import InfoPageShell from "@/app/components/InfoPageShell";
import JsonLd from "@/app/components/JsonLd";
import { createBreadcrumbStructuredData, createPageMetadata } from "@/lib/seo";

const path = "/our-approach" as const;
export const metadata = createPageMetadata({ title: "Our Approach to Musculoskeletal Care", description: "See how Relief Plus combines diagnosis, functional examination, education, and individualized treatment for musculoskeletal care in Lafayette, LA.", path });
export default function Page() { return <><JsonLd data={createBreadcrumbStructuredData(path, "Our Approach")} /><InfoPageShell path={path} breadcrumbLabel="Our Approach" eyebrow="How Relief Plus Thinks Clinically" title="A diagnosis names the condition. The examination makes care personal." description="The diagnosis tells us what condition we may be dealing with. The examination helps us understand how that condition is affecting you." heroPoints={["Pain location is considered alongside function", "Movement and load are assessed in the context of real tasks", "Passive care supports—not replaces—active recovery"]} sections={[
  { eyebrow: "Diagnosis + Function", title: "The same diagnosis can affect two people differently.", paragraphs: ["Diagnosis organizes important information about a condition. Functional examination considers symptom behavior, motion, strength, coordination, load tolerance, and the daily, work, or athletic demands the patient wants to restore.", "Pain location matters, but it does not always identify every contributor. When clinically relevant, the examination may include orthopedic and neurological findings and assess how nearby regions share motion and force."], items: [
    { title: "Neurological evaluation", description: "Strength, sensation, reflexes, nerve-related symptoms, or other findings may be assessed when clinically relevant—not as a universal test list." },
    { title: "Orthopedic evaluation", description: "History, symptom behavior, loading, range of motion, and targeted tests help refine the clinical picture." },
    { title: "Three-dimensional movement", description: "Real tasks involve combinations of bending, rotation, reaching, stepping, and force transfer rather than movement in one plane." },
    { title: "Regional interdependence", description: "The hip, trunk, foot, shoulder, neck, or neighboring region may be examined when its contribution is plausible." },
  ] },
  { eyebrow: "Control + Capacity", title: "Movement quality must meet the demands of the task.", paragraphs: ["Breathing and trunk control may be considered when they meaningfully relate to pressure management, coordination, lifting, gait, or another task. They are examination lenses, not explanations for every symptom.", "Strength, endurance, timing, coordination, and load tolerance help determine whether a person is ready for work, sport, exercise, or daily activity. Progression is individualized rather than built around a universal ideal posture or alignment."] },
  { eyebrow: "Care That Progresses", title: "Relief can open the door; active recovery builds capacity.", paragraphs: ["Adjustments, hands-on care, needling, laser, shockwave, or procedures may help selected patients. When the goal requires greater mobility, strength, coordination, or tolerance, the plan should also create a path toward active recovery.", "Education and self-management help patients understand symptom behavior, adjust activity, respond to flares, and participate in decisions. Imaging, medical evaluation, or specialist referral may be appropriate when examination findings, trauma, neurological change, systemic concerns, or lack of expected progress warrant it."] },
]} cta={{ title: "Begin with an individualized examination.", description: "Call Relief Plus to discuss your symptoms, goals, and the most appropriate next step." }} /></> }
