import InfoPageShell from "@/app/components/InfoPageShell";
import JsonLd from "@/app/components/JsonLd";
import { createBreadcrumbStructuredData, createPageMetadata } from "@/lib/seo";

const path = "/our-approach" as const;
export const metadata = createPageMetadata({ title: "Our Approach to Musculoskeletal Care", description: "See how Relief Plus combines diagnosis, functional examination, education, and individualized treatment for musculoskeletal care in Lafayette, LA.", path });
export default function Page() { return <><JsonLd data={createBreadcrumbStructuredData(path, "Our Approach")} /><InfoPageShell path={path} breadcrumbLabel="Our Approach" eyebrow="What to Expect From Your Care" title="A diagnosis names the condition. The examination makes care personal." description="The diagnosis tells us what condition we may be dealing with. The examination helps us understand how that condition is affecting you." heroPoints={["Pain location is considered alongside function", "We check movements you use at home, work, or sport", "Passive care supports—not replaces—active recovery"]} sections={[
  { eyebrow: "Diagnosis + Function", title: "The same diagnosis can affect two people differently.", paragraphs: ["A diagnosis helps name the problem. Your examination also looks at what you can do: how you move, how strong you are, and how long you can manage an activity before symptoms increase.", "Where it hurts is important, but it may not explain everything. We may check your joints, muscles, nerves, and nearby areas when they could affect the problem."], items: [
    { title: "Neurological evaluation", description: "Strength, sensation, reflexes, nerve-related symptoms, or other findings may be assessed when clinically relevant—not as a universal test list." },
    { title: "Orthopedic evaluation", description: "History, symptom behavior, loading, range of motion, and targeted tests help refine the clinical picture." },
    { title: "Three-dimensional movement", description: "Real tasks involve combinations of bending, rotation, reaching, stepping, and force transfer rather than movement in one plane." },
    { title: "How nearby areas work together", description: "We may check a nearby hip, foot, shoulder, or other area if it could be affecting the movement that hurts." },
  ] },
  { eyebrow: "Control + Capacity", title: "Movement quality must meet the demands of the task.", paragraphs: ["We may look at how you breathe and use your trunk during a lift, a walk, or another difficult task. These checks can offer useful clues, but they do not explain every symptom.", "Being ready for work or sport involves more than feeling less pain. We consider strength, endurance, and how well you manage the task. Your plan builds toward those demands without requiring one perfect posture."] },
  { eyebrow: "Care That Progresses", title: "Relief can open the door; active recovery builds capacity.", paragraphs: ["Adjustments, hands-on care, needling, laser, shockwave, or procedures may help selected patients. When the goal requires greater mobility, strength, coordination, or tolerance, the plan should also create a path toward active recovery.", "Education and self-management help patients understand symptom behavior, adjust activity, respond to flares, and participate in decisions. Imaging, medical evaluation, or specialist referral may be appropriate when examination findings, trauma, neurological change, systemic concerns, or lack of expected progress warrant it."] },
]} cta={{ title: "Tell us what you want to do more comfortably.", description: "Call Relief Plus to discuss your symptoms, goals, and the most appropriate next step." }} /></> }
