import type { Metadata } from "next";
import Link from "next/link";
import Breadcrumbs from "@/app/components/Breadcrumbs";
import JsonLd from "@/app/components/JsonLd";
import SiteFooter from "@/app/components/SiteFooter";
import SiteHeader from "@/app/components/SiteHeader";
import { createBreadcrumbStructuredData, createPageMetadata } from "@/lib/seo";

const path = "/clinical-standards-editorial-review" as const;
export const metadata: Metadata = createPageMetadata({
  title: "Clinical Standards & Editorial Review",
  description: "Learn how Relief Plus develops, sources, reviews, updates, and corrects patient health information published on its website.",
  path,
});

const standards = [
  { title: "Useful to patients", description: "Content begins with a real clinical or practical question and aims to help readers understand reasonable next steps." },
  { title: "Evidence-informed", description: "Appropriate sources may include peer-reviewed literature, recognized clinical guidance, professional organizations, government resources, and academic medical sources." },
  { title: "Clear about uncertainty", description: "Evidence limits, candidacy, alternatives, risks, and differences among diagnoses or procedures should be explained when relevant." },
  { title: "Within professional roles", description: "Contributors address topics that fit their verified training and role. Individual attribution is used only when documented." },
] as const;

export default function ClinicalStandardsPage() {
  return (
    <main className="min-h-screen bg-[#f7f5ef] text-[#12233f]">
      <JsonLd data={createBreadcrumbStructuredData(path, "Clinical Standards & Editorial Review")} />
      <SiteHeader currentPath={path} />
      <section className="px-6 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><Breadcrumbs currentPage="Clinical Standards & Editorial Review" /><div className="mt-12 grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.28em] text-[#82601f]">Clinical Standards & Editorial Review</p><h1 className="mt-6 font-serif text-5xl leading-[1.04] tracking-[-.035em] sm:text-6xl lg:text-7xl">Health information should make care decisions clearer.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[#12233f]/72">Relief Plus publishes patient education to explain musculoskeletal conditions, treatment options, clinical uncertainty, and questions worth discussing with a qualified healthcare professional.</p></div><aside className="rounded-[2rem] bg-[#153e35] p-8 text-white sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#d5b765]">Our Commitment</p><h2 className="mt-5 font-serif text-3xl">Accurate identity. Appropriate evidence. Honest attribution.</h2><p className="mt-6 leading-7 text-white/70">The website is educational. It does not replace an individualized evaluation, diagnosis, treatment plan, or urgent medical care when needed.</p></aside></div></div></section>

      <section className="bg-[#12233f] px-6 py-20 text-white lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#d5b765]">Content Standard</p><h2 className="mt-5 max-w-3xl font-serif text-4xl sm:text-5xl">What guides Relief Plus health information.</h2><div className="mt-12 grid gap-px overflow-hidden rounded-3xl bg-white/10 md:grid-cols-2">{standards.map((item) => <article key={item.title} className="bg-[#12233f] p-8"><h3 className="font-serif text-2xl">{item.title}</h3><p className="mt-4 leading-7 text-white/68">{item.description}</p></article>)}</div><p className="mt-8 max-w-3xl text-sm leading-6 text-white/60">Relief Plus does not claim that every page has undergone a formal systematic review. The depth and frequency of review should reflect the topic, evidence, clinical risk, and likelihood that guidance or regulation may change.</p></div></section>

      <section className="bg-[#e8e5dc] px-6 py-20 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#82601f]">Who Contributes</p><h2 className="mt-5 font-serif text-4xl sm:text-5xl">Different disciplines contribute different perspectives.</h2></div><div className="grid gap-4 sm:grid-cols-2"><Link href="/dr-shawn-johnston-dc" className="rounded-2xl border border-[#12233f]/10 bg-white/60 p-6 transition hover:border-[#b08d3b]"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#82601f]">Chiropractic · Musculoskeletal Care</p><h3 className="mt-3 font-serif text-2xl">Shawn D. Johnston, D.C.</h3><p className="mt-3 text-sm leading-6 text-[#12233f]/68">Dr. Johnston may contribute to chiropractic, musculoskeletal, movement/function, and relevant conservative-care content when his authorship or review is documented.</p></Link><article className="rounded-2xl border border-[#12233f]/10 bg-white/60 p-6"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#82601f]">Physical Therapy · Rehabilitation</p><h3 className="mt-3 font-serif text-2xl">Jeanne Saucier, PT</h3><p className="mt-3 text-sm leading-6 text-[#12233f]/68">Jeanne may contribute to physical therapy and rehabilitation content when she genuinely authors or reviews it. This page does not assign her to existing articles.</p></article><Link href="/dr-ashton-reed-md" className="rounded-2xl border border-[#12233f]/10 bg-white/60 p-6 transition hover:border-[#b08d3b]"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#82601f]">Internal Medicine · Regenerative Care</p><h3 className="mt-3 font-serif text-2xl">Ashton Reed, MD</h3><p className="mt-3 text-sm leading-6 text-[#12233f]/68">Dr. Reed may contribute to medical or regenerative content when he genuinely reviews it. This page does not imply that he reviews all existing content.</p></Link><article className="rounded-2xl border border-[#12233f]/10 bg-white/60 p-6"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#82601f]">Historical Article Attribution</p><h3 className="mt-3 font-serif text-2xl">Relief Plus Editorial</h3><p className="mt-3 text-sm leading-6 text-[#12233f]/68">The 48 retained historical articles remain attributed to Relief Plus Editorial. Provider authorship or review will not be added retroactively without documentation.</p></article></div></div></section>

      <section className="px-6 py-20 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#82601f]">Authorship and Review</p><h2 className="mt-5 font-serif text-4xl sm:text-5xl">Attribution should describe what actually happened.</h2><div className="mt-7 space-y-5 text-lg leading-8 text-[#12233f]/72"><p>Future content may identify who wrote it, who performed a substantive clinical review, and when that review occurred. Those fields appear only when the work is documented.</p><p>A reviewer is not added merely to create an authority signal. The reviewer’s discipline should be relevant to the content, and visible attribution should agree with structured data.</p></div></div><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#82601f]">Updates and Corrections</p><h2 className="mt-5 font-serif text-4xl sm:text-5xl">Review frequency follows the subject.</h2><div className="mt-7 space-y-5 text-lg leading-8 text-[#12233f]/72"><p>Stable clinical education is reviewed periodically. Treatment, regulatory, and advanced-procedure content may require more frequent review because evidence, guidance, products, or rules can change.</p><p>Substantive corrections should be reflected in the content and its updated date. Readers can report a factual concern by emailing <a href="mailto:myreliefplus@gmail.com" className="font-semibold underline decoration-[#b08d3b] underline-offset-4">myreliefplus@gmail.com</a> or calling <a href="tel:+13375654200" className="font-semibold underline decoration-[#b08d3b] underline-offset-4">(337) 565-4200</a>.</p></div></div></div></section>

      <section className="bg-[#153e35] px-6 py-20 text-white lg:px-8"><div className="mx-auto max-w-5xl text-center"><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#d5b765]">Medical Information Boundary</p><h2 className="mt-5 font-serif text-4xl sm:text-5xl">Education supports—but does not replace—individual care.</h2><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-white/70">Website information cannot account for an individual examination, health history, diagnosis, preferences, or treatment needs. New severe symptoms, rapidly worsening neurological changes, major trauma, or other urgent concerns warrant appropriate urgent or emergency evaluation rather than reliance on website information.</p><div className="mt-9 flex flex-col justify-center gap-4 sm:flex-row"><Link href="/about" className="rounded-full bg-[#d5b765] px-7 py-4 text-sm font-semibold text-[#12233f]">About Relief Plus</Link><Link href="/blog" className="rounded-full border border-white/25 px-7 py-4 text-sm font-semibold text-white">Patient Education</Link></div></div></section>
      <SiteFooter />
    </main>
  );
}
