import InfoPageShell from "@/app/components/InfoPageShell";
import JsonLd from "@/app/components/JsonLd";
import { createPageMetadata, createTeamStructuredData } from "@/lib/seo";

const path = "/team" as const;
export const metadata = createPageMetadata({ title: "Relief Plus Team", description: "Meet the verified clinical team listed by Relief Plus for chiropractic, physical therapy, and medical care in Lafayette, Louisiana.", path });
export default function Page() { return <><JsonLd data={createTeamStructuredData()} /><InfoPageShell path={path} breadcrumbLabel="Team" eyebrow="Our Team" title="Different clinical perspectives, one patient-centered plan." description="Relief Plus publicly lists clinicians across chiropractic, physical therapy, and medicine. The profiles below include only names, credentials, and roles verified on the clinic’s existing team page." heroPoints={["Verified public names and credentials only", "Three disciplines with distinct roles", "Care coordinated around the patient’s clinical needs"]} sections={[
  { eyebrow: "Three Disciplines", title: "What each discipline contributes to Relief Plus.", items: [
    { title: "Shawn D. Johnston, D.C.", role: "Chiropractor · Owner", description: "Dr. Johnston has provided chiropractic care in the Lafayette area since 2008. He earned his Doctor of Chiropractic degree from Logan University in 2007. His role centers on chiropractic care, musculoskeletal and functional examination, education, and coordination of appropriate options. Verified Relief Plus material also lists professional training in dry needling and Class IV laser." },
    { title: "Jeanne Saucier, PT", role: "Physical Therapist", description: "Jeanne contributes physical rehabilitation focused on restoring movement, developing strength, progressing load, and helping patients return to meaningful function. No unverified education, specialty, certification, or years-in-practice claims have been added." },
    { title: "Ashton Reed, M.D.", role: "Medical Doctor", description: "Dr. Reed is associated with Relief Plus and contributes medical oversight and appropriate involvement in selected advanced treatment options. Specialty, board certification, education, and specific procedural responsibilities remain intentionally unstated until verified." },
  ] },
  { eyebrow: "Coordinated Care", title: "The provider and treatment should fit the problem.", paragraphs: ["Different disciplines offer different ways to evaluate and support musculoskeletal recovery. Chiropractic may contribute joint and musculoskeletal care; physical therapy may develop movement and capacity; medical involvement may be appropriate when selected advanced options are considered.", "This page does not imply that every patient sees every practitioner or that a fixed handoff workflow applies. Provider availability, scope, and responsibility for a specific procedure should be confirmed directly with Relief Plus."] },
]} cta={{ title: "Talk with Relief Plus about where to begin.", description: "Call the clinic to discuss the concern you want evaluated and the appropriate scheduling path." }} /></> }
