import InfoPageShell from "@/app/components/InfoPageShell";
import JsonLd from "@/app/components/JsonLd";
import { createPageMetadata, createTeamStructuredData } from "@/lib/seo";

const path = "/team" as const;
export const metadata = createPageMetadata({ title: "Relief Plus Team", description: "Meet the verified clinical team listed by Relief Plus for chiropractic, physical therapy, and medical care in Lafayette, Louisiana.", path });
export default function Page() { return <><JsonLd data={createTeamStructuredData()} /><InfoPageShell path={path} breadcrumbLabel="Team" eyebrow="Our Team" title="Different clinical perspectives, one patient-centered plan." description="Relief Plus publicly lists clinicians across chiropractic, physical therapy, and medicine. The profiles below include only names, credentials, and roles verified on the clinic’s existing team page." heroPoints={["Verified public names and credentials only", "Three disciplines with distinct roles", "Care coordinated around the patient’s clinical needs"]} sections={[
  { eyebrow: "Three Disciplines", title: "What each discipline contributes to Relief Plus.", items: [
    { title: "Shawn D. Johnston, D.C.", role: "Chiropractor · Founder", description: "Dr. Johnston has practiced chiropractic since 2008 and founded Relief Plus in 2014. His role centers on chiropractic care, musculoskeletal and functional examination, education, and coordination of appropriate options.", href: "/dr-shawn-johnston-dc" },
    { title: "Jeanne Saucier, PT", role: "Physical Therapist", description: "Jeanne earned her Bachelor of Science in Physical Therapy in 1993. Her broad clinical background informs rehabilitation focused on movement, strength, endurance, and a practical return to meaningful function.", href: "/jeanne-saucier-pt", actionLabel: "Meet Jeanne Saucier, PT", image: { src: "/jeanne-saucier-pt-relief-plus.webp", alt: "Jeanne Saucier, PT, physical therapist at Relief Plus" } },
    { title: "Ashton Reed, MD", role: "Internal Medicine · Medical Oversight", description: "Dr. Reed is a board-certified Internal Medicine physician who provides medical oversight, clinical review, and medical decision-making for patients being considered for regenerative care. His role does not imply that every patient sees him personally.", href: "/dr-ashton-reed-md" },
  ] },
  { eyebrow: "Coordinated Care", title: "The provider and treatment should fit the problem.", paragraphs: ["Different disciplines offer different ways to evaluate and support musculoskeletal recovery. Chiropractic may contribute joint and musculoskeletal care; physical therapy may develop movement and capacity; medical involvement may be appropriate when selected advanced options are considered.", "This page does not imply that every patient sees every practitioner or that a fixed handoff workflow applies. Provider availability, scope, and responsibility for a specific procedure should be confirmed directly with Relief Plus."] },
]} cta={{ title: "Talk with Relief Plus about where to begin.", description: "Call the clinic to discuss the concern you want evaluated and the appropriate scheduling path." }} /></> }
