import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Breadcrumbs from "@/app/components/Breadcrumbs";
import JsonLd from "@/app/components/JsonLd";
import SiteFooter from "@/app/components/SiteFooter";
import SiteHeader from "@/app/components/SiteHeader";
import { createBreadcrumbStructuredData, createPageMetadata } from "@/lib/seo";

const path = "/about" as const;
export const metadata: Metadata = createPageMetadata({
  title: "About Relief Plus",
  description: "Meet the Relief Plus clinical team and learn how chiropractic, physical therapy, physician involvement, and individualized care fit together.",
  path,
});

export default function AboutPage() {
  return (
    <main className="min-h-screen bg-[#f7f5ef] text-[#12233f]">
      <JsonLd data={createBreadcrumbStructuredData(path, "About Relief Plus")} />
      <SiteHeader currentPath={path} />

      <section className="px-6 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><Breadcrumbs currentPage="About Relief Plus" /><div className="mt-12 grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.28em] text-[#82601f]">About Relief Plus</p><h1 className="mt-6 font-serif text-5xl leading-[1.04] tracking-[-.035em] sm:text-6xl lg:text-7xl">Care Is Better When the Person Comes First</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[#12233f]/72">Relief Plus was built around a simple idea: patients should be evaluated as individuals, understand what is happening, and receive care based on what they actually need.</p><p className="mt-5 max-w-2xl text-lg leading-8 text-[#12233f]/72">Chiropractic remains foundational to the clinic, while physical therapy, rehabilitation, physician oversight, and selected medical and regenerative services allow the team to approach musculoskeletal problems from more than one perspective when appropriate. Not every patient sees every provider.</p></div><figure className="overflow-hidden rounded-[2rem] border border-[#12233f]/10"><div className="relative aspect-[4/5]"><Image src="/shawn-d-johnston-dc-relief-plus.webp" alt="Shawn D. Johnston, D.C., founder and chiropractor at Relief Plus" fill priority sizes="(min-width: 1024px) 38vw, 100vw" className="object-cover object-top" /></div><figcaption className="bg-[#153e35] px-7 py-5 text-sm leading-6 text-white/72">Individualized care begins with listening, examination, and a clear explanation of reasonable options.</figcaption></figure></div></div></section>

      <section className="bg-[#12233f] px-6 py-20 text-white lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#d5b765]">Founder · Doctor of Chiropractic</p><h2 className="mt-5 font-serif text-4xl sm:text-5xl">Shawn D. Johnston, D.C.</h2><p className="mt-5 text-sm font-semibold uppercase tracking-[.18em] text-white/55">Chiropractic first, but never in isolation</p></div><div><div className="space-y-5 text-lg leading-8 text-white/72"><p>Dr. Johnston has practiced chiropractic since 2008. He worked at Anesthesiology and Pain Consultants in Lafayette from 2008 through 2014, where a multidisciplinary pain-management environment alongside anesthesiologists and other medical providers helped shape his appreciation for clinical collaboration.</p><p>He founded and opened Relief Plus in 2014 around one central question: What does this particular patient actually need? Chiropractic is foundational, but care can draw on rehabilitation, physician involvement, and selected advanced options when the examination supports them.</p><p>Dr. Johnston earned his Doctor of Chiropractic and Bachelor of Science in Life Science from Logan University in 2007 after pre-medical studies in Biology and Chemistry at Freed-Hardeman University.</p><p>His owner-verified training includes Dry Needling through the American Dry Needling Association, Class IV Laser Therapy through LightForce, Titleist Performance Institute Level I, Selective Functional Movement Assessment training, Motion Palpation Institute coursework, and continuing education across spinal and extremity assessment, rehabilitation, gait, whiplash-associated disorders, TMJ/orofacial rehabilitation, and related musculoskeletal topics. He has presented on Selective Functional Movement Assessment for other healthcare professionals and is a member of the American Chiropractic Association and Louisiana Chiropractic Association.</p></div><blockquote className="mt-9 border-l-4 border-[#d5b765] pl-6"><p className="font-serif text-2xl leading-snug">“The goal isn’t to do more treatment. It’s to understand the person well enough to know what treatment actually makes sense.”</p><footer className="mt-4 text-sm font-semibold text-[#d5b765]">— Shawn D. Johnston, D.C.</footer></blockquote><Link href="/dr-shawn-johnston-dc" className="mt-9 inline-block rounded-full bg-[#d5b765] px-6 py-3 text-sm font-semibold text-[#12233f]">Meet Dr. Johnston</Link></div></div></section>

      <section className="bg-[#e8e5dc] px-6 py-20 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[.8fr_1.2fr]"><figure className="overflow-hidden rounded-[2rem] border border-[#12233f]/10 bg-white/60"><div className="relative aspect-[4/5]"><Image src="/ashton-reed-md-relief-plus.webp" alt="Ashton Reed, MD, Internal Medicine physician at Relief Plus" fill sizes="(min-width: 1024px) 34vw, 100vw" className="object-cover object-top" /></div></figure><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#82601f]">Internal Medicine · Medical Oversight</p><h2 className="mt-5 font-serif text-4xl sm:text-5xl">Ashton Reed, MD</h2><p className="mt-4 font-semibold text-[#153e35]">Medical Oversight — Regenerative Medicine Program</p><div className="mt-7 space-y-5 text-lg leading-8 text-[#12233f]/72"><p>Dr. Reed is a board-certified Internal Medicine physician in Lafayette. He completed his Internal Medicine residency through LSU Health Sciences Center at University Hospital and Clinics in Lafayette.</p><p>At Relief Plus, Dr. Reed provides medical oversight, clinical review, and medical decision-making for patients being considered for regenerative care, with physician involvement in selected regenerative and injection-based services.</p><p>This role does not mean that every regenerative patient sees Dr. Reed personally, that he performs every injection, or that he is continuously onsite. Patients should confirm the provider and process for a specific service directly with Relief Plus.</p></div><Link href="/dr-ashton-reed-md" className="mt-9 inline-block rounded-full bg-[#12233f] px-6 py-3 text-sm font-semibold text-white">Meet Dr. Reed</Link></div></div></section>

      <section className="px-6 py-20 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[.8fr_1.2fr]"><figure className="overflow-hidden rounded-[2rem] border border-[#12233f]/10 bg-white/60"><div className="relative aspect-[4/5]"><Image src="/jeanne-saucier-pt-relief-plus.webp" alt="Jeanne Saucier, PT, physical therapist at Relief Plus" fill sizes="(min-width: 1024px) 34vw, 100vw" className="object-cover object-[center_20%]" /></div></figure><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#82601f]">Physical Therapy · Rehabilitation</p><h2 className="mt-5 font-serif text-4xl sm:text-5xl">Jeanne Saucier, PT</h2><p className="mt-4 font-semibold text-[#153e35]">Physical Therapist — Relief Plus</p><div className="mt-7 space-y-5 text-lg leading-8 text-[#12233f]/72"><p>Jeanne earned her Bachelor of Science in Physical Therapy from LSU Medical Center’s Allied Health program in New Orleans in 1993. Her physical-therapy experience dates to 1993 and spans outpatient rehabilitation, acute care, long-term care, home health, pediatric and school-based therapy, and cardiac rehabilitation.</p><p>At Relief Plus, Jeanne focuses on progressive rehabilitation that helps patients rebuild mobility, strength, endurance, confidence, and capacity for daily life, work, exercise, and recreation. Physical therapy may stand alone or coordinate with other care when appropriate; not every patient requires rehabilitation or sees every provider.</p></div><Link href="/jeanne-saucier-pt" className="mt-9 inline-block rounded-full bg-[#12233f] px-6 py-3 text-sm font-semibold text-white">Meet Jeanne Saucier, PT</Link></div></div></section>

      <section className="bg-[#153e35] px-6 py-20 text-white lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl text-center"><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#d5b765]">One Clinical Team</p><h2 className="mt-5 font-serif text-4xl sm:text-5xl">Three Perspectives. One Patient.</h2><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-white/72">Relief Plus combines access to chiropractic, physical therapy, and physician involvement without implying that every patient needs all three. Each discipline contributes a distinct perspective, and the plan should reflect the individual clinical picture.</p><div className="mx-auto mt-10 grid max-w-5xl gap-4 text-left md:grid-cols-3"><article className="rounded-2xl border border-white/12 bg-white/5 p-6"><h3 className="font-serif text-2xl">Dr. Johnston</h3><p className="mt-3 text-sm leading-6 text-white/68">Chiropractic and musculoskeletal evaluation, movement and mechanical function, and appropriate conservative care.</p></article><article className="rounded-2xl border border-white/12 bg-white/5 p-6"><h3 className="font-serif text-2xl">Jeanne Saucier, PT</h3><p className="mt-3 text-sm leading-6 text-white/68">Rehabilitation, progressive loading, strength, mobility, endurance, and restoring meaningful function.</p></article><article className="rounded-2xl border border-white/12 bg-white/5 p-6"><h3 className="font-serif text-2xl">Dr. Reed</h3><p className="mt-3 text-sm leading-6 text-white/68">Physician oversight of the regenerative medicine program and appropriate medical decision-making.</p></article></div><div className="mx-auto mt-8 grid max-w-4xl gap-4 text-left sm:grid-cols-3"><div className="rounded-2xl border border-white/12 bg-white/5 p-6"><p className="font-serif text-2xl">Understand the problem.</p></div><div className="rounded-2xl border border-white/12 bg-white/5 p-6"><p className="font-serif text-2xl">Choose the appropriate care.</p></div><div className="rounded-2xl border border-white/12 bg-white/5 p-6"><p className="font-serif text-2xl">Help the patient move forward.</p></div></div><div className="mt-10 flex flex-col justify-center gap-4 sm:flex-row"><Link href="/clinical-standards-editorial-review" className="rounded-full bg-[#d5b765] px-7 py-4 text-sm font-semibold text-[#12233f]">Clinical Standards & Editorial Review</Link><Link href="/team" className="rounded-full border border-white/25 px-7 py-4 text-sm font-semibold text-white">View the Team</Link></div></div></section>

      <section className="px-6 py-20 lg:px-8"><div className="mx-auto max-w-7xl rounded-[2rem] bg-[#12233f] px-8 py-14 text-white sm:px-12 lg:flex lg:items-center lg:justify-between"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#d5b765]">Contact Relief Plus</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Start With an Evaluation</h2><p className="mt-5 text-lg leading-8 text-white/70">If pain, an injury, or a movement problem is interfering with work, training, family activity, or daily life, the first step is understanding what is going on.</p></div><a href="tel:+13375654200" className="mt-8 inline-block rounded-full bg-[#d5b765] px-7 py-4 text-sm font-semibold text-[#12233f] lg:mt-0">Call (337) 565-4200</a></div></section>
      <SiteFooter />
    </main>
  );
}
