import LegalPageShell from "@/app/components/LegalPageShell";
import { createPageMetadata } from "@/lib/seo";

const path = "/privacy-policy" as const;
export const metadata = createPageMetadata({ title: "Website Privacy Policy", description: "Website privacy information for the current Relief Plus website, separate from the clinic’s HIPAA Notice and Good Faith Estimate.", path });
export default function Page() { return <LegalPageShell path={path} title="Website Privacy Policy" description="This policy describes the observable behavior of the current Relief Plus website. It is separate from the HIPAA Notice of Privacy Practices, which governs protected health information handled by the clinic." notice="This website provides informational pages, a website search tool, and phone-based scheduling. It does not include an online contact form, patient portal, online booking, embedded map, advertising pixel, or visible analytics integration." sections={[
  { title: "Information you choose to provide", paragraphs: ["The website does not offer online scheduling. Website searches run locally in your browser; the search tool does not send your typed questions to an AI service or the website server. Selecting a telephone link opens your device’s calling feature; the website does not receive the content of your call.", "The site displays the clinic’s email address. Information sent by email is handled outside this website. Ordinary email may not be secure, so do not send urgent or sensitive medical information unless the clinic provides appropriate instructions."] },
  { title: "Website search", paragraphs: ["The search tool downloads an index of published Relief Plus pages and finds matching passages in your browser. Results link to the original pages. It does not generate AI answers, send search questions to an external service, or save search history in a database or browser storage. Questions remain in memory while the page is open. Please do not enter personal medical information; this is not a patient portal or a way to obtain a diagnosis or emergency care."] },
  { title: "Technical website operation", paragraphs: ["Like websites generally, the hosting and network services used to deliver the site may process standard technical request information such as IP address, browser type, requested pages, timestamps, and security or diagnostic data. The production hosting provider, retention periods, and access controls require owner verification before more specific representations can be made.", "The application itself does not currently set an analytics or advertising cookie, load Google Analytics, add Vercel Analytics, or include an advertising pixel. Essential platform or infrastructure behavior should be re-audited after deployment."] },
  { title: "Third-party links and services", paragraphs: ["Some pages link to external clinical research, government guidance, or other websites. Those sites have their own privacy practices. The current site does not embed a map or third-party booking experience."] },
  { title: "HIPAA and patient information", paragraphs: ["This website privacy policy is not the clinic’s HIPAA Notice of Privacy Practices. Review the separate HIPAA notice for information about medical records, permitted uses and disclosures, patient rights, and complaints."] },
  { title: "Changes and contact", paragraphs: ["This policy must be reviewed and updated before adding forms, online scheduling, analytics, cookies, embedded maps, advertising technology, email-marketing collection, or other third-party scripts.", "Questions about this website can be directed to Relief Plus at 337-565-4200. A policy effective date and responsible privacy contact have not yet been supplied and require owner/legal review."] },
]} /> }
