import LegalPageShell from "@/app/components/LegalPageShell";
import { createPageMetadata } from "@/lib/seo";

const path = "/privacy-policy" as const;
export const metadata = createPageMetadata({ title: "Website Privacy Policy", description: "Website privacy information for the current Relief Plus website, separate from the clinic’s HIPAA Notice and Good Faith Estimate.", path });
export default function Page() { return <LegalPageShell path={path} title="Website Privacy Policy" description="This policy describes the observable behavior of the current Relief Plus website. It is separate from the HIPAA Notice of Privacy Practices, which governs protected health information handled by the clinic." notice="This website provides informational pages, an AI website assistant, and phone-based scheduling. It does not include an online contact form, patient portal, online booking, embedded map, advertising pixel, or visible analytics integration." sections={[
  { title: "Information you choose to provide", paragraphs: ["The website does not offer online scheduling. Questions entered into the AI assistant are sent to the website’s server and an AI service to generate a response. Selecting a telephone link opens your device’s calling feature; the website does not receive the content of your call.", "The site displays the clinic’s email address. Information sent by email is handled outside this website. Ordinary email may not be secure, so do not send urgent or sensitive medical information unless the clinic provides appropriate instructions."] },
  { title: "AI website assistant", paragraphs: ["The assistant uses published Relief Plus website information to answer general questions. Your question and recent conversation context are processed through Vercel AI Gateway and an AI model provider. Please do not enter names, dates of birth, contact details, medical records, or other sensitive personal information. This is not a patient portal or a way to obtain a diagnosis or emergency care.", "The application does not save chat transcripts in a database or browser storage. Recent messages stay in memory while the page is open. The application requests that OpenAI responses not be stored, but hosting and AI providers may process or retain information under their own policies; this is not a guarantee of zero retention. The application uses temporary hashed network identifiers to limit repeated requests. AI answers may be incorrect; consult the linked website sources and contact the clinic to confirm details."] },
  { title: "Technical website operation", paragraphs: ["Like websites generally, the hosting and network services used to deliver the site may process standard technical request information such as IP address, browser type, requested pages, timestamps, and security or diagnostic data. The production hosting provider, retention periods, and access controls require owner verification before more specific representations can be made.", "The application itself does not currently set an analytics or advertising cookie, load Google Analytics, add Vercel Analytics, or include an advertising pixel. Essential platform or infrastructure behavior should be re-audited after deployment."] },
  { title: "Third-party links and services", paragraphs: ["Some pages link to external clinical research, government guidance, or other websites. Those sites have their own privacy practices. The current site does not embed a map or third-party booking experience."] },
  { title: "HIPAA and patient information", paragraphs: ["This website privacy policy is not the clinic’s HIPAA Notice of Privacy Practices. Review the separate HIPAA notice for information about medical records, permitted uses and disclosures, patient rights, and complaints."] },
  { title: "Changes and contact", paragraphs: ["This policy must be reviewed and updated before adding forms, online scheduling, analytics, cookies, embedded maps, advertising technology, email-marketing collection, or other third-party scripts.", "Questions about this website can be directed to Relief Plus at 337-565-4200. A policy effective date and responsible privacy contact have not yet been supplied and require owner/legal review."] },
]} /> }
