import type { EducationSection, PillarPageData } from "./pillar-pages";

export type ConditionClinicalContent = {
  serviceTitle: string;
  serviceSteps: PillarPageData["serviceSteps"];
  whoDescription: string;
  approachDescription: string;
  faqs: PillarPageData["faqs"];
  educationSections: EducationSection[];
  pageSources: NonNullable<PillarPageData["pageSources"]>;
};

export const backPainClinical: ConditionClinicalContent = {
  serviceTitle: "A back-pain examination connects symptoms with real-life movement.",
  serviceSteps: [
    { title: "Map symptom behavior", description: "We may compare sitting, standing, walking, bending, lifting, flexion, and extension to learn which directions or loads ease, reproduce, centralize, or spread symptoms." },
    { title: "Examine movement and nerves", description: "The examination may include lumbar, hip, and thoracic movement; strength and endurance; gait; reflexes, sensation, or nerve tension when leg symptoms are present; and task-specific control." },
    { title: "Match care to the findings", description: "The goal is not a perfect posture or one ideal movement. It is to identify useful options, concerning findings, and a tolerable path back to the activities that matter." },
  ],
  whoDescription: "Back pain can be local, movement-related, persistent, or accompanied by leg symptoms. The same label can reflect different symptom behavior, neurological findings, work demands, and recovery priorities.",
  approachDescription: "Chiropractic care is considered first when clinically relevant joint restriction, pain, or guarding limits movement. Physical therapy then helps rebuild mobility, coordination, endurance, lifting capacity, and confidence. Regenerative medicine or adjunctive treatments are separate considerations for selected diagnoses and candidates—not automatic additions to a back-pain plan.",
  faqs: [
    { question: "Does back pain mean my spine is damaged?", answer: "Not necessarily. Pain intensity and tissue damage do not always match. History, symptom behavior, examination, and—when indicated—imaging help determine whether a specific structure or medical condition needs attention." },
    { question: "Is a weak core the reason my back hurts?", answer: "Core capacity may matter for some people, but “core weakness” alone is an incomplete explanation. Breathing, trunk coordination, hip and thoracic movement, task demands, sleep, recovery, and load tolerance may also influence the plan." },
    { question: "Should I avoid bending or lifting?", answer: "Complete avoidance is rarely a durable strategy, but the appropriate amount and technique depend on symptom behavior and diagnosis. Temporary load modification followed by individualized progression may be more useful." },
    { question: "When is imaging useful?", answer: "Imaging may be appropriate when serious pathology is suspected, neurological loss is progressive, trauma or other risk factors are present, or the result is likely to change management. Routine imaging is not needed for every episode." },
  ],
  educationSections: [
    { eyebrow: "Why Care Differs", title: "Two people with back pain may need very different starting points.", paragraphs: ["One person may have a recent lifting episode that improves with walking; another may have persistent symptoms, reduced endurance, fear of bending, or pain extending below the knee. Age, onset, tissue irritability, neurological findings, health history, work or sport demands, and goals change what is safe and useful.", "A diagnosis names a condition or symptom category. The examination helps show how it is affecting this person today, what movements remain available, and which tasks have lost tolerance."], items: [{ title: "Direction matters", description: "Repeated movement may draw leg symptoms toward the back—often called centralization—or farther down the leg—peripheralization. When present, that response is interpreted with the rest of the examination." }, { title: "Capacity matters", description: "Tolerance for sitting, walking, carrying, rotation, and repeated lifting may guide progression more than a single strength test." }] },
    { eyebrow: "Beyond the Painful Area", title: "The back works with the hips, rib cage, trunk, and feet.", paragraphs: ["We may observe how the hips and thoracic spine contribute during bending and rotation, whether the person can vary between a squat and hip-hinge strategy, and how force travels during walking, stepping, carrying, or work tasks.", "Breathing, diaphragm activity, rib-cage and pelvic position, and abdominal pressure may influence trunk coordination under load. These are adaptable strategies—not proof that one breathing pattern or posture caused pain."], items: [{ title: "Three-dimensional movement", description: "Daily activity combines forward-and-back, side-to-side, and rotational motion. Reduced options in one region may place additional demand elsewhere." }, { title: "Protective strategies", description: "Guarding or stiffness may be a short-term response to pain. It becomes clinically relevant only when it limits useful movement or recovery." }] },
    { eyebrow: "Possible Functional Contributors", title: "Contributors are working hypotheses, not a verdict.", items: [{ title: "Overworking muscles", description: "Some muscles may appear to brace or work continuously while others contribute less efficiently during a task." }, { title: "Force transfer", description: "The trunk and hips may have difficulty coordinating or absorbing load during lifting, gait, or deceleration." }, { title: "Movement variability", description: "Reliance on one guarded strategy may reduce options, but normal asymmetry and variation are not automatically problems." }, { title: "Endurance and recovery", description: "Symptoms may relate to how long a position or task is sustained, not simply whether the movement is “good” or “bad.”" }] },
    { eyebrow: "How Therapies May Fit", title: "Hands-on care can open a window; active care builds on it.", paragraphs: ["Chiropractic adjustments or mobilization may be considered for relevant joint restriction, pain, or guarding. Physical therapy and therapeutic exercise may develop hip and trunk coordination, strength, endurance, movement confidence, and graded lifting or walking tolerance.", "Education supports pacing, less fearful interpretation of symptoms, position changes, and gradual return to activity. Dry needling may address selected muscular pain. Class IV laser is a non-invasive adjunct for selected cases without promises of healing or inflammation reduction. Advanced options require a diagnosis-specific candidacy review and are not routine back-pain treatment."],
    },
    { eyebrow: "What You Can Do", title: "Use symptoms as information without letting them dictate permanent avoidance.", items: [{ title: "Keep tolerable movement", description: "Short walks, position changes, and comfortable daily movement may be preferable to prolonged bed rest unless a clinician advises otherwise." }, { title: "Modify load temporarily", description: "Reduce or divide demanding tasks, then rebuild them progressively instead of assuming they must be abandoned." }, { title: "Track meaningful patterns", description: "Notice whether symptoms move toward or away from the spine, whether strength or sensation changes, and which activities change function." }, { title: "Follow an individual progression", description: "A generic exercise list cannot account for diagnosis, irritability, neurological findings, or goals." }] },
    { eyebrow: "When More Evaluation Is Needed", title: "Most back pain is not an emergency, but some changes should not wait.", paragraphs: ["Seek urgent medical evaluation for new loss of bladder or bowel control, numbness around the saddle or genital region, rapidly progressive leg weakness, or severe symptoms after significant trauma. Prompt medical assessment is also appropriate when back pain occurs with fever, significant infection risk, a cancer history, unexplained weight loss, or other systemic illness.", "New or worsening neurological loss, disabling symptoms that are not improving, or a clinical picture that does not fit routine musculoskeletal care may warrant imaging, medical referral, or specialist involvement."],
    },
  ],
  pageSources: [
    { label: "NICE: Low back pain and sciatica recommendations", href: "https://www.nice.org.uk/guidance/NG59/chapter/recommendations", note: "Guidance on assessment, self-management, exercise, manual therapy, imaging, and referral." },
    { label: "American College of Physicians low-back-pain guideline", href: "https://www.acponline.org/sites/default/files/acp-policy-library/guidelines/noninvasive_treatments_for_chronic_low_back_pain_2017.pdf", note: "Evidence-based recommendations for noninvasive care." },
  ],
};

export const neckPainClinical: ConditionClinicalContent = {
  serviceTitle: "A neck examination looks beyond a snapshot of posture.",
  serviceSteps: [
    { title: "Clarify the pattern", description: "We may ask about onset, headache or jaw relationships, screen and sleep positions, reaching, overhead work, and whether symptoms remain local or extend into an arm." },
    { title: "Test relevant systems", description: "Assessment may include cervical and thoracic motion, shoulder-blade coordination, strength and endurance, arm nerve mobility, sensation, reflexes, and symptom response to selected positions." },
    { title: "Build a useful plan", description: "Findings are interpreted together to decide whether education, joint care, rehabilitation, an adjunct, imaging, or medical referral is the appropriate next step." },
  ],
  whoDescription: "Neck pain may involve motion loss, headache, shoulder-region discomfort, or arm symptoms. Similar complaints can reflect different mechanical, neurological, workload, and recovery factors.",
  approachDescription: "Chiropractic care may address clinically relevant cervical or thoracic joint restriction and guarding. Physical therapy may develop neck and shoulder endurance, rib-cage and trunk coordination, comfortable rotation, reaching, and tolerance for sustained tasks. Regenerative medicine is considered only for a defined diagnosis and appropriate candidate; it is not a default response to neck pain.",
  faqs: [
    { question: "Is my posture causing my neck pain?", answer: "Posture may influence symptoms or sustained load, but there is no single perfect posture and posture alone rarely explains the full problem. Variation, movement breaks, capacity, task demands, sleep, and symptom behavior also matter." },
    { question: "Can neck pain cause headaches?", answer: "Some headache patterns can be associated with the neck, but headaches have many possible causes. New, severe, unusual, or neurologically accompanied headaches require appropriate medical assessment." },
    { question: "Why are my shoulder blades or breathing assessed?", answer: "The neck, upper back, ribs, shoulders, and trunk coordinate during reaching and sustained work. Those findings may help plan care, but they are not assumed to be the cause." },
    { question: "What if pain or tingling travels into my arm?", answer: "Arm symptoms prompt a neurological and musculoskeletal screen. Progressive weakness, loss of coordination, widespread numbness, balance change, or other concerning findings may require referral." },
  ],
  educationSections: [
    { eyebrow: "Why Care Differs", title: "The same neck-pain label can describe very different problems.", paragraphs: ["A person with a recent strain and local stiffness may need a different plan from someone with persistent desk-related symptoms, headaches, a prior collision, or arm weakness and numbness. Symptom distribution, neurological findings, duration, health history, work demands, and goals shape decisions.", "Pain with one posture does not prove that posture damaged the neck. The examination asks what changes symptoms, which movements are available, and how the person tolerates real tasks."],
    },
    { eyebrow: "Beyond the Neck", title: "Turning, breathing, and reaching involve more than the cervical spine.", paragraphs: ["Thoracic motion and rib-cage position may influence how much movement the neck supplies during rotation or looking overhead. Breathing strategy and diaphragm–trunk coordination can affect how the upper chest, ribs, and neck muscles share work, especially during stress or sustained tasks.", "We may observe shoulder-blade motion during reaching, the ability to rotate through the trunk, jaw or headache relationships where relevant, and how screen, driving, sleep, or overhead positions affect symptoms."], items: [{ title: "Neighboring regions", description: "Limited thoracic or shoulder contribution may place additional demand on the neck, but this remains one factor to test—not a presumed cause." }, { title: "Task-specific control", description: "Someone may move comfortably in a clinic but lose endurance during hours of computer work or repeated overhead activity." }] },
    { eyebrow: "Possible Functional Contributors", title: "Coordination and endurance can matter as much as flexibility.", items: [{ title: "Protective muscle activity", description: "Neck or shoulder muscles may appear to overwork in response to pain, stress, or insufficient support from neighboring regions." }, { title: "Scapular contribution", description: "Shoulder-blade coordination may influence reaching and load transfer without being labeled “bad posture.”" }, { title: "Reduced movement options", description: "A person may rely on the neck when the upper back or trunk contributes less during rotation." }, { title: "Sustained-load tolerance", description: "Symptoms may emerge after time because endurance and recovery are limited, not because one seated position is inherently harmful." }] },
    { eyebrow: "How Therapies May Fit", title: "Treatment may address motion, capacity, symptoms, or several layers at once.", paragraphs: ["Chiropractic care may improve available cervical or thoracic motion and reduce guarding when appropriate. Physical therapy may retrain coordinated neck, shoulder, rib-cage, and trunk movement; build endurance; and progress reaching, work, or exercise demands.", "Education can support movement breaks, varied positions, sleep strategies, pacing, and reduced fear. Dry needling may be considered for selected muscular pain or protective tension, and Class IV laser may be a non-invasive adjunct in selected cases. Neither modality corrects the whole condition by itself."],
    },
    { eyebrow: "What You Can Do", title: "Aim for comfortable variation, not a rigid perfect posture.", items: [{ title: "Change positions", description: "Brief movement breaks and varied working positions may be more practical than holding one “correct” pose." }, { title: "Use tolerable motion", description: "Gentle, comfortable movement may help maintain options, but radiating or neurological symptoms should guide professional advice." }, { title: "Track arm symptoms", description: "Report new weakness, spreading numbness, loss of hand coordination, or meaningful changes in symptom distribution." }, { title: "Progress for the task", description: "Exercise should eventually prepare the neck and upper quarter for the person’s actual work, sport, and daily demands." }] },
    { eyebrow: "When More Evaluation Is Needed", title: "Certain headache, neurological, trauma, or systemic findings need medical attention.", paragraphs: ["Prompt or urgent assessment is appropriate for major trauma, new severe or unusual headache, fever or significant illness, progressive arm weakness, or signs concerning for cervical myelopathy such as new hand clumsiness, balance or walking difficulty, changes affecting both arms or legs, or bowel or bladder dysfunction.", "Persistent radiating symptoms, rapidly worsening neurological findings, or a presentation that does not respond as expected may require imaging, medical referral, or specialist evaluation. Imaging decisions should reflect the clinical scenario rather than pain alone."],
    },
  ],
  pageSources: [
    { label: "APTA Orthopedics: Neck Pain Clinical Practice Guideline", href: "https://www.orthopt.org/uploads/content_files/files/Neck%20Pain%20CPG%20-%20Revision%202017.pdf", note: "Guidance on classification, examination, activity limits, exercise, and multimodal care." },
    { label: "ACR Appropriateness Criteria: Cervical Pain or Radiculopathy", href: "https://pubmed.ncbi.nlm.nih.gov/40409873/", note: "Current evidence-based imaging guidance for different cervical presentations." },
  ],
};

export const sciaticaClinical: ConditionClinicalContent = {
  serviceTitle: "A sciatica examination follows the symptoms and the nervous system.",
  serviceSteps: [
    { title: "Trace the distribution", description: "We ask where symptoms begin and travel, whether pain or altered sensation reaches the foot, and which sitting, walking, bending, coughing, or lifting situations change the pattern." },
    { title: "Screen nerve function", description: "Depending on the presentation, the examination may include strength, reflexes, sensation, nerve-tension testing, gait, lumbar movement, and signs that suggest a non-spinal mimic." },
    { title: "Observe directional response", description: "Selected repeated movements may show symptoms centralizing toward the spine or peripheralizing farther down the leg. This response can guide care but is not interpreted in isolation." },
  ],
  whoDescription: "Sciatica is a leg-symptom pattern, not one single diagnosis. Nerve-root irritation is common, but hip, peripheral nerve, vascular, and other conditions can sometimes resemble it.",
  approachDescription: "Chiropractic care may be considered for relevant lumbar or pelvic joint restriction and symptom modulation when safe. Physical therapy may develop directional movement, nerve mobility when appropriate, trunk and hip coordination, walking tolerance, and graded return to lifting. Regenerative medicine is not automatically indicated for sciatica and requires a separate diagnosis-specific candidacy review.",
  faqs: [
    { question: "Is every pain down the leg sciatica?", answer: "No. Referred pain, hip conditions, peripheral nerve irritation, vascular problems, and other conditions may create similar symptoms. Distribution and neurological examination help clarify the pattern." },
    { question: "What do centralization and peripheralization mean?", answer: "Centralization means symptoms retreat from the leg toward the spine during a movement or position; peripheralization means they extend farther down the limb. When consistent, this information may help guide treatment." },
    { question: "Does sciatica always require an MRI?", answer: "No. Imaging is generally considered when serious pathology or progressive neurological loss is suspected, when symptoms remain disabling despite appropriate care, or when results are likely to change management." },
    { question: "Can I keep walking?", answer: "Tolerable activity is often encouraged, but the appropriate amount depends on weakness, balance, symptom behavior, diagnosis, and medical advice." },
  ],
  educationSections: [
    { eyebrow: "What the Pattern Means", title: "Sciatica describes symptoms; the examination searches for the mechanism.", paragraphs: ["Sciatica commonly refers to pain, burning, tingling, numbness, or weakness following part of the sciatic nerve pathway. Lumbar nerve-root irritation may be involved, but the word itself does not identify the exact tissue, level, or cause.", "Symptoms alone cannot distinguish disc-related radiculopathy from narrowing around a nerve root or a non-spinal mimic. Self-diagnosis based only on where pain travels can therefore be misleading."],
    },
    { eyebrow: "Why Care Differs", title: "Two people with leg pain may respond to opposite strategies.", paragraphs: ["One person may feel better walking and worse sitting; another may tolerate sitting but develop symptoms with standing or extension. Strength, reflexes, sensation, symptom duration, movement response, work demands, and walking tolerance can point to different priorities.", "A severe-feeling symptom does not automatically establish severity of nerve injury, but objective weakness or progressive neurological change carries particular importance."],
    },
    { eyebrow: "Beyond the Leg", title: "Lumbar, hip, trunk, gait, and load response all provide clues.", paragraphs: ["We may observe lumbar and hip motion, trunk control, gait, balance, sitting tolerance, bending, and how symptoms behave during repeated or sustained positions. Hip or trunk coordination may influence demand during walking and lifting but is not presumed to be the cause.", "A protective strategy—such as avoiding one leg, bracing continuously, or limiting spinal movement—may be useful early and limiting later. The response must be interpreted with neurological findings."], items: [{ title: "Nervous-system screen", description: "Strength, reflexes, sensation, and symptom distribution help assess whether a nerve root may be involved and whether referral is needed." }, { title: "Non-spinal mimics", description: "Hip disorders, peripheral nerve entrapment, vascular conditions, and other medical problems may require a different path." }] },
    { eyebrow: "How Therapies May Fit", title: "Care is selected around neurological safety and functional response.", paragraphs: ["Chiropractic care may address appropriate joint restrictions or help reduce guarding; it is not used to claim that a vertebra is “out.” Physical therapy may use individualized directional movement, graded nerve mobility when indicated, hip and trunk coordination, strengthening, and progressive walking or lifting exposure.", "Education supports pacing, position changes, and understanding symptom behavior. Dry needling may address a separate muscular contributor but does not treat nerve-root pathology itself. Advanced treatments require a defined diagnosis and candidacy review; not every person with sciatica is a candidate."],
    },
    { eyebrow: "What You Can Do", title: "Protect the nerve without becoming afraid of all movement.", items: [{ title: "Use tolerable positions", description: "Change positions before symptoms become overwhelming and use the movement direction recommended for your presentation." }, { title: "Watch distribution", description: "Notice whether symptoms retreat toward the back or spread farther down the leg and report consistent changes." }, { title: "Modify, then rebuild", description: "Temporarily adjust lifting, sitting, or walking volume while working toward gradual recovery of capacity." }, { title: "Report neurological change", description: "New weakness, foot drop, saddle numbness, or bowel or bladder change should not be managed as routine soreness." }] },
    { eyebrow: "When More Evaluation Is Needed", title: "Progressive weakness and cauda-equina symptoms require urgent action.", paragraphs: ["Seek immediate evaluation for new bladder or bowel dysfunction, new sexual dysfunction with severe radiating back pain, numbness in the saddle or perineal region, or rapidly progressive leg weakness. These may signal cauda equina syndrome or another neurological emergency.", "Prompt medical assessment is also important for significant trauma, fever or infection risk, cancer history, unexplained systemic symptoms, vascular warning signs, or disabling symptoms that do not follow an expected course."],
    },
  ],
  pageSources: [
    { label: "NICE: Low back pain and sciatica recommendations", href: "https://www.nice.org.uk/guidance/NG59/chapter/recommendations", note: "Assessment, self-management, imaging, conservative care, and specialist referral guidance." },
    { label: "NICE: Neurological conditions recognition and referral", href: "https://www.nice.org.uk/guidance/ng127/chapter/Recommendations-for-adults-aged-over-16", note: "Urgent referral guidance for cauda equina and progressive neurological presentations." },
  ],
};

export const herniatedDiscClinical: ConditionClinicalContent = {
  serviceTitle: "A disc finding becomes meaningful only when it matches the person.",
  serviceSteps: [
    { title: "Correlate symptoms", description: "We compare the location and behavior of neck, back, arm, or leg symptoms with the suspected spinal level rather than assuming an MRI phrase explains everything." },
    { title: "Check neurological function", description: "Strength, sensation, reflexes, gait, coordination, and nerve-tension findings may help determine whether a nerve root is affected and whether referral is needed." },
    { title: "Assess movement and load", description: "When clinically relevant, flexion, extension, rotation, sitting, walking, lifting, and selected repeated-movement responses may show what is currently tolerated and whether symptoms centralize or peripheralize." },
  ],
  whoDescription: "Disc herniations can occur in the neck or lower back. Some produce local pain, some affect a nerve root, and some appear on imaging without causing symptoms.",
  approachDescription: "Chiropractic care may support appropriate joint motion and reduce guarding when neurological and medical screening indicate it is safe. Physical therapy may use symptom-guided movement, strength and coordination training, education, and graded return to work or activity. The main pathway remains progressive, function-focused care with imaging or referral when clinical findings warrant it.",
  faqs: [
    { question: "Does a herniated disc on MRI prove it is causing my pain?", answer: "No. Disc findings can exist without symptoms. The location of the finding, symptom distribution, neurological examination, movement response, and overall clinical picture must agree." },
    { question: "Can a herniated disc improve without surgery?", answer: "Many people improve with time and nonsurgical management, but the course varies. Progressive neurological loss, emergency symptoms, or persistent disabling pain may change referral decisions." },
    { question: "Should I avoid all flexion or lifting?", answer: "Not automatically. Irritable movements may be modified temporarily, but long-term restrictions should be based on symptom behavior, neurological findings, job or activity needs, and graded progression." },
    { question: "When might imaging or specialist referral be considered?", answer: "Referral may be appropriate for progressive or significant neurological loss, emergency symptoms, major trauma, concerning systemic findings, an uncertain diagnosis, or persistent disabling symptoms when imaging would change management." },
  ],
  educationSections: [
    { eyebrow: "What the Diagnosis Means", title: "An imaging description is not the complete diagnosis.", paragraphs: ["A spinal disc has an outer ring and an inner gel-like region. Herniation describes disc material extending beyond its usual boundary. Whether that matters depends on location, size, contact with nerves, inflammation, and—most importantly—whether findings match symptoms and examination.", "Words such as bulge, degeneration, or herniation can sound alarming, yet imaging changes are also found in people without pain. The scan should inform care, not define the person or predict the future by itself."],
    },
    { eyebrow: "Why Care Differs", title: "The same MRI phrase can accompany different symptoms and abilities.", paragraphs: ["One person may have local back pain without nerve findings; another may have leg pain, numbness, weakness, or altered reflexes. Cervical disc symptoms can similarly involve the neck, shoulder blade, arm, hand, strength, or coordination.", "Onset, neurological status, direction of symptom change, function, work demands, health history, prior episodes, and goals determine whether care begins conservatively or requires additional evaluation."],
    },
    { eyebrow: "Beyond the Disc", title: "We evaluate movement options, nerve function, and real-world load tolerance.", paragraphs: ["The examination may compare spinal and hip movement, gait, balance, reaching, lifting, sitting, and repeated-movement responses. Breathing and trunk-pressure coordination may influence how load is managed, but a single coordination finding does not prove why a disc herniated.", "Centralization or peripheralization can be clinically useful when consistent. Changes in strength, sensation, reflexes, hand coordination, or walking receive greater weight because they may reflect neurological involvement."], items: [{ title: "Protective compensation", description: "A person may brace, shift, or avoid one direction. That strategy may reduce symptoms temporarily and later need graded expansion." }, { title: "Neighbor contribution", description: "Hip, thoracic, shoulder, or trunk movement may affect task demand without being labeled the root cause." }] },
    { eyebrow: "How Therapies May Fit", title: "Treatment addresses the patient’s presentation—not an attempt to push a disc into place.", paragraphs: ["Chiropractic care may be used carefully for clinically relevant joint restriction or guarding when examination findings support it. It is not described as realigning the spine or physically replacing disc material. Physical therapy may focus on symptom-guided movement, strength, coordination, education, and gradual restoration of work or activity capacity.", "Dry needling may address selected secondary muscular pain. Class IV laser is a possible non-invasive adjunct for selected presentations without a promise of disc healing or inflammation reduction. Advanced options, if discussed at all, are limited to selected musculoskeletal cases after diagnosis, evidence review, candidacy assessment, and discussion of alternatives; they are not presented as repairing, regenerating, replacing, or restoring a disc."],
    },
    { eyebrow: "What You Can Do", title: "Let neurological status and symptom behavior guide progression.", items: [{ title: "Stay reasonably active", description: "Tolerable walking and position changes may help maintain function; prolonged bed rest is generally not a default strategy." }, { title: "Use temporary modification", description: "Adjust provocative load while gradually rebuilding the specific sitting, lifting, reaching, or sport demands you need." }, { title: "Avoid imaging fear", description: "Discuss what the report means clinically instead of assuming every finding represents ongoing damage." }, { title: "Monitor nerve function", description: "Report worsening weakness, numbness, coordination, balance, or bowel and bladder changes promptly." }] },
    { eyebrow: "When More Evaluation Is Needed", title: "Imaging and referral are driven by risk and clinical change.", paragraphs: ["Urgent evaluation is warranted for significant or progressive arm or leg weakness, saddle or genital numbness, loss of bladder or bowel control, major trauma, or concerning systemic features such as fever with infection risk or a relevant cancer history.", "Imaging or specialist referral may also be considered when symptoms remain disabling despite appropriate conservative care, when the diagnosis is uncertain, or when results would change a procedural or surgical decision."],
    },
  ],
  pageSources: [
    { label: "American Association of Neurological Surgeons: Herniated Disc", href: "https://www.aans.org/patients/conditions-treatments/herniated-disc/", note: "Patient guidance on symptoms, neurological findings, imaging, conservative care, and urgent referral." },
    { label: "NICE: Imaging quality standard for back pain and sciatica", href: "https://www.nice.org.uk/guidance/qs155/chapter/Quality-statement-2-Referrals-for-imaging", note: "Guidance explaining why routine imaging is often unnecessary unless serious pathology is suspected." },
  ],
};

export const pinchedNerveClinical: ConditionClinicalContent = {
  serviceTitle: "A “pinched nerve” examination first identifies which nervous-system pattern fits.",
  serviceSteps: [
    { title: "Map symptoms", description: "We ask where pain, tingling, numbness, or weakness travels and how neck, back, shoulder, elbow, wrist, hip, or leg positions change it." },
    { title: "Compare nerve pathways", description: "Strength, reflexes, sensation, nerve mobility, spinal movement, and selected peripheral tests may help distinguish nerve-root irritation from entrapment farther along a limb." },
    { title: "Screen alternatives", description: "Referred joint pain, muscular pain, vascular conditions, spinal cord findings, and other medical problems can mimic nerve symptoms and may need a different evaluation." },
  ],
  whoDescription: "“Pinched nerve” is a useful everyday phrase, but it can refer to cervical or lumbar nerve-root irritation, peripheral nerve entrapment, referred pain, or local muscular symptoms.",
  approachDescription: "Chiropractic care may address appropriate spinal or neighboring joint restrictions that influence symptoms. Physical therapy may use nerve-sensitive movement, strength, coordination, ergonomics, and gradual exposure to gripping, reaching, walking, or lifting. Regenerative medicine is not a general treatment for an undefined “pinched nerve” and requires a specific diagnosis and candidacy review.",
  faqs: [
    { question: "How do you know where a nerve is irritated?", answer: "Symptom distribution is compared with strength, reflexes, sensation, movement response, and provocative or relieving tests. Sometimes imaging or electrodiagnostic testing is needed when location remains unclear or findings are significant." },
    { question: "Could tingling come from a muscle instead?", answer: "Muscles and joints can refer pain, but true numbness, weakness, or a recognizable nerve distribution increases concern for neurological involvement. The examination distinguishes among possibilities rather than relying on one symptom." },
    { question: "Is a pinched nerve permanent?", answer: "Not necessarily. Many nerve-root presentations improve, but recovery depends on the mechanism and severity. Progressive weakness or spinal-cord signs require timely referral." },
    { question: "Should I stretch the nerve?", answer: "Aggressive stretching is not automatically appropriate. Nerve mobility work, if used, should match irritability, location, neurological findings, and response." },
  ],
  educationSections: [
    { eyebrow: "What the Phrase Can Mean", title: "“Pinched nerve” does not identify one diagnosis or one location.", paragraphs: ["A spinal nerve root can be irritated near the neck or lower back. A peripheral nerve can also be compressed or sensitive near the shoulder, elbow, wrist, hip, knee, or ankle. Referred pain from joints or muscles can feel similar without true nerve dysfunction.", "The term therefore starts a conversation; it does not prove compression, identify the structure, or determine treatment."],
    },
    { eyebrow: "Why Care Differs", title: "Similar tingling can come with different neurological findings.", paragraphs: ["One person may have neck-related arm pain with altered reflexes; another may have hand tingling influenced by wrist position; a third may have muscular referral without objective neurological loss. Duration, trauma, health history, work exposure, strength, sensation, and symptom distribution change priorities.", "Two people with the same diagnostic label may also differ in movement, coordination, load tolerance, and recovery goals."],
    },
    { eyebrow: "Beyond the Symptom Location", title: "We follow the nerve pathway and the movements around it.", paragraphs: ["For arm symptoms, we may examine the neck, shoulder blade, shoulder, elbow, wrist, grip, reaching, and sustained work positions. For leg symptoms, we may assess the lumbar spine, hip, gait, balance, knee, ankle, and task-related loading.", "Breathing, rib-cage and trunk coordination, and proximal stability may influence how the limb manages load. These findings are potential contributors, not proof of the nerve’s compression site."], items: [{ title: "Neurological examination", description: "Strength, reflexes, sensation, coordination, and symptom distribution help identify whether nerve function is changing." }, { title: "Position and movement", description: "A symptom may increase or ease with spinal position, limb tension, gripping, reaching, walking, or sustained compression." }] },
    { eyebrow: "Possible Functional Contributors", title: "Load, space, and coordination can influence nerve sensitivity.", items: [{ title: "Neighboring joint motion", description: "Reduced movement in the spine, shoulder, hip, or another region may place additional demand on a nerve pathway." }, { title: "Protective tension", description: "Muscles may overwork to guard an irritable area; treating tension alone does not establish or resolve the neurological diagnosis." }, { title: "Repetitive demand", description: "Sustained gripping, screen work, reaching, sitting, or walking may exceed current nerve and tissue tolerance." }, { title: "Altered force transfer", description: "Reduced proximal coordination may influence limb loading, but it must be interpreted alongside neurological findings." }] },
    { eyebrow: "How Therapies May Fit", title: "The treatment target depends on where and why symptoms arise.", paragraphs: ["Chiropractic care may address clinically relevant joint restriction and movement when safe and appropriate. Physical therapy may use graded nerve mobility, strengthening, movement retraining, ergonomic changes, and progressive task exposure. Education helps patients distinguish tolerable symptoms from meaningful neurological change.", "Dry needling or trigger-point injections may be considered only for a separate, clinically relevant muscular component; they do not decompress a nerve root. Laser is a possible adjunct in selected cases without a guaranteed neurological outcome. Advanced options require a specific diagnosis and candidacy review."],
    },
    { eyebrow: "What You Can Do and When to Escalate", title: "Modify irritation while watching strength, sensation, and coordination.", paragraphs: ["Temporarily reduce sustained pressure or repetitive tasks that consistently worsen symptoms, vary positions, and follow an individualized progression rather than aggressively stretching an irritable nerve. Report changes in grip, foot control, balance, sensation, or task performance.", "Seek prompt medical evaluation for progressive or significant weakness, rapidly worsening neurological findings, major trauma, systemic illness, or signs concerning for cervical myelopathy such as new balance or walking difficulty, loss of hand coordination, or symptoms affecting multiple limbs. New bowel or bladder dysfunction or saddle sensory change with back and leg symptoms requires urgent evaluation."],
    },
  ],
  pageSources: [
    { label: "AAOS OrthoInfo: Cervical Radiculopathy (Pinched Nerve)", href: "https://www.orthoinfo.org/diseases--conditions/cervical-radiculopathy-pinched-nerve/", note: "Peer-reviewed patient guidance on symptoms, examination, mimics, neurological testing, and care." },
    { label: "APTA Orthopedics: Neck Pain Clinical Practice Guideline", href: "https://www.orthopt.org/uploads/content_files/files/Neck%20Pain%20CPG%20-%20Revision%202017.pdf", note: "Guidance on radiating neck pain, neurological findings, examination, and multimodal care." },
  ],
};
