import type { BlogPost } from "./blog-posts";

const lowBackGuideline = { title: "Low Back Pain Clinical Practice Guideline", organization: "Academy of Orthopaedic Physical Therapy", href: "https://www.orthopt.org/content/practice/clinical-practice-guidelines/low-back-pain" };
const headacheClassification = { title: "International Classification of Headache Disorders", organization: "International Headache Society", href: "https://ichd-3.org/" };

export const phaseNineFBlogPosts: BlogPost[] = [
  {
    slug: "why-your-back-hurts-when-you-stand-too-long-lafayette-la-guide", path: "/blog/why-your-back-hurts-when-you-stand-too-long-lafayette-la-guide",
    title: "Why Your Back May Hurt When You Stand Too Long", seoTitle: "Why Back Pain Can Worsen With Standing | Relief Plus", description: "Learn why prolonged standing can aggravate back pain, how movement variability and load tolerance matter, and when symptoms need evaluation.", category: "Back & Spine", summary: "Standing is not inherently harmful, but sustained position and insufficient capacity for the task can provoke symptoms. The useful answer is usually more nuanced than correcting one posture.", datePublished: "2026-06-09T11:16:51-05:00", readTime: "7 min read",
    sections: [
      { heading: "Static standing is still a load", paragraphs: ["Even without lifting, the back, hips, and legs continually manage body weight. Holding one position limits variation and can make sensitive tissues feel tired. This does not prove damage; it identifies a current tolerance limit.", "Standing at a counter, waiting in line, and working on concrete are different tasks. Duration, footwear, reach, surface, fatigue, and the previous day’s activity all influence the response."] },
      { heading: "Posture is one variable—not a verdict", paragraphs: ["An arched or relaxed posture is not universally bad. Constantly bracing or forcing a textbook position can become uncomfortable too. Useful strategies include changing stance, shifting weight, using a foot support briefly, walking for a minute, or alternating tasks."] },
      { heading: "The hips and legs share the job", paragraphs: ["Hip motion, calf endurance, foot comfort, trunk coordination, and breathing under load can alter how standing feels. Examination should determine whether changing a neighboring region actually improves familiar symptoms rather than assuming an alignment fault."] },
      { heading: "Build standing capacity progressively", paragraphs: ["Rehabilitation may combine graded standing, walking, hip and trunk strength, lifting, and work-specific endurance. Track both the response during a task and recovery afterward. The goal is broader options and longer tolerance, not dependence on one posture."] },
      { heading: "Symptoms that change the plan", paragraphs: ["Leg pain, numbness, weakness, or symptoms that move farther down the limb warrant neurological assessment. New bowel or bladder dysfunction, saddle sensory change, major trauma, fever, unexplained illness, or progressive weakness requires prompt medical evaluation."] },
    ], related: [{ title: "Back pain care", href: "/back-pain-lafayette", description: "Explore individualized back-pain evaluation." }, { title: "Physical therapy", href: "/physical-therapy-lafayette", description: "Build standing and work tolerance." }, { title: "Sciatica", href: "/sciatica-treatment-lafayette", description: "Understand back-related leg symptoms." }], sources: [lowBackGuideline],
  },
  {
    slug: "strengthening-your-foundation-top-three-exercises-for-low-back-stability", path: "/blog/strengthening-your-foundation-top-three-exercises-for-low-back-stability",
    title: "Three Ways to Explore Low-Back Stability—Without a One-Size-Fits-All Program", seoTitle: "Low-Back Stability Exercise Principles | Relief Plus", description: "Learn what trunk stability means and how breathing, coordination, graded exercise, and symptom response guide safe low-back training.", category: "Rehabilitation & Function", summary: "Stability is the ability to coordinate force and movement for a task—not keeping the spine rigid or having visibly strong abdominal muscles. Exercise choice should match symptoms and goals.", datePublished: "2024-04-24T09:13:45-05:00", readTime: "8 min read",
    sections: [
      { heading: "Stability is adaptable control", paragraphs: ["The trunk must sometimes resist motion and sometimes create it. Breathing, abdominal pressure, hips, shoulders, and timing all contribute. Bracing as hard as possible is not the goal for every lift, step, or breath."] },
      { heading: "Strategy one: supported trunk control", paragraphs: ["A low-load starting point might involve lying or standing while gently coordinating an exhale with abdominal tension and limb movement. The spine need not be flattened or held rigid. Reduce range or support the limbs if symptoms increase."] },
      { heading: "Strategy two: resist rotation", paragraphs: ["A band press, suitcase carry, or asymmetrical hold can train the trunk to manage rotational force. Begin with a load and stance that feel controlled, then progress resistance, distance, or movement—not all at once."] },
      { heading: "Strategy three: connect to bending and lifting", paragraphs: ["Hip hinges, squats, step patterns, and carries translate coordination into daily tasks. There is no universally perfect lifting shape; technique should fit the object, environment, capacity, and symptom behavior."] },
      { heading: "Modify or stop when the response is wrong", paragraphs: ["Mild effort or temporary local discomfort can be acceptable, but rapidly increasing pain, symptoms spreading down a limb, new numbness or weakness, loss of coordination, or lasting deterioration requires adjustment and possibly evaluation. These examples are education, not a personal prescription."] },
    ], related: [{ title: "Back pain care", href: "/back-pain-lafayette", description: "Match exercise to the presentation." }, { title: "Physical therapy", href: "/physical-therapy-lafayette", description: "Progress strength and task function." }, { title: "Our approach", href: "/our-approach", description: "See how individualized plans are built." }], sources: [lowBackGuideline],
  },
  {
    slug: "understanding-and-managing-mortons-neuroma-a-comprehensive-guide", path: "/blog/understanding-and-managing-mortons-neuroma-a-comprehensive-guide",
    title: "Morton’s Neuroma: Understanding Burning Forefoot Pain", seoTitle: "Morton’s Neuroma and Forefoot Pain Guide | Relief Plus", description: "Understand interdigital nerve irritation, forefoot loading, footwear considerations, differential diagnoses, and when specialist evaluation may help.", category: "Hip & Lower Extremity", summary: "Morton’s neuroma describes irritation and thickening around an interdigital nerve, often producing burning, tingling, or the feeling of a pebble under the forefoot. Similar symptoms require differentiation.", datePublished: "2024-05-15T09:17:41-05:00", readTime: "8 min read",
    sections: [
      { heading: "What the condition means", paragraphs: ["Symptoms commonly occur between the third and fourth toes, although another web space can be involved. Tight toe boxes, forefoot compression, and repeated push-off may increase irritation. The term neuroma is historical; the problem is not typically a true nerve tumor."] },
      { heading: "Walking and footwear provide clues", paragraphs: ["Narrow shoes or higher heels can increase pressure across the metatarsal heads. A wider toe box, lower heel, or metatarsal support may reduce symptoms for some people. Footwear changes should improve function, not become a claim that one shoe corrects every foot."] },
      { heading: "Other conditions can feel similar", paragraphs: ["Metatarsal stress injury, joint irritation, plantar-plate problems, peripheral neuropathy, lumbar or peripheral nerve symptoms, and inflammatory conditions can overlap. Examination considers location, sensation, compression, walking, footwear, and health history."] },
      { heading: "Conservative care and capacity", paragraphs: ["Temporary load modification, suitable footwear, foot and calf strength, and gradual return to walking or running may help. The hips and trunk can influence task demands, but should be included only when findings show relevance."] },
      { heading: "When specialist input is useful", paragraphs: ["Persistent numbness or burning, progressive symptoms, major swelling, trauma, suspected stress injury, diabetes or systemic neuropathy concerns, or failure of reasonable conservative care may warrant podiatry, orthopedic, neurological, or imaging evaluation."] },
    ], related: [{ title: "Services", href: "/services", description: "Browse Relief Plus evaluation and care options." }, { title: "Physical therapy", href: "/physical-therapy-lafayette", description: "Build walking and lower-extremity capacity." }, { title: "Pinched nerve", href: "/pinched-nerve-lafayette", description: "Understand other nerve-related patterns." }], sources: [{ title: "Morton’s Neuroma", organization: "American Academy of Orthopaedic Surgeons", href: "https://orthoinfo.aaos.org/en/diseases--conditions/mortons-neuroma/" }],
  },
  {
    slug: "headaches-that-wont-go-away-it-might-not-be-what-you-think", path: "/blog/headaches-that-wont-go-away-it-might-not-be-what-you-think",
    title: "When Headaches Keep Returning: Classification Before Assumption", seoTitle: "Persistent Headaches: Patterns and Red Flags | Relief Plus", description: "Learn why persistent headaches require classification, how migraine, tension-type, cervicogenic, TMJ, and medication-overuse patterns differ, and when to seek care.", category: "Headache", summary: "A headache that keeps returning should not automatically be blamed on the neck, posture, stress, or the jaw. Pattern, associated symptoms, medication use, examination, and change over time guide the next step.", datePublished: "2026-03-27T10:41:03-05:00", readTime: "9 min read",
    sections: [
      { heading: "Persistent is a description, not a diagnosis", paragraphs: ["Migraine can include nausea, light or sound sensitivity, activity aggravation, and sometimes aura. Tension-type headache is more often pressing or tightening and less aggravated by routine activity. People can have more than one headache type."] },
      { heading: "The neck and jaw may contribute—but do not explain everything", paragraphs: ["Cervicogenic headache is attributed to a cervical disorder and may relate to neck movement or reduced motion. Neck soreness also occurs with migraine. TMJ disorders may involve jaw pain, chewing sensitivity, limited opening, or painful clicking. Examination should test whether these findings are meaningfully connected."] },
      { heading: "Medication use belongs in the history", paragraphs: ["Frequent use of acute headache medication can contribute to medication-overuse headache in susceptible people. This requires a medical discussion; patients should not abruptly alter prescribed medication based on an article."] },
      { heading: "Visual and work demands can amplify symptoms", paragraphs: ["Screen duration, glare, uncorrected vision, sleep, workload, hydration, and prolonged static positions may influence a headache without establishing its diagnosis. A diary can track frequency, duration, associated features, medication use, and context."] },
      { heading: "Red flags change urgency", paragraphs: ["Seek urgent evaluation for a sudden severe headache, new weakness or speech difficulty, confusion, fever with neck stiffness, major trauma, substantial visual change, or a new pregnancy/postpartum headache pattern. A major change from the usual pattern, steadily worsening headache, or persistent uncertainty deserves medical evaluation."] },
    ], related: [{ title: "Headache care", href: "/headache-treatment-lafayette", description: "Review classification and evaluation." }, { title: "Neck pain", href: "/neck-pain-lafayette", description: "Explore when neck findings are relevant." }, { title: "TMJ care", href: "/tmj-treatment-lafayette", description: "Understand jaw-related symptom patterns." }], sources: [headacheClassification, { title: "Medication-overuse headache", organization: "International Headache Society", href: "https://ichd-3.org/8-headache-attributed-to-a-substance-or-its-withdrawal/8-2-medication-overuse-headache-moh/" }],
  },
  {
    slug: "pregnancy-pain-whats-normal-whats-not-and-how-to-find-relief-safely", path: "/blog/pregnancy-pain-whats-normal-whats-not-and-how-to-find-relief-safely",
    title: "Musculoskeletal Pain During Pregnancy: What Deserves Attention", seoTitle: "Back and Pelvic Pain During Pregnancy | Relief Plus", description: "A conservative guide to pregnancy-related back and pelvic discomfort, movement, sleep, activity tolerance, and when obstetric evaluation comes first.", category: "Rehabilitation & Function", summary: "Back and pelvic discomfort are common during pregnancy, but pain should not automatically be dismissed as normal. Obstetric or medical concerns must be considered before musculoskeletal care.", datePublished: "2026-03-28T10:44:31-05:00", readTime: "9 min read",
    sections: [
      { heading: "Pregnancy changes demands—not just posture", paragraphs: ["Changing body mass, center of gravity, sleep, fatigue, ligament behavior, and daily tasks alter how the back, pelvis, hips, and legs manage load. Symptoms vary widely; one alignment or weak-muscle explanation is inadequate."] },
      { heading: "Activity is individualized", paragraphs: ["For uncomplicated pregnancies, professional guidance supports continued physical activity with appropriate modifications. Walking, strength, mobility, and water-based activity may be useful, but an obstetric clinician should address contraindications and pregnancy-specific restrictions before a program is started or changed."] },
      { heading: "Comfort strategies should remain flexible", paragraphs: ["Position changes, pillows for sleep support, shorter activity bouts, supportive footwear, and modifying lifting or carrying may improve tolerance. Recommendations depending on gestational stage or medical status should come from the obstetric care team."] },
      { heading: "Rehabilitation stays within musculoskeletal scope", paragraphs: ["When obstetric causes have been considered, rehabilitation may address comfortable movement, hip and trunk coordination, strength, breathing, and task demands. Relief Plus does not claim that chiropractic changes fetal position or improves labor or delivery outcomes."] },
      { heading: "Contact the obstetric team when appropriate", paragraphs: ["Severe or persistent back pain, fever, burning with urination, vaginal bleeding, fluid leakage, regular painful contractions, abdominal pain, dizziness, chest pain, calf pain or swelling, breathing difficulty, or other concerning changes require obstetric or urgent guidance. Medication decisions belong with the appropriate medical clinician."] },
    ], related: [{ title: "Physical therapy", href: "/physical-therapy-lafayette", description: "Explore individualized movement and function." }, { title: "Services", href: "/services", description: "Review the Relief Plus care framework." }, { title: "Our approach", href: "/our-approach", description: "See how scope and referral guide decisions." }], sources: [{ title: "Back Pain During Pregnancy", organization: "American College of Obstetricians and Gynecologists", href: "https://www.acog.org/womens-health/faqs/back-pain-during-pregnancy" }, { title: "Physical Activity and Exercise During Pregnancy", organization: "American College of Obstetricians and Gynecologists", href: "https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2020/04/physical-activity-and-exercise-during-pregnancy-and-the-postpartum-period" }],
  },
  {
    slug: "piriformis-syndrome-and-l5-s1-disc-bulge-a-comparative-insight-by-dr-shawn-johnston-at-relief-plus", path: "/blog/piriformis-syndrome-and-l5-s1-disc-bulge-a-comparative-insight-by-dr-shawn-johnston-at-relief-plus",
    title: "Piriformis-Like Pain vs. Lumbar Nerve-Root Symptoms", seoTitle: "Piriformis vs. Lumbar Disc and Sciatica Symptoms | Relief Plus", description: "Learn how buttock and leg symptoms may differ between deep-gluteal irritation and lumbar nerve-root problems—and why symptom maps or MRI alone are insufficient.", category: "Back & Spine", summary: "Buttock and leg pain can arise through different mechanisms. “Piriformis syndrome” should not be the default explanation for sciatica, and a disc bulge on imaging does not automatically identify the source.", datePublished: "2024-03-20T08:17:57-05:00", readTime: "9 min read",
    sections: [
      { heading: "Similar symptoms can have different sources", paragraphs: ["Lumbar nerve-root irritation may create radiating pain, numbness, tingling, weakness, or reflex change. Deep-gluteal region symptoms may be more strongly influenced by sitting, hip position, or local loading. Considerable overlap makes examination essential."] },
      { heading: "Distribution is a clue, not a diagnosis", paragraphs: ["A textbook map cannot account for every person or distinguish all peripheral nerves from nerve roots. Strength, reflexes, sensation, walking, neural loading, spinal and hip movement, and symptom response must be considered together."] },
      { heading: "Movement and position may clarify behavior", paragraphs: ["Repeated movement may centralize symptoms toward the back or peripheralize them farther down the limb. Hip loading may reproduce a deep-gluteal complaint. These findings may be assessed when relevant; not everyone receives every test."] },
      { heading: "Imaging requires context", paragraphs: ["Disc bulges are common in people without symptoms. Imaging is most useful when it matches the clinical pattern and will change management. It should not override a reassuring neurological examination or be used to predict recovery by itself."] },
      { heading: "Escalation and rehabilitation", paragraphs: ["Progressive weakness, saddle sensory change, new bowel or bladder dysfunction, rapidly worsening neurological findings, or systemic illness requires prompt medical evaluation. Otherwise, education, movement, graded nerve and tissue loading, and task-specific rehabilitation may be appropriate. The historical URL naming Dr. Johnston does not establish authorship."] },
    ], related: [{ title: "Sciatica care", href: "/sciatica-treatment-lafayette", description: "Review differential assessment and recovery." }, { title: "Herniated disc", href: "/herniated-disc-lafayette", description: "Understand disc and neurological findings." }, { title: "Physical therapy", href: "/physical-therapy-lafayette", description: "Build movement and load tolerance." }], sources: [lowBackGuideline, { title: "Herniated Disk", organization: "American Academy of Orthopaedic Surgeons", href: "https://orthoinfo.aaos.org/en/diseases--conditions/herniated-disk/" }],
  },
  {
    slug: "understanding-arm-numbness-differentiating-causes-by-symptoms", path: "/blog/understanding-arm-numbness-differentiating-causes-by-symptoms",
    title: "Arm Numbness: Why Distribution Alone Is Not a Diagnosis", seoTitle: "Arm Numbness: Neck, Nerve, and Medical Patterns | Relief Plus", description: "Understand cervical radiculopathy, peripheral nerve entrapment, task and position effects, vascular concerns, and urgent signs associated with arm numbness.", category: "Spine & Nerve", summary: "Arm numbness may involve a cervical nerve root, a peripheral nerve, more than one compression site, or a medical or vascular cause. Symptom maps are useful clues—not stand-alone diagnoses.", datePublished: "2024-03-27T11:07:27-05:00", readTime: "9 min read",
    sections: [
      { heading: "Start with distribution and context", paragraphs: ["Neck-related nerve irritation may travel through the shoulder and arm with pain, tingling, numbness, or weakness. Median-nerve symptoms often affect the thumb-side hand, while ulnar-nerve symptoms commonly involve the ring and little fingers. Real patterns frequently overlap."] },
      { heading: "Position and task dependence add information", paragraphs: ["Neck motion, overhead work, elbow flexion, wrist position, gripping, vibration, or sleeping posture may change symptoms. This helps organize possibilities but does not prove one entrapment site."] },
      { heading: "Examination goes beyond sensation", paragraphs: ["Strength in specific muscles, reflexes, sensation, coordination, pulses and color when relevant, neck and upper-limb movement, and selected nerve-loading or compression tests can refine the picture. Thoracic outlet concepts require caution because provocative tests can be nonspecific."] },
      { heading: "Some causes are not musculoskeletal", paragraphs: ["Diabetes, medication effects, systemic neuropathy, circulation problems, and neurological disease may contribute. Sudden one-sided numbness with facial weakness, speech difficulty, severe headache, chest symptoms, or shortness of breath requires emergency evaluation."] },
      { heading: "Treat the supported mechanism", paragraphs: ["Care may include task modification, movement, nerve or tissue loading, strength, and treatment of relevant neck or limb findings. Progressive weakness, muscle wasting, loss of coordination, rapidly worsening numbness, or unclear persistent symptoms warrants medical or specialist evaluation."] },
    ], related: [{ title: "Pinched nerve care", href: "/pinched-nerve-lafayette", description: "Explore neurological examination and treatment options." }, { title: "Neck pain", href: "/neck-pain-lafayette", description: "Understand neck-related arm symptoms." }, { title: "Physical therapy", href: "/physical-therapy-lafayette", description: "Restore task and upper-limb tolerance." }], sources: [{ title: "Neck Pain Clinical Practice Guideline", organization: "Academy of Orthopaedic Physical Therapy", href: "https://www.orthopt.org/uploads/content_files/files/Neck%20Pain%20CPG%20-%20Revision%202017.pdf" }, { title: "Carpal Tunnel Syndrome Clinical Practice Guideline", organization: "Academy of Orthopaedic Physical Therapy", href: "https://www.orthopt.org/content/practice/clinical-practice-guidelines/carpal-tunnel-syndrome" }],
  },
  {
    slug: "easing-the-grip-of-disc-bulge-with-radicular-pain-traction-and-adjusting-at-relief-plus", path: "/blog/easing-the-grip-of-disc-bulge-with-radicular-pain-traction-and-adjusting-at-relief-plus",
    title: "Disc-Related Radicular Pain: Traction, Manual Care, and Active Recovery", seoTitle: "Disc Bulge, Radicular Pain, and Traction | Relief Plus", description: "A balanced guide to disc findings, radicular symptoms, neurological screening, traction evidence, manual care, rehabilitation, imaging, and referral.", category: "Back & Spine", summary: "Traction and manual care may be considered for selected radicular presentations, but neither pulls a disc back into place. Neurological status, symptom behavior, active rehabilitation, and response guide care.", datePublished: "2024-03-14T16:06:04-05:00", readTime: "9 min read",
    sections: [
      { heading: "A bulge is not automatically the problem", paragraphs: ["Disc bulges appear on many scans from people without pain. A symptomatic disc-related presentation is more plausible when history, movement behavior, neurological findings, and imaging—if needed—tell a coherent story."] },
      { heading: "Radicular symptoms require neurological screening", paragraphs: ["Pain radiating into a limb can occur with or without true nerve-root dysfunction. Strength, reflexes, sensation, walking, and nerve-loading findings help assess involvement and severity. Progressive weakness changes urgency."] },
      { heading: "Centralization and peripheralization can guide care", paragraphs: ["When clinically relevant, repeated movements may draw symptoms out of the limb toward the back or move them farther away. This response can inform exercise direction, but it is not a universal test and should not be forced."] },
      { heading: "Traction and manual care are adjuncts", paragraphs: ["Traction research shows mixed average effects, with some support in selected radicular care when combined with other rehabilitation. It does not create guaranteed decompression or repair a disc. Chiropractic manipulation or mobilization may help selected patients after screening, but should support movement rather than replace active care."] },
      { heading: "Rehabilitation, imaging, and referral", paragraphs: ["Progressive walking, strength, movement, nerve tolerance, and return to work or lifting remain central. Imaging or medical referral may be appropriate after major trauma, with significant or progressive neurological findings, systemic concerns, or when results would change management. New bowel or bladder dysfunction or saddle sensory change requires urgent evaluation."] },
    ], related: [{ title: "Herniated disc care", href: "/herniated-disc-lafayette", description: "Review neurological status and treatment pathways." }, { title: "Sciatica", href: "/sciatica-treatment-lafayette", description: "Understand radiating leg symptoms." }, { title: "Chiropractic", href: "/chiropractic-adjustments-lafayette", description: "See where screened manual care may fit." }], sources: [lowBackGuideline, { title: "Traction for lumbar radiculopathy: systematic review and meta-analysis", organization: "PubMed", href: "https://pubmed.ncbi.nlm.nih.gov/33382419/" }],
  },
];
