import type { PillarLink, PillarPageData } from "./pillar-pages";

type PageInput = {
  path: PillarPageData["path"];
  name: string;
  eyebrow: string;
  h1: string;
  title: string;
  description: string;
  hero: string;
  overviewTitle: string;
  overview: string[];
  examTitle: string;
  exam: PillarPageData["serviceSteps"];
  dailyTitle: string;
  dailyDescription: string;
  daily: PillarPageData["considerations"];
  related: PillarPageData["conditions"];
  approach: string;
  therapies: PillarLink[];
  sections: NonNullable<PillarPageData["educationSections"]>;
  faqs: PillarPageData["faqs"];
  sources: NonNullable<PillarPageData["pageSources"]>;
};

function page(input: PageInput): PillarPageData {
  return {
    path: input.path,
    breadcrumbLabel: input.name,
    eyebrow: input.eyebrow,
    h1: input.h1,
    seoTitle: input.title,
    seoDescription: input.description,
    heroDescription: input.hero,
    heroPoints: [
      "Diagnosis and functional contributors are considered separately",
      "Movement is assessed in the context of meaningful tasks",
      "Treatment is selected from findings, goals, and clinical suitability",
    ],
    overviewTitle: input.overviewTitle,
    overviewParagraphs: input.overview,
    serviceTitle: input.examTitle,
    serviceSteps: input.exam,
    whoTitle: input.dailyTitle,
    whoDescription: input.dailyDescription,
    considerations: input.daily,
    conditionsDescription:
      "Related symptoms can overlap without sharing the same diagnosis. These guides provide context; an examination is needed to identify the most relevant pattern.",
    conditions: input.related,
    approachDescription: input.approach,
    relatedServices: input.therapies,
    educationSections: input.sections,
    faqs: input.faqs,
    pageSources: input.sources,
    ctaTitle: `Begin with an individualized ${input.name.toLowerCase()} evaluation.`,
    ctaDescription:
      "Call Relief Plus in Lafayette to discuss your symptoms, functional goals, and an appropriate next step for care in Acadiana.",
  };
}

const chiropractic = (description: string): PillarLink => ({ title: "Chiropractic", href: "/chiropractic-adjustments-lafayette", description });
const pt = (description: string): PillarLink => ({ title: "Physical Therapy", href: "/physical-therapy-lafayette", description });
const dry = (description: string): PillarLink => ({ title: "Dry Needling", href: "/dry-needling-lafayette", description });
const laser = (description: string): PillarLink => ({ title: "Class IV Laser Therapy", href: "/class-iv-laser-therapy-lafayette", description });
const shockwave = (description: string): PillarLink => ({ title: "Shockwave Therapy", href: "/shockwave-therapy-lafayette", description });
const prp = (description: string): PillarLink => ({ title: "PRP Therapy", href: "/prp-therapy-lafayette", description });

export const kneeOsteoarthritisPage = page({
  path: "/knee-osteoarthritis-lafayette",
  name: "Knee Osteoarthritis",
  eyebrow: "Knee Osteoarthritis Care in Lafayette, Louisiana",
  h1: "Knee osteoarthritis care focused on capacity, confidence, and function.",
  title: "Knee Osteoarthritis Treatment in Lafayette, LA",
  description: "Knee osteoarthritis treatment in Lafayette, LA with individualized physical therapy, progressive exercise, and evidence-informed options at Relief Plus.",
  hero: "Knee osteoarthritis is more than an X-ray phrase. Relief Plus evaluates symptoms, strength, movement confidence, walking and daily function for patients from Lafayette, Carencro, and across Acadiana.",
  overviewTitle: "Osteoarthritis does not reduce a knee to “bone on bone.”",
  overview: [
    "Osteoarthritis involves changes across the joint, including cartilage, bone and other tissues, but an image does not tell us how much a person can do or how much pain they will feel. People with similar X-rays can have very different symptoms, walking tolerance and goals.",
    "A useful plan therefore addresses the diagnosis and the person’s current capacity. Strength, load tolerance, sleep, prior injuries, health factors, activity patterns and confidence with movement may all influence function without being treated as a single cause.",
  ],
  examTitle: "A knee OA examination connects symptoms with real-world tasks.",
  exam: [
    { title: "Clarify the presentation", description: "We review symptom location, swelling, stiffness, flare pattern, prior injury, imaging when available, health history and signs that may suggest another diagnosis." },
    { title: "Measure useful capacity", description: "Knee motion and strength may be considered alongside walking, sit-to-stand, stairs, balance and other tasks that matter to the patient." },
    { title: "Assess the movement system", description: "Hip strength, foot and ankle motion, gait and load absorption may be assessed when relevant; no single finding is assumed to explain the arthritis." },
  ],
  dailyTitle: "Knee OA can affect more than pain at rest.",
  dailyDescription: "The practical problem may be reduced tolerance, an unpredictable flare, or uncertainty about how much activity is safe—not simply the presence of joint changes.",
  daily: [
    { title: "Walking tolerance", description: "Distance, pace, terrain and recovery after walking can help establish a useful baseline." },
    { title: "Stairs and transitions", description: "Step control, chair height and sit-to-stand strength may reveal modifiable capacity limits." },
    { title: "Load confidence", description: "Fear of aggravating the knee may lead to avoidance even when carefully graded movement is appropriate." },
    { title: "Flare behavior", description: "Duration, swelling and next-day response help guide activity dosage and recovery strategies." },
  ],
  related: [
    { title: "Broad Knee Pain Guide", href: "/knee-pain-lafayette" },
    { title: "Hip Pain", href: "/hip-pain-lafayette" },
    { title: "Tendonitis", href: "/tendonitis-treatment-lafayette" },
  ],
  approach: "Physical therapy and progressive exercise are central when appropriate. Chiropractic or manual care may address clinically relevant restrictions in the hip, ankle or other neighboring regions, but it does not reverse arthritis. Adjuncts and advanced options are considered only in context.",
  therapies: [
    pt("Progressive strength, mobility, balance and task-specific conditioning are matched to symptoms and goals."),
    chiropractic("Manual care may address relevant regional restrictions as one part of a broader active plan."),
    laser("A possible adjunct for selected presentations; it is not a stand-alone solution or a cartilage-regrowth treatment."),
    prp("May be discussed cautiously after diagnosis, evidence review, alternatives and candidacy; outcomes are not guaranteed."),
  ],
  sections: [
    { eyebrow: "Diagnosis and Function", title: "Imaging severity and symptom severity do not always move together.", paragraphs: ["X-rays can help identify joint-space and bone changes, but imaging is interpreted with history and examination. A severe-looking image does not automatically mean severe disability, and a milder image does not invalidate meaningful pain.", "The broad knee-pain page addresses many possible knee complaints. This guide is specifically for confirmed or suspected osteoarthritis and focuses on what the diagnosis means, how function is measured, and how capacity may be rebuilt."] },
    { eyebrow: "Regional Interdependence", title: "The hip, foot and ankle can influence how the knee manages force.", paragraphs: ["Walking, stair climbing and rising from a chair distribute demand across several joints. Hip strength, ankle motion, foot contact and trunk strategy may influence how force is transferred and absorbed at the knee.", "These observations are not proof that one neighboring region caused arthritis. They are factors we may evaluate because improving an available movement option can make a meaningful task more tolerable."], items: [{ title: "Walking", description: "Stride, pace, turning and terrain may be compared with symptoms and fatigue." }, { title: "Stairs", description: "Hip contribution, ankle motion and knee control may influence demand during ascent and descent." }, { title: "Sit-to-stand", description: "Chair height, speed, strength and use of the arms provide a repeatable functional measure." }, { title: "Single-leg demand", description: "Balance and control may matter for curbs, dressing and uneven ground." }] },
    { eyebrow: "Progressive Loading", title: "Complete inactivity can reduce the capacity needed for daily life.", paragraphs: ["During an irritable flare, temporary adjustments to volume, impact or range may be useful. Long periods of avoiding movement, however, can reduce strength and tolerance, making ordinary demands feel harder.", "Progressive loading starts at a manageable level and changes one variable at a time. The aim is not to force through escalating symptoms; it is to find a dose the knee can recover from and build from there."], items: [{ title: "Strength", description: "Knee and hip exercise can be progressed by resistance, range, repetitions and task complexity." }, { title: "Aerobic activity", description: "Walking, cycling or another tolerable option may support general health and activity capacity." }, { title: "Flare plan", description: "A temporary step down, recovery strategy and planned return can reduce all-or-nothing cycles." }, { title: "Confidence", description: "Repeated success with meaningful tasks may help restore trust in movement." }] },
    { eyebrow: "Treatment Selection", title: "Active care leads; adjuncts must have a defined role.", paragraphs: ["Education and exercise are prominent because they can address strength, function and self-management. Hands-on care may be useful for selected regional restrictions or short-term symptom modulation when it supports active progression.", "Laser may be considered as an adjunct without promises about inflammation or healing. PRP may be discussed for a diagnosed knee presentation only after reviewing the mixed and evolving evidence, risks, alternatives, cost and individual candidacy. Neither option is described as regrowing cartilage or guaranteeing avoidance of surgery."] },
    { eyebrow: "What You Can Do", title: "Use symptoms and recovery to adjust—not abandon—movement.", paragraphs: ["Track a few meaningful measures, such as walking minutes, stair response, sit-to-stand repetitions or next-day stiffness. A modest temporary increase in symptoms may be acceptable for some plans, while marked swelling or a prolonged flare may indicate that dosage needs adjustment.", "Choose sustainable activity, distribute demanding tasks when possible, and follow an individualized strengthening progression. Sleep, general health and recovery time also matter, but no single lifestyle factor should be blamed for the condition."] },
    { eyebrow: "Additional Evaluation", title: "Referral decisions depend on symptoms, function and the clinical picture.", paragraphs: ["Prompt medical evaluation is appropriate after major trauma, for a hot markedly swollen joint with fever or illness, inability to bear weight, suspected fracture or infection, or rapidly worsening symptoms. Locking, substantial instability or an uncertain diagnosis may also warrant additional assessment.", "Orthopedic consultation may be appropriate when pain and loss of function remain substantial despite a well-delivered nonsurgical plan, or when the patient wants to understand surgical options. Consultation is not failure; it is one step in shared decision-making."] },
  ],
  faqs: [
    { question: "Does “bone on bone” mean exercise will damage my knee?", answer: "No phrase on an X-ray can answer that by itself. Exercise selection and dosage should reflect symptoms, function, health history and recovery. Progressive strengthening is commonly part of evidence-informed knee OA care." },
    { question: "Should I rest during a flare?", answer: "Temporary load reduction may help, but complete inactivity is rarely the long-term goal. A flare plan can reduce demand briefly and then restore activity in steps." },
    { question: "Can treatment regrow knee cartilage?", answer: "Relief Plus does not promise cartilage regrowth. Care focuses on symptoms, strength, mobility, activity tolerance and informed discussion of appropriate options." },
    { question: "When should I discuss joint replacement?", answer: "An orthopedic discussion may be useful when pain and functional loss remain substantial after appropriate nonsurgical care or when you want to understand risks, benefits and alternatives." },
  ],
  sources: [
    { label: "AAOS: Management of Osteoarthritis of the Knee", href: "https://www.aaos.org/oak3cpg", note: "Clinical practice guideline addressing nonsurgical knee osteoarthritis care." },
    { label: "NICE: Osteoarthritis in over 16s", href: "https://www.nice.org.uk/guidance/ng226", note: "Guidance on diagnosis, information, exercise, weight management, treatment and referral." },
  ],
});

export const rotatorCuffPage = page({
  path: "/rotator-cuff-pain-lafayette", name: "Rotator Cuff Pain", eyebrow: "Rotator Cuff Care in Lafayette, Louisiana", h1: "Rotator cuff pain care built around diagnosis, load, and shoulder function.", title: "Rotator Cuff Pain Treatment in Lafayette, LA", description: "Rotator cuff pain treatment in Lafayette, LA with diagnosis-focused evaluation, progressive rehabilitation, and individualized care at Relief Plus.",
  hero: "Rotator cuff pain may reflect tendinopathy, a partial or full-thickness tear, another shoulder condition, or pain referred from elsewhere. Relief Plus connects the diagnosis to reaching, lifting, work, sport, and daily function.",
  overviewTitle: "Painful weakness does not identify the diagnosis by itself.",
  overview: ["The rotator cuff is a group of muscles and tendons that contributes to shoulder rotation, elevation and control. Tendinopathy and tears can overlap in symptoms, while imaging findings may also exist without explaining all of a person’s pain.", "Gradual symptoms with repeated overhead demand call for a different level of concern than sudden weakness after a fall or forceful injury. Age, onset, night symptoms, strength, motion and task tolerance help determine whether rehabilitation, imaging or orthopedic input should be considered."],
  examTitle: "The examination separates cuff findings from overlapping sources.",
  exam: [{ title: "History and differential", description: "We compare gradual or traumatic onset, pain behavior, night symptoms, medical history and signs of frozen shoulder, instability, arthritis, cervical referral or another condition." }, { title: "Shoulder capacity", description: "Active and passive motion, resisted testing, endurance and task-specific reaching or lifting may help characterize the presentation." }, { title: "Regional screen", description: "Scapular movement, thoracic motion, rib-cage strategy and the cervical spine may be assessed when relevant without assigning one universal cause." }],
  dailyTitle: "Rotator cuff symptoms often show up under specific demand.", dailyDescription: "The useful question is not only whether an arm hurts, but which direction, load, duration and speed exceed current tolerance.",
  daily: [{ title: "Overhead reach", description: "Shelf height, arm path, load and repetition can change symptoms." }, { title: "External rotation", description: "Reaching behind the head, throwing and stabilizing a load may expose painful weakness." }, { title: "Endurance", description: "Repeated work may be limited even when a single strength test looks acceptable." }, { title: "Sleep and dressing", description: "Side lying, fastening clothing and grooming can reveal different mobility and load needs." }],
  related: [{ title: "Broad Shoulder Pain Guide", href: "/shoulder-pain-lafayette" }, { title: "Frozen Shoulder", href: "/frozen-shoulder-lafayette" }, { title: "Neck Pain", href: "/neck-pain-lafayette" }, { title: "Tendonitis", href: "/tendonitis-treatment-lafayette" }],
  approach: "Physical therapy and progressive loading are prominent for appropriate rotator cuff presentations. Chiropractic may address relevant cervical, thoracic or shoulder joint findings. Modalities are selected only when their proposed role matches the diagnosis—never as substitutes for a complete examination and active plan.",
  therapies: [pt("Active rehabilitation may develop cuff and shoulder capacity through individualized motor-control and resistance exercise."), chiropractic("May address relevant cervical, thoracic or shoulder joint findings when examination supports it."), dry("May be considered for a separate muscular contributor; it does not repair a tendon tear."), shockwave("Reserved for selected persistent tendon presentations, particularly when the specific diagnosis supports its use."), laser("A possible adjunct in selected presentations; not a stand-alone repair strategy."), prp("Discussed only when diagnosis, evidence, alternatives and candidacy justify consideration.")],
  sections: [
    { eyebrow: "Tendinopathy or Tear", title: "The terms describe different tissue findings, but neither predicts function alone.", paragraphs: ["Tendinopathy describes a painful tendon presentation often associated with load sensitivity. A tear describes a structural defect that may be partial or full thickness and may develop gradually or follow trauma. Symptoms, strength and function can overlap.", "Imaging can be useful when the diagnosis is uncertain, symptoms follow significant trauma, meaningful weakness persists, or results would change management. It should be interpreted with the examination rather than used as a stand-alone verdict."] },
    { eyebrow: "Movement Context", title: "The shoulder works with the scapula, rib cage, thorax, and neck.", paragraphs: ["Reaching is a coordinated task. Scapular rotation, thoracic movement, rib-cage position and cuff force may influence the space and load available to the arm. Cervical screening matters because neck-related pain can mimic or accompany a shoulder condition.", "A movement difference may be a useful treatment target, a protective compensation, or simply normal variation. It must be interpreted with symptoms, strength and the task—not labeled the singular cause."], items: [{ title: "Reach path", description: "Arm angle and trunk contribution may change demand during work or sport." }, { title: "Scapular behavior", description: "Movement and endurance may be assessed without treating “dyskinesis” as a diagnosis by itself." }, { title: "Rib-cage strategy", description: "Breathing and trunk position may influence overhead options in selected patients." }, { title: "Neck screen", description: "Movement, neurological findings and symptom reproduction help identify cervical contribution." }] },
    { eyebrow: "Rehabilitation", title: "Progressive loading prepares the cuff for the demands it must meet.", paragraphs: ["An active program may begin with tolerable isometric, isotonic or motor-control exercise and progress toward the range, speed, repetition and load needed for daily life, work or sport. There is no single best exercise for every presentation.", "Pain response, strength, range, fatigue and next-day recovery guide dosage. Ergonomic or technique changes may temporarily reduce demand while capacity is rebuilt, but indefinite avoidance is not the objective."] },
    { eyebrow: "Adjunctive Care", title: "A modality must match the diagnosis and support active progression.", paragraphs: ["Manual care or chiropractic may address relevant cervical, thoracic or shoulder restrictions. Dry needling may be used for selected muscular pain. Neither is described as repairing a tear.", "Shockwave is not presented routinely for noncalcific rotator cuff tendinopathy; evidence-based discussion differs for calcific presentations. Laser and PRP also require diagnosis-specific evidence and candidacy review. No adjunct guarantees tendon healing or return to activity."] },
    { eyebrow: "What You Can Do", title: "Modify the dose while preserving useful shoulder activity.", paragraphs: ["Identify the combination of height, load and repetition that is currently provocative. Temporary changes—lighter loads, shorter sets, different hand position or more recovery—can create room for progressive exercise.", "Avoid repeatedly testing a painful maximum. Track functional markers such as sleep, reaching height, carrying tolerance and endurance so progress is not judged from pain intensity alone."] },
    { eyebrow: "Additional Evaluation", title: "Trauma, marked weakness, or progressive loss changes the pathway.", paragraphs: ["Prompt medical assessment is appropriate after a dislocation, major fall or forceful injury; for visible deformity; fever with a hot swollen joint; or new neurological or vascular symptoms. Sudden inability to lift the arm after trauma may warrant timely imaging or orthopedic evaluation.", "Imaging or specialist input may also be useful when substantial weakness or disability persists despite appropriate care, when the diagnosis remains uncertain, or when the result would influence a procedural or surgical decision."] },
  ],
  faqs: [{ question: "Does shoulder pain mean my rotator cuff is torn?", answer: "No. Tendinopathy, frozen shoulder, arthritis, cervical referral and other conditions can produce overlapping symptoms. History and examination guide whether imaging is useful." }, { question: "Do all rotator cuff tears need surgery?", answer: "No. Decisions depend on trauma, tear characteristics, weakness, function, health factors, goals and response to appropriate nonsurgical care." }, { question: "Should I stop overhead activity?", answer: "A temporary reduction may be appropriate when demand exceeds tolerance, but the longer-term plan often rebuilds overhead capacity progressively." }, { question: "Can shockwave or PRP repair a tear?", answer: "Relief Plus does not promise structural repair. These options require a specific diagnosis, evidence review, candidacy assessment and discussion of alternatives." }],
  sources: [{ label: "JOSPT: Rotator Cuff Tendinopathy Clinical Practice Guideline", href: "https://doi.org/10.2519/jospt.2025.13182", note: "2025 guidance on diagnosis, nonsurgical care, rehabilitation and return to function." }, { label: "AAOS: Management of Rotator Cuff Injuries", href: "https://www.aaos.org/quality/quality-programs/rotator-cuff/", note: "Evidence-based orthopedic guidance for rotator cuff injuries." }],
});

export const tmjPage = page({
  path: "/tmj-treatment-lafayette", name: "TMJ and Jaw Pain", eyebrow: "TMJ and Jaw Pain Care in Lafayette, Louisiana", h1: "TMJ and jaw pain care without assumptions about “alignment.”", title: "TMJ and Jaw Pain Treatment in Lafayette, LA", description: "TMJ and jaw pain treatment in Lafayette, LA with conservative evaluation, physical therapy, education, and coordinated care at Relief Plus.",
  hero: "Temporomandibular disorders can involve the jaw joints, chewing muscles, or both. Relief Plus evaluates jaw motion and load alongside the neck, breathing, headaches, and daily tasks such as eating and speaking.",
  overviewTitle: "TMJ names the joint; TMD describes a group of possible disorders.",
  overview: ["Jaw pain is not one diagnosis. Symptoms may arise mainly from the chewing muscles, the temporomandibular joint, disc-related mechanics, or overlapping pain conditions. Clicking without pain is common and does not automatically require treatment.", "A conservative evaluation considers pain location, opening and closing, locking, chewing tolerance, clenching or other load, trauma, headache overlap and dental factors. Treatment does not aim to realign the jaw or permanently change the bite."],
  examTitle: "A jaw examination distinguishes joint, muscle, and referred patterns.",
  exam: [{ title: "Listen to the history", description: "We review onset, trauma, locking, joint noise, headaches, clenching, chewing demands, dental care and symptoms that may require collaboration." }, { title: "Observe function", description: "Comfortable opening, closing path, side-to-side motion, tenderness and chewing tolerance may be assessed without forcing irritable movement." }, { title: "Screen connected regions", description: "Cervical and upper thoracic movement, rib-cage strategy, breathing and relevant neurological findings may be considered when they affect the presentation." }],
  dailyTitle: "Jaw symptoms may change with load, habit, and recovery.", dailyDescription: "Eating, yawning, prolonged speaking, sleep and periods of clenching may expose different joint and muscular demands.",
  daily: [{ title: "Chewing tolerance", description: "Food texture, duration and side preference may alter symptoms." }, { title: "Opening and closing", description: "Range, deviation, pain and locking help characterize the mechanical pattern." }, { title: "Clenching load", description: "Daytime bracing or sleep-related grinding may increase muscular demand but is not assumed to be the only cause." }, { title: "Headache overlap", description: "Jaw, neck and headache symptoms may coexist and require a broader differential." }],
  related: [{ title: "Neck Pain", href: "/neck-pain-lafayette" }, { title: "Headaches", href: "/headache-treatment-lafayette" }, { title: "Why Your Jaw Hurts", href: "/blog/why-your-jaw-hurts-tmj-pain-guide-for-lafayette-la" }, { title: "Conservative TMD Care", href: "/blog/treating-temporomandibular-joint-dysfunction-with-conservative-care" }],
  approach: "Education, habit modification, physical therapy and graded jaw exercise may lead a conservative plan. Chiropractic is limited to relevant cervical or neighboring joint findings and is not described as realigning the jaw. Dental, medical or oral-maxillofacial collaboration is recommended when the presentation calls for it.",
  therapies: [pt("May use graded jaw and cervical movement, coordination, endurance and practical self-management."), chiropractic("May address relevant cervical or upper-thoracic findings; it does not reposition the jaw or bite."), dry("May be considered for selected chewing or neck-muscle contributors after appropriate screening.")],
  sections: [
    { eyebrow: "Joint or Muscle", title: "Location alone cannot separate TMJ pain from muscular jaw pain.", paragraphs: ["Joint-dominant symptoms may include localized preauricular pain, painful joint noise, catching or locking. Muscle-dominant symptoms may feel broader across the cheek, temple or jaw and may increase with sustained clenching or chewing. Mixed presentations are common.", "Pain in the mouth, face or jaw can also come from dental disease, infection, neuralgia, headache disorders and other medical conditions. The clinical history determines when a dentist or physician should lead the evaluation."] },
    { eyebrow: "Regional Interdependence", title: "Jaw motion occurs within a head, neck, rib-cage, and breathing system.", paragraphs: ["Cervical position and muscle activity can influence how a person opens, speaks and chews. Upper-thoracic and rib-cage movement may affect available head and neck strategies. Breathing pattern and resting jaw position can matter when muscular bracing is present.", "These relationships do not prove that neck posture caused TMD. They are possible contributors assessed only when clinically relevant and interpreted with jaw-specific findings."], items: [{ title: "Resting position", description: "Awareness of unnecessary tooth contact may help some patients reduce sustained load." }, { title: "Breathing", description: "Breath holding or bracing may accompany difficult tasks and can be explored without assigning blame." }, { title: "Neck movement", description: "Symptom change with cervical motion may indicate a relevant overlapping source." }, { title: "Headache pattern", description: "Timing, triggers and associated symptoms help decide whether additional medical evaluation is needed." }] },
    { eyebrow: "Conservative Care", title: "Start with reversible strategies matched to the presentation.", paragraphs: ["Education may include temporary food-texture changes, reducing gum chewing or repeated wide opening, awareness of daytime clenching, and a planned return toward normal use. Exercises may address comfortable motion, coordination and endurance rather than forcing the joint.", "Physical therapy may include jaw and cervical exercise and manual care. Dry needling may be considered for selected muscular contributors. Chiropractic care, when relevant, focuses on the cervical or upper-thoracic region—not jaw realignment."] },
    { eyebrow: "Collaboration", title: "Some jaw presentations are best managed with dental or medical partners.", paragraphs: ["Dental evaluation may be important when tooth pain, infection, bite trauma or oral disease is possible. A dentist or orofacial pain clinician may also assess whether a reversible oral appliance is appropriate; permanent changes to teeth or bite should not be presented as routine conservative care.", "Persistent locking, significant trauma, progressive restriction or a suspected structural joint disorder may call for oral-maxillofacial or medical evaluation. Collaboration keeps treatment aligned with the actual diagnosis."] },
    { eyebrow: "What You Can Do", title: "Reduce unnecessary load without becoming afraid of normal jaw use.", paragraphs: ["During an irritable period, smaller bites, temporarily softer foods and avoiding repeated end-range opening may help. Notice daytime tooth contact and let the jaw rest comfortably when possible.", "Do not force through locking or sharply escalating pain. Track opening, chewing duration, headache overlap and symptom recovery, then progress normal use as tolerance allows under appropriate guidance."] },
    { eyebrow: "Additional Evaluation", title: "Locking, trauma, progressive limitation, or systemic signs deserve attention.", paragraphs: ["Seek prompt dental or medical evaluation for facial swelling with fever, suspected infection, significant jaw trauma, inability to close the mouth, new neurological symptoms, or difficulty swallowing or breathing. Sudden severe headache or other acute neurological signs also require urgent assessment.", "Persistent closed or open locking, steadily decreasing opening, unexplained weight loss, a new mass or symptoms that do not fit a musculoskeletal pattern warrant appropriate medical, dental or oral-maxillofacial review."] },
  ],
  faqs: [{ question: "Is jaw clicking always a problem?", answer: "No. Painless clicking is common and may not need treatment. Painful noise, locking or progressive loss of movement deserves evaluation." }, { question: "Can chiropractic realign my jaw?", answer: "That is not how Relief Plus describes care. Chiropractic may address relevant cervical or upper-thoracic findings; jaw treatment remains diagnosis-specific and conservative." }, { question: "Should I stop chewing on the painful side?", answer: "Temporary modification may help an irritable presentation, but prolonged one-sided avoidance is not automatically the goal. Progression depends on the diagnosis and response." }, { question: "When should I see a dentist or oral surgeon?", answer: "Dental symptoms, trauma, infection concern, persistent locking, progressive limitation or suspected structural disease may require dental or oral-maxillofacial evaluation." }],
  sources: [{ label: "NIDCR: Temporomandibular Disorders", href: "https://www.nidcr.nih.gov/health-info/tmd", note: "NIH patient guidance on TMD categories, diagnosis, conservative care and cautions around irreversible treatment." }, { label: "National Academies: Temporomandibular Disorders", href: "https://doi.org/10.17226/25652", note: "Consensus report on TMD research, diagnosis and care priorities." }],
});

export const frozenShoulderPage = page({
  path: "/frozen-shoulder-lafayette", name: "Frozen Shoulder", eyebrow: "Frozen Shoulder Care in Lafayette, Louisiana", h1: "Frozen shoulder care paced to motion, irritability, and daily function.", title: "Frozen Shoulder Treatment in Lafayette, LA", description: "Frozen shoulder treatment in Lafayette, LA with individualized physical therapy, progressive mobility, and conservative care at Relief Plus.",
  hero: "Frozen shoulder, or adhesive capsulitis, typically involves meaningful loss of both active and passive shoulder motion. Relief Plus evaluates irritability, motion, compensation, health context, and the daily activities most affected.",
  overviewTitle: "Frozen shoulder is distinct from ordinary shoulder stiffness or rotator cuff pain.",
  overview: ["Adhesive capsulitis is characterized by pain and restricted movement at the shoulder joint. The limitation is present when the person moves the arm and when an examiner gently assesses passive motion, although the exact pattern and irritability can vary.", "Recovery time is variable. A thoughtful plan respects symptom sensitivity while preserving useful activity and progressively restoring motion and strength. Care does not rely on a claim that adhesions can simply be “broken up.”"],
  examTitle: "The examination confirms a capsular pattern and screens alternatives.",
  exam: [{ title: "Compare active and passive motion", description: "Range and symptom behavior are assessed in multiple directions, with attention to external rotation and function rather than forcing end range." }, { title: "Screen other diagnoses", description: "Rotator cuff injury, arthritis, cervical referral, fracture and other shoulder disorders may require a different pathway." }, { title: "Understand context", description: "Onset, stage, sleep, prior injury, diabetes or other relevant health factors, goals and response to movement guide decisions." }],
  dailyTitle: "Loss of motion changes ordinary self-care and sleep.", dailyDescription: "The functional pattern often matters more to the patient than a degree measurement alone.",
  daily: [{ title: "Dressing", description: "Reaching into a sleeve or behind the back may become restricted." }, { title: "Grooming", description: "Hair care and reaching the head may expose combined elevation and rotation limits." }, { title: "Sleep", description: "Side lying and nighttime pain can affect recovery and daytime capacity." }, { title: "Overhead use", description: "Shelves, work and recreation may require temporary modification and gradual restoration." }],
  related: [{ title: "Broad Shoulder Pain Guide", href: "/shoulder-pain-lafayette" }, { title: "Rotator Cuff Pain", href: "/rotator-cuff-pain-lafayette" }, { title: "Frozen Shoulder Exercise Article", href: "/blog/frozen-shoulder-effective-exercises-for-regaining-your-range-of-motion" }, { title: "Neck Pain", href: "/neck-pain-lafayette" }],
  approach: "Physical therapy, education and progressive mobility are central. Chiropractic or manual care may address relevant surrounding cervical, thoracic, rib or shoulder regions but is not presented as forcefully breaking adhesions. Adjuncts are secondary to diagnosis and an appropriate active plan.",
  therapies: [pt("Progresses tolerable shoulder mobility, strength and function according to irritability and stage."), chiropractic("May address relevant surrounding joint restrictions without claiming to break capsular adhesions."), dry("May be considered for secondary muscular guarding; it does not treat the capsule itself."), laser("A possible adjunct in selected cases, without a promise of shortened recovery or tissue healing.")],
  sections: [
    { eyebrow: "What the Diagnosis Means", title: "Active and passive motion loss separates adhesive capsulitis from many look-alikes.", paragraphs: ["A painful shoulder can be hard to lift because of pain or weakness while passive motion remains relatively available. Frozen shoulder more often restricts both, reflecting reduced joint-capsule mobility. External rotation is commonly limited, but diagnosis should not rely on one motion alone.", "The condition may be primary or may follow immobilization, surgery or injury. Diabetes and thyroid disease are recognized associations, but an association does not explain every case or determine an individual outcome."] },
    { eyebrow: "Compensation", title: "The shoulder blade and trunk may create motion when the joint cannot.", paragraphs: ["A person may elevate the shoulder blade, lean the trunk or rotate the rib cage to reach. These strategies can be helpful adaptations, yet they may also increase demand on surrounding tissues during repeated tasks.", "Thoracic, scapular and cervical findings are interpreted as part of function—not blamed as the cause of the frozen shoulder. Treatment may improve surrounding options while the glenohumeral joint is progressed carefully."], items: [{ title: "Scapular motion", description: "Early or increased shoulder-blade movement may compensate for limited joint motion." }, { title: "Thoracic contribution", description: "Trunk extension or rotation may help reach and can be assessed during meaningful tasks." }, { title: "Protective guarding", description: "Muscular tension may reflect irritability rather than a primary problem." }, { title: "Task strategy", description: "Dressing and grooming can be adapted temporarily while capacity develops." }] },
    { eyebrow: "Progressive Mobility", title: "More force is not always more effective.", paragraphs: ["Highly irritable shoulders may respond poorly to aggressive end-range work. Early exercise may emphasize comfortable motion and maintaining function, while later stages can tolerate longer or stronger mobility and strengthening doses.", "Progress is assessed through motion, sleep, daily tasks and symptom recovery. The pace can vary substantially, so a fixed timeline or guaranteed result would be misleading."] },
    { eyebrow: "Treatment Selection", title: "Surrounding care supports the plan without pretending to change the capsule instantly.", paragraphs: ["Physical therapy may use education, graded mobility, exercise and manual techniques selected for irritability. Chiropractic or manual care may target relevant thoracic, cervical, rib or scapular-region findings when those restrictions affect function.", "Dry needling may address secondary muscular pain and laser may be considered as an adjunct. Neither is presented as breaking adhesions, restoring full motion immediately or replacing progressive rehabilitation."] },
    { eyebrow: "What You Can Do", title: "Keep useful motion within a dose the shoulder can recover from.", paragraphs: ["Short, tolerable movement sessions may be preferable to repeatedly forcing a painful limit. Use task modifications for dressing, grooming and reaching, and avoid prolonged immobilization unless directed after a procedure or injury.", "Track night symptoms, functional reach and recovery after exercise. If each session produces a marked prolonged flare, the range, intensity or volume may need adjustment."] },
    { eyebrow: "Additional Evaluation", title: "Trauma, systemic signs, or an atypical pattern may change the plan.", paragraphs: ["Prompt evaluation is appropriate after significant trauma, for deformity, a hot swollen joint with fever, or new neurological or vascular symptoms. Sudden severe weakness or inability to use the arm after injury may call for imaging.", "Imaging or orthopedic evaluation may also be considered when the diagnosis is uncertain, motion loss progresses unexpectedly, symptoms remain substantially disabling, or results would change management. Medical review can be useful when relevant metabolic associations have not been addressed."] },
  ],
  faqs: [{ question: "Is frozen shoulder the same as a rotator cuff tear?", answer: "No. Both can cause pain and difficulty lifting, but frozen shoulder usually restricts passive as well as active motion. Examination helps distinguish them." }, { question: "Can adhesions be broken up with manipulation?", answer: "Relief Plus does not use that claim. Mobility and manual care are dosed according to irritability, diagnosis and function; forceful treatment is not automatically appropriate." }, { question: "How long does frozen shoulder take to improve?", answer: "The course varies considerably. Progress depends on stage, irritability, health factors, function and response to care, so a guaranteed timeline is not appropriate." }, { question: "Should I stretch as hard as possible?", answer: "Not necessarily. Aggressive stretching can aggravate a highly irritable shoulder. Dosage should match symptom response and stage." }],
  sources: [{ label: "AAOS OrthoInfo: Frozen Shoulder", href: "https://orthoinfo.aaos.org/en/diseases--conditions/frozen-shoulder/", note: "Patient guidance on adhesive capsulitis, examination, natural history and treatment." }, { label: "APTA Orthopedics: Adhesive Capsulitis CPG", href: "https://www.orthopt.org/content/s/shoulder-pain-and-mobility-deficits-adhesive-capsulitis-2013", note: "Clinical practice guidance on diagnosis, irritability and rehabilitation." }],
});

export const hipBursitisPage = page({
  path: "/hip-bursitis-lafayette", name: "Hip Bursitis / Greater Trochanteric Pain Syndrome", eyebrow: "Lateral Hip Pain Care in Lafayette, Louisiana", h1: "Hip Bursitis / Greater Trochanteric Pain Syndrome care built around load tolerance.", title: "Hip Bursitis & GTPS Treatment in Lafayette, LA", description: "Hip bursitis and greater trochanteric pain syndrome treatment in Lafayette, LA with progressive rehabilitation and individualized care at Relief Plus.",
  hero: "Pain at the outside of the hip is not always an isolated inflamed bursa. Greater trochanteric pain syndrome can involve gluteal tendons and compression sensitivity, requiring a broader look at walking, stairs, sleep, and single-leg loading.",
  overviewTitle: "“Hip bursitis” is familiar language, but GTPS often describes the clinical picture more accurately.",
  overview: ["The greater trochanter is the bony area at the outside of the upper thigh. Nearby bursae and the gluteus medius and minimus tendons can contribute to lateral hip pain. Research increasingly recognizes gluteal tendinopathy as an important part of many GTPS presentations.", "Diagnosis still requires care. Lumbar referral, hip-joint conditions, fracture, nerve symptoms and other problems can mimic lateral hip pain. Tenderness over the side of the hip is informative but not sufficient by itself."],
  examTitle: "The examination tests lateral-hip load and screens common mimics.",
  exam: [{ title: "Locate and characterize pain", description: "We review tenderness, side-lying symptoms, walking and stair response, onset, trauma, health history and irritability." }, { title: "Assess tendon demand", description: "Selected resisted hip tests, single-leg loading and gait may help determine whether the gluteal tendon region is involved." }, { title: "Screen hip and lumbar sources", description: "Hip-joint motion, lumbar movement, neurological findings and other tests may be used when clinically relevant." }],
  dailyTitle: "Compression and single-leg demand often reveal the pattern.", dailyDescription: "A diagnosis should explain why ordinary positions and tasks are provocative—not just where the area is tender.",
  daily: [{ title: "Side lying", description: "Direct compression or the top leg crossing inward may increase lateral-hip symptoms." }, { title: "Walking", description: "Distance, hills, speed and recent changes in volume can affect tendon demand." }, { title: "Stairs", description: "Repeated single-leg force may expose hip-abductor capacity and control." }, { title: "Standing on one leg", description: "Dressing, curbs and prolonged hip-hanging postures may reproduce symptoms." }],
  related: [{ title: "Broad Hip Pain Guide", href: "/hip-pain-lafayette" }, { title: "Back Pain", href: "/back-pain-lafayette" }, { title: "Sciatica", href: "/sciatica-treatment-lafayette" }, { title: "Tendonitis", href: "/tendonitis-treatment-lafayette" }],
  approach: "Physical therapy emphasizes education and progressive gluteal and lower-limb loading. Chiropractic may address relevant lumbar or hip restrictions. Dry needling, shockwave or laser may be considered for selected contributors or persistent presentations, but no modality replaces diagnosis-specific load management.",
  therapies: [pt("Builds gluteal and lower-limb capacity while modifying compression and task demand."), chiropractic("May address relevant lumbar, pelvic-region or hip restrictions without claiming the pelvis is out."), dry("May address selected secondary muscular contributors rather than the tendon diagnosis itself."), shockwave("May be considered for selected persistent gluteal tendinopathy after diagnosis and candidacy review."), laser("A possible adjunct without promises of tendon healing or guaranteed pain relief.")],
  sections: [
    { eyebrow: "Beyond the Bursa", title: "Lateral hip pain commonly involves more than inflammation of a bursa.", paragraphs: ["GTPS is an umbrella term for pain around the greater trochanter. Gluteal tendinopathy, with or without bursal involvement, is common. Calling every presentation “bursitis” can obscure the role of tendon load and compression.", "The diagnosis is based on the history and a cluster of findings. Imaging is not automatically required, but it may help when trauma, substantial weakness, an uncertain diagnosis or poor response raises concern for another condition or a significant tendon tear."] },
    { eyebrow: "Regional Interdependence", title: "Walking transfers load through the trunk, hip, knee, ankle, and foot.", paragraphs: ["During single-leg stance, the lateral hip helps control the relationship between the pelvis and femur. Trunk strategy, hip motion, foot contact and walking speed may influence demand on the gluteal tendons.", "A visible pelvic shift is not proof that the pelvis is “out” or that one muscle caused the pain. It may be a compensation for pain, a capacity issue, or normal variation and must be interpreted with the full examination."], items: [{ title: "Gait", description: "Stride width, cadence, trunk shift and hills may alter lateral-hip demand." }, { title: "Hip control", description: "Single-leg tasks can show how force is managed without assigning one faulty pattern." }, { title: "Lumbar screen", description: "Back movement and neurological findings help identify referred or overlapping pain." }, { title: "Foot and ankle", description: "Ground contact may influence force transfer but is not presumed causal." }] },
    { eyebrow: "Progressive Loading", title: "Reduce excessive compression while rebuilding tendon capacity.", paragraphs: ["Early education may reduce sustained positions that compress the lateral hip, such as sleeping directly on the painful side or standing with the hip pushed outward. This is temporary load management, not a demand for perfect posture.", "Strengthening progresses from tolerable hip-abductor work toward walking, stairs, single-leg control and the patient’s activity goals. Exercise dosage reflects symptoms and recovery rather than a universal protocol."] },
    { eyebrow: "Treatment Selection", title: "Adjuncts are considered only when they support a clear active plan.", paragraphs: ["Chiropractic or manual care may address a relevant lumbar or hip restriction. Dry needling may target selected muscular pain. These approaches do not replace progressive loading for a tendon-dominant presentation.", "Shockwave may be discussed in selected persistent gluteal tendinopathy. Laser is a possible adjunct. Both require realistic discussion of evidence, timing and alternatives, with no guarantee of tissue healing or symptom resolution."] },
    { eyebrow: "What You Can Do", title: "Modify compression and walking volume without abandoning activity.", paragraphs: ["A pillow between the knees, avoiding prolonged hip-hanging and temporarily adjusting hills or walking distance may reduce irritation. The goal is to find a workable level, not to avoid loading forever.", "Track side-lying tolerance, walking time, stair response and next-day symptoms. Progress strength and task exposure gradually as recovery becomes more predictable."] },
    { eyebrow: "Additional Evaluation", title: "Trauma, inability to bear weight, or systemic findings require a broader view.", paragraphs: ["Prompt medical assessment is appropriate after major trauma, with inability to bear weight, a hot swollen joint, fever, rapidly worsening pain, or new neurological symptoms. Groin pain with marked motion loss may suggest a hip-joint source rather than isolated GTPS.", "Imaging or orthopedic evaluation may be useful for suspected substantial gluteal tendon tear, persistent meaningful weakness, uncertain diagnosis or failure to progress when results would change management."] },
  ],
  faqs: [{ question: "Is hip bursitis always an inflamed bursa?", answer: "No. Greater trochanteric pain syndrome often includes gluteal tendon involvement, and other hip or lumbar conditions can mimic it." }, { question: "Should I stop walking?", answer: "Usually the first step is to adjust a provocative dose rather than stop all activity. Distance, hills, speed and recovery can be progressed as tolerance improves." }, { question: "Why does lying on my side hurt?", answer: "Direct compression of sensitive tissues at the outer hip can be provocative. Sleep-position modifications may help while capacity is rebuilt." }, { question: "Can shockwave cure GTPS?", answer: "No treatment is guaranteed. Shockwave may be considered for selected persistent tendon presentations alongside diagnosis-specific education and loading." }],
  sources: [{ label: "BMJ: Education plus exercise for gluteal tendinopathy", href: "https://www.bmj.com/content/361/bmj.k1662", note: "Randomized trial of load-management education and specific exercise." }, { label: "JOSPT: Diagnostic Accuracy for GTPS", href: "https://pubmed.ncbi.nlm.nih.gov/37561820/", note: "Systematic review and meta-analysis of clinical tests for greater trochanteric pain syndrome." }],
});

export const tennisElbowPage = page({
  path: "/tennis-elbow-lafayette", name: "Tennis Elbow", eyebrow: "Tennis Elbow Care in Lafayette, Louisiana", h1: "Tennis elbow care for grip, work, sport, and tendon capacity.", title: "Tennis Elbow Treatment in Lafayette, LA", description: "Tennis elbow treatment in Lafayette, LA with progressive tendon loading, physical therapy, and selected adjuncts at Relief Plus.",
  hero: "Tennis elbow, or lateral elbow tendinopathy, often reflects sensitivity to gripping and wrist-extensor load—not necessarily playing tennis. Relief Plus evaluates the elbow within the demands of work, sport, and the full upper limb.",
  overviewTitle: "A tendon can become load-sensitive without being torn or permanently damaged.",
  overview: ["Lateral elbow tendinopathy commonly produces pain near the outer elbow with gripping, lifting or resisted wrist extension. Symptoms may follow a change in work, tools, training or repeated hand use, but no single exposure explains every case.", "Pain at the outer elbow can also come from a joint, nerve, neck or another tendon. Diagnosis matters before selecting exercise or a modality, especially when symptoms are atypical, include numbness or follow significant trauma."],
  examTitle: "The examination links elbow findings to the grip demands that matter.",
  exam: [{ title: "Reproduce the pattern", description: "Palpation, resisted wrist or finger testing, grip and functional tasks may help identify a lateral tendon presentation." }, { title: "Measure load tolerance", description: "Grip force, repetition, tool position and recovery help establish a baseline for progressive loading." }, { title: "Screen the region", description: "Elbow joint motion, shoulder and scapular capacity, and cervical or nerve findings may be assessed when symptoms warrant it." }],
  dailyTitle: "Grip demand is more specific than the label “overuse.”", dailyDescription: "Load depends on force, wrist position, repetition, speed, tool size, rest and the capacity of the whole arm.",
  daily: [{ title: "Work tools", description: "Grip diameter, vibration, wrist position and repetition may influence demand." }, { title: "Lifting", description: "Palm position, lever length and object weight can change lateral-elbow load." }, { title: "Racquet or throwing sport", description: "Technique, equipment and sudden volume changes may matter when relevant." }, { title: "Everyday grip", description: "Opening containers, carrying bags and computer use may expose different tolerances." }],
  related: [{ title: "Tendonitis", href: "/tendonitis-treatment-lafayette" }, { title: "Neck Pain", href: "/neck-pain-lafayette" }, { title: "PRP and Tennis Elbow Article", href: "/blog/discover-the-power-of-prp-therapy-for-tennis-elbow-at-relief-plus" }, { title: "Dry Needling Article", href: "/blog/dry-needling-a-game-changer-in-treating-tennis-elbow-at-relief-plus-with-dr-shawn-johnston-1" }],
  approach: "Physical therapy and progressive tendon loading are central. Dry needling, shockwave or laser may be considered for selected presentations. Chiropractic is limited to relevant cervical, shoulder, elbow or wrist findings rather than presented as routine elbow treatment.",
  therapies: [pt("Progresses wrist-extensor, grip and upper-limb capacity toward work or sport demands."), dry("May address selected muscular contributors as an adjunct to active rehabilitation."), shockwave("May be considered for selected persistent lateral elbow tendinopathy after appropriate evaluation."), laser("A possible adjunct without a healing guarantee."), chiropractic("Used only when clinically relevant regional joint findings influence the presentation.")],
  sections: [
    { eyebrow: "What the Diagnosis Means", title: "Tennis elbow is a load-related tendon presentation, not a sport requirement.", paragraphs: ["The common wrist-extensor tendons attach near the lateral epicondyle. Pain can develop when current demand exceeds tolerance, often after a change in repetition, gripping force or recovery. Tendinopathy does not automatically mean a tear or irreversible degeneration.", "The broad tendonitis page discusses tendon problems across the body. This page stays focused on the lateral elbow differential and rebuilding the specific grip and wrist-extensor demands involved."] },
    { eyebrow: "Regional Interdependence", title: "Grip begins at the hand but depends on the elbow, shoulder, and neck.", paragraphs: ["The shoulder and scapula position the arm so the wrist and hand can generate force. Limited endurance higher in the chain may increase demand at the forearm during repeated work, but this is one factor to evaluate—not proof of causation.", "Cervical and nerve screening becomes more important when pain is poorly localized, travels, includes tingling, or does not behave like a local tendon problem."], items: [{ title: "Shoulder endurance", description: "Proximal fatigue may influence repeated tool use or racquet control." }, { title: "Wrist position", description: "Grip force and tendon demand change as the wrist angle changes." }, { title: "Task exposure", description: "Repetition, force, vibration and recovery shape the actual dose." }, { title: "Cervical screen", description: "Neck and neurological findings help evaluate atypical or radiating symptoms." }] },
    { eyebrow: "Progressive Loading", title: "Complete rest may calm symptoms but can leave the tendon unprepared.", paragraphs: ["Short-term task modification may reduce an irritable load. If all gripping is avoided indefinitely, capacity may fall and symptoms can return when normal demands resume.", "Rehabilitation may progress isometric or isotonic wrist-extensor work, grip, forearm rotation and task-specific exposure. Dosage is adjusted to symptom response and recovery rather than based on a rigid pain-free rule."] },
    { eyebrow: "Treatment Selection", title: "Modalities complement—but do not replace—load progression.", paragraphs: ["Dry needling may address selected muscular contributors. Shockwave may be considered in persistent cases, and laser may be used as an adjunct. Expected benefit, uncertainty, burden and alternatives should be discussed.", "Chiropractic or manual care is considered only for clinically relevant cervical, shoulder, elbow or wrist restrictions. No hands-on treatment is described as correcting a universal imbalance or permanently fixing tendon capacity."] },
    { eyebrow: "What You Can Do", title: "Change force, position, or repetition while building tolerance.", paragraphs: ["Temporarily use two hands, reduce load, vary wrist position, adjust tool diameter or break a long task into shorter bouts. These changes reduce a specific dose; they do not mean the arm is fragile.", "Track grip tasks and next-day response. Build strength consistently, then progress toward faster, heavier or longer-duration tasks required by work or recreation."] },
    { eyebrow: "Additional Evaluation", title: "Trauma, neurological symptoms, or failure to progress may require more assessment.", paragraphs: ["Prompt evaluation is appropriate after major trauma, visible deformity, marked swelling, inability to use the arm, a hot joint with fever, or new weakness or numbness. A sudden pop with bruising or substantial strength loss may indicate a different injury.", "Imaging or specialist review may be considered when the diagnosis remains unclear, mechanical locking is present, symptoms are atypical, or meaningful disability persists despite appropriate care."] },
  ],
  faqs: [{ question: "Do I have to play tennis to get tennis elbow?", answer: "No. Work, tools, lifting, computer tasks and other repeated grip demands can be relevant." }, { question: "Should I stop using my arm completely?", answer: "Complete rest may reduce current symptoms but also reduce capacity. A better plan often modifies provocative demand while progressively rebuilding tolerance." }, { question: "Will dry needling or shockwave cure the tendon?", answer: "No modality guarantees a cure. Adjuncts may be considered for selected presentations while progressive loading remains central." }, { question: "Why examine my neck and shoulder?", answer: "They help position and load the arm, and cervical or nerve symptoms can mimic elbow pain. Their findings must be interpreted with the local examination." }],
  sources: [{ label: "APTA Orthopedics: Lateral Elbow Pain CPG", href: "https://www.orthopt.org/content/s/lateral-elbow-pain-and-muscle-function-impairments-2022", note: "2022 clinical practice guideline on diagnosis, outcomes and rehabilitation." }, { label: "JOSPT: Lateral Elbow Pain and Muscle Function Impairments", href: "https://doi.org/10.2519/jospt.2022.0302", note: "Peer-reviewed guideline supporting diagnosis-specific, progressive care." }],
});

export const achillesPage = page({
  path: "/achilles-tendinopathy-lafayette", name: "Achilles Tendinopathy", eyebrow: "Achilles Tendinopathy Care in Lafayette, Louisiana", h1: "Achilles tendinopathy care matched to tendon location and load.", title: "Achilles Tendinopathy Treatment in Lafayette, LA", description: "Achilles tendinopathy treatment in Lafayette, LA with progressive loading, gait and activity evaluation, and individualized care at Relief Plus.",
  hero: "Achilles symptoms near the heel may follow an insertional or midportion pattern, and those distinctions affect exercise and stretching choices. Relief Plus evaluates calf capacity, ankle and foot function, gait, and recent changes in activity load.",
  overviewTitle: "Insertional and midportion Achilles pain are not interchangeable.",
  overview: ["Midportion tendinopathy typically involves symptoms several centimeters above the heel. Insertional symptoms occur where the tendon meets the heel bone and can be more sensitive to compression in deep ankle dorsiflexion. Other conditions, including bursitis, partial tear and referred pain, can overlap.", "Tendon pain often reflects a mismatch between current load and capacity. A rapid increase in running, jumping, hills, speed or work demand may contribute, but age, health, recovery and prior symptoms also matter. The goal is not to identify one training “mistake” to blame."],
  examTitle: "The examination identifies location, capacity, and rupture concern.",
  exam: [{ title: "Differentiate the region", description: "Pain location, palpation, swelling, onset and selected tendon tests help distinguish midportion, insertional and alternative presentations." }, { title: "Measure calf function", description: "Heel-raise height, repetitions, strength, balance and hopping or running tolerance may be assessed when safe." }, { title: "Assess task demand", description: "Ankle motion, foot function, gait, footwear and recent training or work changes are interpreted with symptoms and goals." }],
  dailyTitle: "Tendon demand changes with speed, incline, and ankle position.", dailyDescription: "A person may tolerate level walking yet struggle with stairs, hills, acceleration or repeated jumping.",
  daily: [{ title: "Walking and stairs", description: "Volume, incline and push-off demand help establish current capacity." }, { title: "Running load", description: "Recent changes in distance, speed, hills or frequency may exceed recovery." }, { title: "Calf endurance", description: "Repeated heel raises provide a functional measure beyond pain alone." }, { title: "Ankle position", description: "Deep dorsiflexion may compress an insertional tendon and change exercise selection." }],
  related: [{ title: "Tendonitis", href: "/tendonitis-treatment-lafayette" }, { title: "Knee Pain", href: "/knee-pain-lafayette" }, { title: "Hip Pain", href: "/hip-pain-lafayette" }],
  approach: "Physical therapy and progressive tendon loading are central. Shockwave may be considered for selected persistent presentations and laser only as an adjunct. Chiropractic is limited to relevant ankle, foot or kinetic-chain findings and does not replace tendon loading.",
  therapies: [pt("Builds calf and tendon capacity toward walking, work, running or sport demands."), shockwave("May be considered for selected persistent Achilles presentations after diagnosis and candidacy review."), laser("A possible adjunct without promises of tendon regeneration or predictable relief."), chiropractic("May address relevant ankle, foot or regional joint findings when they affect function.")],
  sections: [
    { eyebrow: "Location Matters", title: "Compression differs between insertional and midportion patterns.", paragraphs: ["The insertional tendon can be compressed against the heel during deep dorsiflexion, so heel-drop stretching below a step is not automatically appropriate. Midportion presentations may tolerate and require different ranges as loading progresses.", "Imaging is not always required. It may be useful when diagnosis is uncertain, recovery changes unexpectedly, a partial tear or other condition is suspected, or a procedure is being considered. Tissue appearance must still be interpreted with function and symptoms."] },
    { eyebrow: "Regional Interdependence", title: "The Achilles transfers force from the calf through the ankle and foot.", paragraphs: ["Calf strength, ankle motion, foot contact, stride and the contribution of the knee and hip may influence how load is distributed during gait. Running speed, incline and surface can change tendon demand substantially.", "No single foot type or movement pattern proves the cause. Findings are useful only if they relate to symptom behavior, performance and a modifiable task."], items: [{ title: "Calf strength", description: "Capacity may differ in straight-knee and bent-knee tasks." }, { title: "Ankle mobility", description: "Available motion and symptom response guide exercise range, especially at the insertion." }, { title: "Gait and running", description: "Cadence, speed, incline and recent volume help define actual load." }, { title: "Kinetic chain", description: "Hip and knee contribution may influence force transfer but is not assumed causal." }] },
    { eyebrow: "Progressive Loading", title: "Tendons need a graded reason to become more capable.", paragraphs: ["Loading can include isometric, concentric, eccentric, heavy slow resistance and later faster or plyometric work. The appropriate starting point depends on irritability, strength, function and whether the presentation is insertional or midportion.", "Stretching is not universally required and may aggravate insertional compression. Progress is guided by pain response, heel-raise performance, walking or running tolerance and next-day recovery."] },
    { eyebrow: "Treatment Selection", title: "Exercise is foundational; adjuncts have narrower roles.", paragraphs: ["Physical therapy organizes load progression and return to activity. Chiropractic or manual care may address a relevant ankle or foot restriction when it supports function, but passive care alone does not restore tendon capacity.", "Shockwave may be considered for selected persistent cases, and laser may be an adjunct. Neither guarantees tendon healing. Choices should account for diagnosis, evidence, cost, preferences and alternatives."] },
    { eyebrow: "What You Can Do", title: "Avoid sudden load spikes and plan the return to speed or hills.", paragraphs: ["Reduce the most provocative variable temporarily—such as hill volume, sprinting or consecutive running days—while maintaining tolerable activity. Do not repeatedly stretch deeply into insertional pain without guidance.", "Track morning stiffness, walking response, heel-raise capacity and recovery after training. Restore volume before adding high speed or explosive work when that sequence fits the goal."] },
    { eyebrow: "Additional Evaluation", title: "A sudden pop or loss of push-off can signal rupture.", paragraphs: ["Seek urgent evaluation for a sudden pop, immediate weakness, bruising, a palpable gap, or inability to push off or perform a heel raise after injury. Significant trauma, marked swelling, redness with systemic illness or calf swelling with shortness of breath also warrants prompt medical care.", "Imaging or specialist assessment may be appropriate for suspected partial tear, uncertain diagnosis, atypical symptoms or delayed recovery when the result would change management."] },
  ],
  faqs: [{ question: "Is Achilles tendinopathy the same as a rupture?", answer: "No. Tendinopathy is usually a load-related pain and function problem. A rupture often has sudden onset, a pop and marked loss of push-off and needs urgent evaluation." }, { question: "Should everyone stretch the Achilles?", answer: "No. Deep dorsiflexion can aggravate insertional symptoms. Stretching decisions depend on location, mobility, irritability and task goals." }, { question: "Do I have to stop running?", answer: "Not always. A temporary change in volume, speed, hills or frequency may allow symptoms to settle while capacity is rebuilt." }, { question: "What is the main treatment?", answer: "Progressive tendon loading is central for many appropriate presentations, with dosage matched to symptoms, function and recovery." }],
  sources: [{ label: "APTA Orthopedics: Achilles Tendinopathy CPG 2024", href: "https://www.orthopt.org/content/s/achilles-pain-stiffness-and-muscle-power-deficits-midportion-achilles-tendinopathy-revision-2024", note: "Current clinical practice guideline for midportion Achilles tendinopathy." }, { label: "Dutch Multidisciplinary Achilles Guideline", href: "https://doi.org/10.1136/bjsports-2020-103867", note: "Multidisciplinary guidance on diagnosis, loading, imaging and referral." }],
});

export const siJointPage = page({
  path: "/si-joint-pain-lafayette", name: "SI Joint Pain", eyebrow: "SI-Region Pain Care in Lafayette, Louisiana", h1: "SI joint pain care that starts by confirming the pain source.", title: "SI Joint Pain Treatment in Lafayette, LA", description: "SI joint pain treatment in Lafayette, LA with careful differential diagnosis, chiropractic, physical therapy, and functional rehabilitation at Relief Plus.",
  hero: "Pain near the sacroiliac region can come from the SI joint, lumbar spine, hip, muscle, nerve, or referred sources. Relief Plus begins with a differential examination rather than assuming the pelvis is “out.”",
  overviewTitle: "Pain in the SI region is not the same as confirmed SI-joint pain.",
  overview: ["The sacroiliac joints transfer load between the spine and lower limbs. Symptoms near one joint can overlap with low-back pain, hip conditions, muscular referral, nerve symptoms and inflammatory disease. Location is a clue, not confirmation.", "A cluster of symptom-reproduction tests may increase or decrease clinical suspicion. In more complex or persistent cases, medical evaluation and an image-guided diagnostic block may be considered when confirmation would change an interventional decision."],
  examTitle: "The examination tests hypotheses rather than visual “alignment.”",
  exam: [{ title: "Build the differential", description: "We review location, onset, trauma, pregnancy or postpartum context when relevant, systemic symptoms, neurological findings and aggravating tasks." }, { title: "Use test clusters", description: "Selected SI provocation tests may be combined; one motion or palpation finding does not establish that the joint is the source." }, { title: "Assess function", description: "Lumbar and hip movement, gait, single-leg load, transitions, lifting and rotation may reveal relevant capacity or symptom patterns." }],
  dailyTitle: "SI-region symptoms often emerge during load transfer and transitions.", dailyDescription: "The same location can behave differently during walking, rolling, lifting or standing on one leg.",
  daily: [{ title: "Gait", description: "Stride, stance time, speed and hills may change load through the region." }, { title: "Single-leg loading", description: "Stairs, dressing and stepping can expose hip and trunk capacity." }, { title: "Transitions", description: "Rolling in bed, rising, entering a car and changing direction may be provocative." }, { title: "Lifting and rotation", description: "Load position, speed, breath strategy and repetition influence demand." }],
  related: [{ title: "Back Pain", href: "/back-pain-lafayette" }, { title: "Hip Pain", href: "/hip-pain-lafayette" }, { title: "Sciatica", href: "/sciatica-treatment-lafayette" }, { title: "Herniated Disc", href: "/herniated-disc-lafayette" }],
  approach: "Chiropractic, physical therapy, education and progressive exercise may work together when the examination supports a mechanical SI-region presentation. Dry needling is limited to a separate muscular contributor. Advanced options require a clearer diagnosis, failed appropriate conservative care and candidacy review.",
  therapies: [chiropractic("May address clinically relevant joint restriction or symptom modulation without claiming pelvic realignment."), pt("Develops hip, trunk and lower-limb capacity for gait, transitions, lifting and other tasks."), dry("May address a clearly separate muscular contributor; it does not confirm or reposition the SI joint."), { title: "Regenerative Medicine", href: "/regenerative-cellular-therapy-lafayette", description: "Not routine; advanced options require specific diagnosis, evidence review, candidacy and alternatives." }],
  sections: [
    { eyebrow: "Differential Diagnosis", title: "Lumbar, hip, muscular, and referred pain can mimic the SI joint.", paragraphs: ["Low-back and disc-related symptoms can refer toward the buttock. Hip-joint conditions may involve groin, lateral hip or posterior symptoms. Muscles and nerves can also create pain near the SI region. Examination therefore includes neighboring regions and neurological screening when relevant.", "Inflammatory sacroiliitis, fracture, infection and other medical conditions require different evaluation. Morning stiffness, systemic symptoms, trauma, health history and symptom pattern may change referral priorities."] },
    { eyebrow: "Functional Movement", title: "The pelvis transfers force; it is not described as slipping out of place.", paragraphs: ["Walking and single-leg tasks require coordinated contribution from the foot, hip, trunk and pelvic region. Rotation and force transfer during lifting or changing direction may influence demand. Breathing and trunk-pressure strategy may also be assessed for difficult tasks.", "A weight shift, asymmetry or muscle recruitment difference may be a compensation, a contributing factor or normal variation. It does not prove that the pelvis is “out,” and treatment is not based on visual alignment alone."], items: [{ title: "Gait", description: "Painful stance, stride and speed may help identify load sensitivity." }, { title: "Hip contribution", description: "Strength, motion and control can affect single-leg demand without being labeled the cause." }, { title: "Trunk strategy", description: "Rotation, bracing and breath timing may be explored during lifting or transitions." }, { title: "Task specificity", description: "A finding matters most when it relates consistently to a meaningful activity and changes with intervention." }] },
    { eyebrow: "Pregnancy and Postpartum", title: "Peripartum symptoms deserve context, not assumptions about instability.", paragraphs: ["Pregnancy and postpartum changes can alter load, recovery, sleep and daily lifting demands. Pelvic-girdle symptoms are real, but they should not be explained with fear-based claims that the pelvis is unstable or permanently misaligned.", "Assessment and exercise are adapted to stage, medical history and symptoms. Coordination with obstetric or medical care is appropriate when symptoms are severe, atypical or accompanied by pregnancy-related warning signs."] },
    { eyebrow: "Treatment Selection", title: "Manual care and exercise are matched to a supported clinical pattern.", paragraphs: ["Chiropractic or manual therapy may help selected patients with relevant joint or movement findings. Physical therapy may build hip, trunk and lower-limb capacity and progress gait, transitions, lifting and rotation.", "Dry needling may address a separate muscular contributor. Advanced or interventional options are not routine and require clearer diagnostic support, appropriate prior care, evidence and risk discussion, and referral when outside the clinic’s role."] },
    { eyebrow: "What You Can Do", title: "Vary provocative load while rebuilding the task that matters.", paragraphs: ["Temporarily shorten a stride, change lifting position, break up prolonged standing or use both legs more evenly during a difficult transition if that reduces symptoms. These are options, not rules about perfect movement.", "Build tolerance through progressive hip, trunk and lower-limb exercise and graded exposure to walking, stairs, lifting or rotation. Track recovery and function rather than repeatedly checking pelvic symmetry."] },
    { eyebrow: "Additional Evaluation", title: "Neurological, traumatic, inflammatory, or systemic findings change the plan.", paragraphs: ["Urgent assessment is appropriate for new bowel or bladder dysfunction, saddle sensory change, progressive or significant leg weakness, major trauma, fever with severe pain, or other rapidly worsening neurological or systemic findings.", "Medical review may also be warranted for suspected inflammatory disease, unexplained weight loss, persistent night pain, pregnancy-related warning signs, or symptoms that remain disabling despite appropriate care. Imaging does not reliably confirm ordinary mechanical SI pain, but it may help evaluate important alternatives."] },
  ],
  faqs: [{ question: "Can you tell if my pelvis is out by looking at it?", answer: "Relief Plus does not use that explanation. Visual asymmetry and palpation alone do not confirm SI-joint pain. History, test clusters, regional screening and function are considered together." }, { question: "How is SI-joint pain confirmed?", answer: "A compatible history and a cluster of provocation tests can raise clinical suspicion. In selected persistent cases, an image-guided diagnostic block may be used by an appropriate specialist when confirmation would change care." }, { question: "Can chiropractic and physical therapy work together?", answer: "Yes, when appropriate. Manual care may help selected joint or symptom findings while rehabilitation builds capacity for gait, lifting and other tasks." }, { question: "Is SI pain common in pregnancy?", answer: "Pelvic-girdle symptoms can occur during pregnancy or postpartum, but severe or atypical symptoms require appropriate obstetric or medical review. Care should avoid fear-based instability claims." }],
  sources: [{ label: "American Family Physician: SI Joint Dysfunction", href: "https://www.aafp.org/pubs/afp/issues/2022/0300/p239.html", note: "Evidence review on differential diagnosis, provocation testing and conservative care." }, { label: "Pain Medicine: SI Joint Complex Pain Consensus Guideline", href: "https://doi.org/10.1093/pm/pnaf129", note: "Multispecialty consensus guidance on diagnosis and treatment pathways." }],
});

export const phaseFiveConditionPages = [
  kneeOsteoarthritisPage,
  rotatorCuffPage,
  tmjPage,
  frozenShoulderPage,
  hipBursitisPage,
  tennisElbowPage,
  achillesPage,
  siJointPage,
] as const;
