import type { PillarLink, PillarPageData } from "./pillar-pages";

type Input = {
  path: PillarPageData["path"]; name: string; eyebrow: string; h1: string; title: string; description: string; hero: string;
  overviewTitle: string; overview: string[]; examTitle: string; exam: PillarPageData["serviceSteps"];
  functionTitle: string; functionDescription: string; functions: PillarPageData["considerations"];
  related: PillarPageData["conditions"]; approach: string; therapies: PillarLink[];
  sections: NonNullable<PillarPageData["educationSections"]>; faqs: PillarPageData["faqs"]; sources: NonNullable<PillarPageData["pageSources"]>;
};

function createPage(input: Input): PillarPageData {
  return {
    path: input.path, breadcrumbLabel: input.name, eyebrow: input.eyebrow, h1: input.h1,
    seoTitle: input.title, seoDescription: input.description, heroDescription: input.hero,
    heroPoints: ["Symptoms are classified before treatment is selected", "Movement and load are assessed in meaningful tasks", "Care is individualized to findings, goals, and clinical suitability"],
    overviewTitle: input.overviewTitle, overviewParagraphs: input.overview,
    serviceTitle: input.examTitle, serviceSteps: input.exam, whoTitle: input.functionTitle,
    whoDescription: input.functionDescription, considerations: input.functions,
    conditionsDescription: "Related guides clarify overlapping diagnoses and symptom patterns. An examination is still needed to identify which findings matter for the individual patient.",
    conditions: input.related, approachDescription: input.approach, relatedServices: input.therapies,
    educationSections: input.sections, faqs: input.faqs, pageSources: input.sources,
    ctaTitle: `Start with an individualized ${input.name.toLowerCase()} evaluation.`,
    ctaDescription: "Call Relief Plus in Lafayette to discuss symptoms, function, and an appropriate next step for care in Carencro and across Acadiana.",
  };
}

const care = {
  chiropractic: (description: string): PillarLink => ({ title: "Chiropractic", href: "/chiropractic-adjustments-lafayette", description }),
  pt: (description: string): PillarLink => ({ title: "Physical Therapy", href: "/physical-therapy-lafayette", description }),
  dry: (description: string): PillarLink => ({ title: "Dry Needling", href: "/dry-needling-lafayette", description }),
  laser: (description: string): PillarLink => ({ title: "Class IV Laser Therapy", href: "/class-iv-laser-therapy-lafayette", description }),
  shockwave: (description: string): PillarLink => ({ title: "Shockwave Therapy", href: "/shockwave-therapy-lafayette", description }),
  prp: (description: string): PillarLink => ({ title: "PRP Therapy", href: "/prp-therapy-lafayette", description }),
};

export const headachePage = createPage({
  path: "/headache-treatment-lafayette", name: "Headache Care", eyebrow: "Headache Evaluation in Lafayette, Louisiana",
  h1: "Headache care begins by identifying the pattern—not assuming every headache is mechanical.",
  title: "Headache Treatment in Lafayette, LA", description: "Headache treatment in Lafayette, LA with careful classification, neck and movement evaluation, physical therapy, and selected chiropractic care at Relief Plus.",
  hero: "Headache is a symptom category, not one diagnosis. Relief Plus distinguishes patterns that may involve the neck or jaw from migraine, tension-type, post-traumatic, and medically concerning presentations before discussing care.",
  overviewTitle: "Similar head pain can reflect very different clinical priorities.",
  overview: ["Cervicogenic headache is associated with a neck source and may change with cervical movement or sustained position. Tension-type headache and migraine have different diagnostic features, and jaw-related or post-traumatic symptoms add other considerations.", "A headache label should come from history and appropriate screening. Location alone cannot establish the cause, and chiropractic is not presented as a universal migraine treatment."],
  examTitle: "A headache examination starts with classification and safety screening.",
  exam: [{ title: "Define the pattern", description: "Onset, frequency, duration, location, associated symptoms, medication use, trauma, sleep, visual demands, and known diagnoses help guide the differential." }, { title: "Screen neurological and medical findings", description: "When relevant, cranial nerve, strength, sensation, coordination, balance, vital signs, and systemic history help determine whether medical evaluation should lead." }, { title: "Assess mechanical contributors", description: "Upper-cervical and thoracic movement, jaw function, shoulder-girdle endurance, breathing, and work tasks may be assessed when the history supports them." }],
  functionTitle: "Headache burden is measured through life—not pain intensity alone.", functionDescription: "Screen tolerance, concentration, driving, sleep, exercise, and work may reveal different triggers and recovery needs.",
  functions: [{ title: "Screen and visual demand", description: "Duration, breaks, lighting, and visual symptoms may influence work tolerance." }, { title: "Neck movement", description: "Turning, looking up, and sustained positions may reproduce selected cervicogenic patterns." }, { title: "Jaw load", description: "Clenching, chewing, and TMJ symptoms may overlap with temple or facial pain." }, { title: "Sleep and recovery", description: "Sleep disruption and overall load may influence headache frequency without being treated as the sole cause." }],
  related: [{ title: "Neck Pain", href: "/neck-pain-lafayette" }, { title: "TMJ / Jaw Pain", href: "/tmj-treatment-lafayette" }, { title: "Pinched Nerve", href: "/pinched-nerve-lafayette" }],
  approach: "Care is offered only when the classified presentation and examination support a musculoskeletal contribution. Chiropractic may address selected cervicogenic findings; physical therapy, education, exercise, and dry needling may address relevant movement, endurance, and muscular factors. Medical headache care remains appropriate when indicated.",
  therapies: [care.chiropractic("Considered for selected cervicogenic or mechanical neck findings—not as a blanket treatment for migraine."), care.pt("May develop cervical and shoulder-girdle capacity, movement options, and graded return to work or activity."), care.dry("May be an adjunct for selected muscular contributors after headache classification and safety screening.")],
  sections: [
    { eyebrow: "Headache Categories", title: "Cervicogenic, tension-type, migraine, jaw-related, and post-traumatic patterns require distinction.", paragraphs: ["Cervicogenic headache is typically linked to a cervical disorder and may be accompanied by reduced neck motion or reproduction with neck-related testing. Tension-type headache often presents differently, while migraine may include nausea, light or sound sensitivity, or neurological aura.", "Jaw-muscle or TMJ pain can refer toward the temple. Headache following a collision or blow to the head requires trauma and concussion screening. More than one pattern can coexist, so a single symptom should not determine treatment."] },
    { eyebrow: "Beyond the Head", title: "The neck, thorax, rib cage, jaw, and visual task can influence selected presentations.", paragraphs: ["Upper-cervical motion, thoracic movement, shoulder-girdle endurance, rib-cage mechanics, and breathing strategy may affect sustained desk or driving tasks. The jaw may be relevant when chewing, clenching, or facial pain reproduces symptoms.", "These findings may contribute or compensate; they do not prove that posture, stress, one tight muscle, or a spinal misalignment caused the headache."], items: [{ title: "Work position", description: "Time, task variation, and recovery matter more than labeling one posture as bad." }, { title: "Breathing and bracing", description: "Breath holding may accompany effort and is assessed only when relevant." }, { title: "Visual demand", description: "Eye strain or visual symptoms may require optometric or medical input." }, { title: "Jaw contribution", description: "TMJ and chewing-muscle findings are interpreted with the complete headache history." }] },
    { eyebrow: "Treatment Selection", title: "A mechanical contribution must be supported before musculoskeletal care leads.", paragraphs: ["Chiropractic or manual care may address relevant cervical or thoracic restriction in a selected cervicogenic presentation. Physical therapy may use exercise, endurance, movement retraining, and task progression. Dry needling may address a distinct muscular component.", "Education can address pacing, sleep routines, hydration, screen breaks, and a headache diary where appropriate. These strategies complement—not replace—medical evaluation and diagnosis-specific migraine or other headache management."] },
    { eyebrow: "What You Can Do", title: "Track pattern, context, and associated symptoms rather than repeatedly testing pain.", paragraphs: ["Record onset, duration, activity, sleep, medication, menstrual or other relevant context, neurological symptoms, and what helped. A diary can show patterns without implying that every association is causal.", "Vary sustained tasks, use tolerable neck and upper-body movement, and follow a graded plan. Avoid forceful self-manipulation or aggressive exercise during a new, unexplained, or rapidly changing headache."] },
    { eyebrow: "Medical Evaluation", title: "New or concerning headache patterns deserve timely medical attention.", paragraphs: ["Emergency assessment is appropriate for a sudden severe headache reaching maximum intensity quickly, new weakness or numbness, difficulty speaking, confusion, seizure, loss of consciousness, severe or worsening post-traumatic headache, or headache with fever and neck stiffness.", "Prompt medical review is also appropriate for a new progressive pattern, substantial change from usual headaches, persistent vomiting, pregnancy or postpartum concern, cancer or immune-suppression history, or symptoms triggered by exertion when unexplained."] },
  ],
  faqs: [{ question: "Can headaches come from the neck?", answer: "Some can. A cervicogenic pattern is supported by history and examination; neck pain alone does not prove the diagnosis." }, { question: "Does chiropractic treat every migraine?", answer: "No. Migraine is a neurological headache disorder. Musculoskeletal care is considered only for relevant coexisting findings and should not replace appropriate medical management." }, { question: "Could my jaw contribute?", answer: "Jaw-joint or chewing-muscle symptoms can overlap with headache. Chewing, clenching, jaw motion, and the broader headache pattern are assessed together." }, { question: "When is a headache urgent?", answer: "A sudden severe headache, neurological change, seizure, significant trauma, fever with neck stiffness, loss of consciousness, or rapidly worsening pattern warrants urgent medical evaluation." }],
  sources: [{ label: "VA/DoD: Management of Headache CPG", href: "https://www.healthquality.va.gov/guidelines/Pain/headache/", note: "Evidence-based guidance on headache assessment and management." }, { label: "International Classification of Headache Disorders", href: "https://ichd-3.org/", note: "Diagnostic framework distinguishing primary and secondary headache disorders." }],
});

export const shoulderPainPage = createPage({
  path: "/shoulder-pain-lafayette", name: "Shoulder Pain", eyebrow: "Shoulder Pain Care in Lafayette, Louisiana", h1: "Shoulder pain care built around the diagnosis and the task that hurts.",
  title: "Shoulder Pain Treatment in Lafayette, LA", description: "Shoulder pain treatment in Lafayette, LA with diagnosis-focused physical therapy, chiropractic, progressive exercise, and selected adjuncts at Relief Plus.",
  hero: "Shoulder pain may arise from the rotator cuff, capsule, joint, tendon, neck, nerve, or another source. Relief Plus evaluates movement, strength, endurance, and load before selecting care.",
  overviewTitle: "A painful shoulder is a region, not a diagnosis.", overview: ["Gradual pain during reaching can reflect a different problem from sudden weakness after trauma. Rotator cuff tendinopathy or tear, adhesive capsulitis, arthritis, instability, tendon pain, and cervical referral can overlap.", "This broad regional guide helps patients understand the differential. The rotator-cuff and frozen-shoulder pages provide deeper diagnosis-specific education rather than competing with this page."],
  examTitle: "The examination separates mobility, strength, tendon, joint, and referred patterns.",
  exam: [{ title: "Clarify onset and behavior", description: "Traumatic versus gradual onset, night symptoms, instability, neurological features, work, sport, and health history shape priorities." }, { title: "Compare motion and capacity", description: "Active and passive motion, resisted testing, endurance, reaching, pushing, pulling, and lifting may identify meaningful limits." }, { title: "Screen connected regions", description: "Cervical, thoracic, rib-cage, scapular, and neurological findings are assessed when relevant and interpreted with shoulder-specific tests." }],
  functionTitle: "Shoulder demand changes with direction, leverage, speed, and repetition.", functionDescription: "A person may tolerate an isolated test but struggle with repeated overhead work, carrying, sleep, or sport.",
  functions: [{ title: "Reaching", description: "Height, distance, hand position, and trunk contribution alter demand." }, { title: "Pushing and pulling", description: "Load, speed, and shoulder position can expose strength or control limits." }, { title: "Overhead endurance", description: "Repeated work may reveal fatigue not seen in one repetition." }, { title: "Lifting and carrying", description: "Lever length and load position influence shoulder and cuff demand." }],
  related: [{ title: "Rotator Cuff Pain", href: "/rotator-cuff-pain-lafayette" }, { title: "Frozen Shoulder", href: "/frozen-shoulder-lafayette" }, { title: "Neck Pain", href: "/neck-pain-lafayette" }, { title: "Tendonitis", href: "/tendonitis-treatment-lafayette" }],
  approach: "Physical therapy and progressive exercise are prominent when mobility, strength, endurance, or task tolerance need development. Chiropractic may address relevant cervical, thoracic, or shoulder-joint findings. Adjuncts require a diagnosis-specific role and do not replace active care.",
  therapies: [care.pt("Progresses mobility, strength, endurance, and task-specific shoulder capacity."), care.chiropractic("May address relevant cervical, thoracic, rib, or shoulder-joint restrictions."), care.dry("May address selected muscular contributors."), care.laser("A possible adjunct without a healing guarantee."), care.shockwave("Reserved for selected persistent tendon diagnoses, not generic shoulder pain."), care.prp("Discussed only when a specific diagnosis, evidence, alternatives, and candidacy support it.")],
  sections: [
    { eyebrow: "The Differential", title: "Rotator cuff pain, frozen shoulder, joint pain, and neck referral behave differently.", paragraphs: ["Rotator cuff presentations often involve load-related pain or weakness. Frozen shoulder restricts active and passive motion. Joint irritation, instability, arthritis, biceps or other tendon pain, and cervical nerve-related symptoms require different emphasis.", "Traumatic onset, dislocation, marked weakness, neurological changes, and loss of passive motion change decisions about imaging and referral."] },
    { eyebrow: "Regional Interdependence", title: "The arm moves with the scapula, thorax, rib cage, and neck.", paragraphs: ["Scapular rotation and endurance, thoracic motion, rib-cage position, and cuff capacity influence reaching. The neck must be screened when symptoms travel, include tingling, or change with cervical movement.", "A visible scapular difference is not a stand-alone diagnosis or proof of causation. It may be a compensation, a modifiable contributor, or normal variation."], items: [{ title: "Scapular movement", description: "Assessed during the task and interpreted with symptoms and strength." }, { title: "Thoracic motion", description: "May influence overhead options without being blamed as the cause." }, { title: "Rib-cage strategy", description: "Breathing and trunk position can change reach in selected patients." }, { title: "Cervical screen", description: "Helps distinguish shoulder-region pain from neck or nerve contribution." }] },
    { eyebrow: "Progressive Capacity", title: "Rehabilitation matches the shoulder to real-world demand.", paragraphs: ["Exercise may progress mobility, cuff and scapular strength, pushing, pulling, carrying, overhead endurance, or faster sport demands. The starting point reflects irritability and diagnosis.", "Temporary task modification can reduce a provocative dose while capacity develops. Indefinite avoidance is not automatically the goal."] },
    { eyebrow: "Adjuncts", title: "Modalities are diagnosis-specific, not a menu for every shoulder.", paragraphs: ["Dry needling may address selected muscular pain and laser may be an adjunct. Shockwave evidence and suitability differ between calcific and noncalcific tendon presentations. PRP requires a specific diagnosis and careful evidence and candidacy review.", "Chiropractic may address relevant joint restrictions, but no passive treatment is described as realigning the shoulder or repairing a tear."] },
    { eyebrow: "Additional Evaluation", title: "Trauma, deformity, marked weakness, or systemic signs change the pathway.", paragraphs: ["Prompt care is appropriate after dislocation, major trauma, visible deformity, a hot swollen joint with fever, new vascular or neurological symptoms, or sudden inability to lift the arm.", "Imaging or orthopedic review may be appropriate for persistent substantial weakness, progressive motion loss, suspected full-thickness tear, uncertain diagnosis, or failure to progress when results would change management."] },
  ],
  faqs: [{ question: "Is all shoulder pain rotator cuff pain?", answer: "No. Frozen shoulder, joint conditions, cervical referral, instability, and other tendon problems can overlap." }, { question: "Why examine my neck and rib cage?", answer: "They participate in upper-body movement and can refer or influence symptoms. Findings matter only when they fit the rest of the examination." }, { question: "Should I avoid overhead use?", answer: "Temporary modification may help, but many plans progressively rebuild overhead capacity." }, { question: "Do I need an MRI?", answer: "Not always. Imaging is most useful when trauma, significant weakness, uncertain diagnosis, or a management-changing decision makes it relevant." }],
  sources: [{ label: "JOSPT: Rotator Cuff Tendinopathy CPG", href: "https://doi.org/10.2519/jospt.2025.13182", note: "Current guidance on shoulder assessment and active rehabilitation." }, { label: "AAOS: Rotator Cuff Injuries", href: "https://www.aaos.org/quality/quality-programs/rotator-cuff/", note: "Evidence-based orthopedic guidance on cuff injury evaluation and treatment." }],
});

export const kneePainPage = createPage({
  path: "/knee-pain-lafayette", name: "Knee Pain", eyebrow: "Knee Pain Care in Lafayette, Louisiana", h1: "Knee pain care that connects the structure, movement, and load.",
  title: "Knee Pain Treatment in Lafayette, LA", description: "Knee pain treatment in Lafayette, LA with careful evaluation, physical therapy, progressive loading, and individualized options at Relief Plus.",
  hero: "Knee pain can follow trauma, develop gradually, or reflect joint, tendon, ligament, meniscus, patellofemoral, arthritic, or referred contributors. Care begins by distinguishing the pattern.",
  overviewTitle: "Not every painful knee is arthritis—and not every structure needs the same plan.", overview: ["Swelling after a twist, gradual pain with running, pain on stairs, and persistent stiffness can represent different mechanisms. Locking, giving way, trauma, load changes, and symptom location help focus the differential.", "The knee-osteoarthritis page addresses confirmed or suspected OA. This broad page preserves regional intent and covers traumatic, load-related, and non-arthritic presentations."],
  examTitle: "A knee examination pairs local tests with walking and task performance.",
  exam: [{ title: "Classify onset and risk", description: "Trauma, swelling timing, locking, instability, systemic symptoms, prior injury, and recent load changes guide screening." }, { title: "Assess knee function", description: "Motion, strength, swelling, selected ligament or meniscal tests, squat, step, and sit-to-stand may be used when appropriate." }, { title: "Evaluate force transfer", description: "Hip contribution, ankle and foot motion, balance, gait, deceleration, and work or sport tasks may be assessed without assigning one cause." }],
  functionTitle: "Knee demand depends on the task and how quickly force must be managed.", functionDescription: "Walking, stairs, squatting, changing direction, and rising from a chair require different combinations of strength, motion, and control.",
  functions: [{ title: "Walking and stairs", description: "Distance, incline, speed, and step control help define tolerance." }, { title: "Squat and sit-to-stand", description: "Depth, load, chair height, and repetition alter demand." }, { title: "Single-leg control", description: "Balance, stepping, and deceleration may matter for work and sport." }, { title: "Swelling and recovery", description: "Timing and next-day response guide load progression and referral decisions." }],
  related: [{ title: "Knee Osteoarthritis", href: "/knee-osteoarthritis-lafayette" }, { title: "Hip Pain", href: "/hip-pain-lafayette" }, { title: "Tendonitis", href: "/tendonitis-treatment-lafayette" }, { title: "Work Injuries", href: "/work-injury-lafayette" }],
  approach: "Physical therapy and progressive loading lead when strength, mobility, force absorption, or task capacity are limited. Chiropractic may address relevant hip, ankle, or regional joint findings. Adjunctive and advanced options require a specific diagnosis.",
  therapies: [care.pt("Develops knee and lower-limb capacity for walking, stairs, work, or sport."), care.chiropractic("May address relevant hip, ankle, foot, or regional restrictions."), care.dry("May address a selected muscular component."), care.laser("A possible adjunct, not a stand-alone diagnosis or repair treatment."), care.prp("Considered only for selected diagnosed presentations after evidence, alternatives, and candidacy review.")],
  sections: [
    { eyebrow: "Multiple Mechanisms", title: "Traumatic and gradual-onset knee pain require different questions.", paragraphs: ["A twisting injury with rapid swelling or inability to continue activity raises different concerns than gradual pain after a training or workload increase. Mechanical locking differs from brief stiffness, and true instability differs from pain-related hesitation.", "The examination tests likely structures while screening fracture, infection, vascular, neurological, and referred causes when indicated."] },
    { eyebrow: "Regional Interdependence", title: "The hip, ankle, and foot help the knee absorb and redirect force.", paragraphs: ["Stairs, landing, cutting, and lifting distribute force across the lower limb. Hip strength, ankle dorsiflexion, foot contact, trunk strategy, and task speed may influence knee demand.", "A knee moving inward or a foot position does not prove cause. The finding must be consistent, meaningful to the task, and interpreted with tissue and symptom findings."], items: [{ title: "Force absorption", description: "Hip, knee, and ankle share demand during landing and deceleration." }, { title: "Single-leg task", description: "Balance and control may reveal capacity or confidence limits." }, { title: "Ankle motion", description: "May change squat or stair strategy without being the sole cause." }, { title: "Work and sport", description: "Repetition, surface, speed, and recovery define the actual exposure." }] },
    { eyebrow: "Progressive Loading", title: "Capacity grows through a tolerable, diagnosis-specific dose.", paragraphs: ["Exercise may target quadriceps, hamstrings, calf, hip, balance, or task practice depending on findings. Range, resistance, speed, volume, and direction progress separately.", "Temporary modification can reduce swelling or irritability, but complete rest may reduce capacity. Progress is guided by function and recovery, not by forcing through escalating symptoms."] },
    { eyebrow: "Treatment Selection", title: "Advanced options require a named target and candidacy discussion.", paragraphs: ["Chiropractic or manual care may address relevant regional restrictions; dry needling may address muscular contributors; and laser may be an adjunct. None determines the diagnosis or replaces rehabilitation.", "PRP or another advanced option is discussed only when a supported diagnosis, evidence, goals, risks, alternatives, and candidacy justify it. Relief Plus does not promise cartilage regrowth or guaranteed avoidance of surgery."] },
    { eyebrow: "Additional Evaluation", title: "Major trauma, marked swelling, locking, or systemic illness may require imaging or referral.", paragraphs: ["Prompt evaluation is appropriate for inability to bear weight after trauma, deformity, a hot swollen joint with fever, suspected fracture, rapidly increasing swelling, new neurological or vascular symptoms, or calf swelling with breathing difficulty.", "Imaging or orthopedic review may be useful for true locking, recurrent giving way, suspected significant ligament or meniscal injury, or persistent disability when the result would change care."] },
  ],
  faqs: [{ question: "Does knee pain mean arthritis?", answer: "No. Tendon, ligament, meniscal, patellofemoral, traumatic, and referred presentations are among the alternatives." }, { question: "Is some discomfort during exercise acceptable?", answer: "It may be for selected conditions, but dosage depends on diagnosis, swelling, irritability, function, and recovery." }, { question: "Why assess my hip and ankle?", answer: "They share force during walking, stairs, squats, and deceleration. Their findings are considered as contributors, not assumed causes." }, { question: "When is locking concerning?", answer: "A knee that is mechanically unable to fully bend or straighten, particularly after trauma or with swelling, deserves timely evaluation." }],
  sources: [{ label: "APTA Orthopedics: Knee Pain CPGs", href: "https://www.orthopt.org/content/practice/clinical-practice-guidelines/cpgs", note: "Clinical practice guidance covering common knee pain and movement presentations." }, { label: "ACR: Acute Trauma to the Knee", href: "https://acsearch.acr.org/docs/69419/Narrative/", note: "Imaging appropriateness guidance after acute knee trauma." }],
});

export const hipPainPage = createPage({
  path: "/hip-pain-lafayette", name: "Hip Pain", eyebrow: "Hip Pain Care in Lafayette, Louisiana", h1: "Hip pain care that distinguishes the joint, lateral hip, muscle, and referred sources.",
  title: "Hip Pain Treatment in Lafayette, LA", description: "Hip pain treatment in Lafayette, LA with regional diagnosis, gait and movement evaluation, physical therapy, and individualized care at Relief Plus.",
  hero: "Hip-region pain may come from the hip joint, lateral gluteal tendons, muscle, lumbar spine, SI region, or another source. Relief Plus evaluates the location within gait, single-leg load, and the tasks affected.",
  overviewTitle: "Groin, lateral, buttock, and referred pain do not share one diagnosis.", overview: ["Groin-dominant pain may raise hip-joint questions; lateral pain can fit greater trochanteric pain syndrome; posterior symptoms may involve the lumbar spine, SI region, muscle, or nerve. Location helps, but history and examination are required.", "This broad regional page links to focused GTPS and SI-joint guides while remaining the primary landing page for patients who do not yet have a specific diagnosis."],
  examTitle: "The examination compares hip findings with lumbar, SI, and functional patterns.",
  exam: [{ title: "Map symptoms and onset", description: "Location, trauma, clicking, stiffness, neurological symptoms, night pain, load change, and health history guide the differential." }, { title: "Assess hip capacity", description: "Motion, strength, selected joint or tendon tests, single-leg load, and sit-to-stand may be assessed." }, { title: "Observe movement in context", description: "Gait, stairs, rotation, frontal and transverse-plane control, running, and work or sport tasks may reveal relevant demand." }],
  functionTitle: "Hip demand changes across gait, single-leg stance, rotation, and transitions.", functionDescription: "Walking and rising from a chair can expose different joint, tendon, trunk, and lower-limb requirements.",
  functions: [{ title: "Walking and running", description: "Distance, speed, incline, stride, and recovery alter load." }, { title: "Single-leg loading", description: "Stairs, curbs, dressing, and sport may expose lateral-hip capacity." }, { title: "Hip rotation", description: "Pivoting, sitting, and changing direction can help characterize joint and task tolerance." }, { title: "Sit-to-stand", description: "Chair height, depth, speed, and trunk strategy influence demand." }],
  related: [{ title: "Hip Bursitis / GTPS", href: "/hip-bursitis-lafayette" }, { title: "SI Joint Pain", href: "/si-joint-pain-lafayette" }, { title: "Back Pain", href: "/back-pain-lafayette" }, { title: "Sciatica", href: "/sciatica-treatment-lafayette" }],
  approach: "Physical therapy and exercise may develop hip, trunk, and lower-limb capacity. Chiropractic may address relevant hip, lumbar, or SI-region restrictions without claiming pelvic realignment. Modalities and advanced options require a supported diagnosis and defined role.",
  therapies: [care.pt("Develops mobility, strength, gait, single-leg control, and task tolerance."), care.chiropractic("May address relevant hip, lumbar, or SI-region joint findings."), care.dry("May address selected muscular contributors."), care.shockwave("May be considered for selected persistent lateral-hip tendon presentations."), care.laser("A possible adjunct without guaranteed tissue healing."), care.prp("Advanced discussion requires diagnosis-specific evidence, alternatives, and candidacy.")],
  sections: [
    { eyebrow: "The Hip Differential", title: "Joint pain, GTPS, muscle pain, and lumbar or SI referral can overlap.", paragraphs: ["Hip-joint conditions may affect groin pain, rotation, sitting, or deep flexion. GTPS often involves lateral tenderness and sensitivity with side lying or single-leg load. Lumbar or nerve-related symptoms may travel or include neurological findings.", "Trauma, inability to bear weight, systemic illness, and significant night pain require broader screening rather than routine musculoskeletal assumptions."] },
    { eyebrow: "Three-Dimensional Function", title: "The hip manages load in the frontal and transverse planes as well as forward and backward.", paragraphs: ["Walking, stair climbing, turning, and lifting require rotation and side-to-side control. The trunk, pelvis, knee, ankle, and foot all influence force transfer.", "A pelvic shift or rotation may be a protective response, capacity issue, or normal variation. It is not evidence that the pelvis is out of place."], items: [{ title: "Gait", description: "Stride, stance, speed, and trunk strategy may alter symptoms." }, { title: "Frontal-plane demand", description: "Single-leg tasks require lateral-hip and trunk contribution." }, { title: "Transverse-plane demand", description: "Pivoting and direction change reveal rotation tolerance." }, { title: "Lumbar screen", description: "Helps distinguish local hip findings from referred symptoms." }] },
    { eyebrow: "Progressive Capacity", title: "Exercise progresses toward the walking, work, or sport demand that matters.", paragraphs: ["Mobility, hip and trunk strength, balance, gait, and task exposure are selected from findings. A runner, a warehouse worker, and a person limited by stairs may share a pain location but need different progressions.", "Temporary load changes may calm irritability while maintaining useful activity. Complete rest is not automatically required."] },
    { eyebrow: "Treatment Selection", title: "The diagnosis determines whether a tendon, joint, muscle, or referred source leads the plan.", paragraphs: ["Chiropractic or manual care may address relevant hip, lumbar, or SI-region findings. Dry needling may address a muscular component. Shockwave may be considered for selected persistent gluteal tendinopathy and laser may be an adjunct.", "Advanced options require diagnosis-specific evidence and candidacy review. No treatment is presented as universally restoring the joint or guaranteeing relief."] },
    { eyebrow: "Additional Evaluation", title: "Trauma, systemic findings, or marked functional loss can warrant urgent or specialist care.", paragraphs: ["Prompt evaluation is appropriate after significant trauma, with inability to bear weight, deformity, fever with a hot painful joint, rapidly worsening symptoms, or new neurological or vascular findings.", "Imaging or orthopedic review may be useful for suspected fracture, significant tendon tear, progressive motion loss, persistent groin pain, uncertain diagnosis, or disability that does not improve when results would change management."] },
  ],
  faqs: [{ question: "Can hip pain come from my back?", answer: "Yes. Lumbar and nerve-related symptoms can refer toward the hip or buttock, so regional screening is important." }, { question: "Is lateral hip pain always bursitis?", answer: "No. Greater trochanteric pain syndrome often involves gluteal tendon sensitivity and may or may not include bursal involvement." }, { question: "Why assess gait?", answer: "Walking repeatedly transfers force through the trunk, hip, knee, ankle, and foot and can reveal task-specific tolerance." }, { question: "Does a pelvic shift mean my pelvis is out?", answer: "No. It may be compensation, pain avoidance, capacity, or normal variation and must be interpreted with the full examination." }],
  sources: [{ label: "APTA Orthopedics: Nonarthritic Hip Joint Pain CPG", href: "https://www.orthopt.org/content/s/hip-pain-and-movement-dysfunction-associated-with-nonarthritic-hip-joint-pain-revision-2023", note: "Guidance on hip differential diagnosis, function, and rehabilitation." }, { label: "JOSPT: GTPS Diagnostic Accuracy Review", href: "https://pubmed.ncbi.nlm.nih.gov/37561820/", note: "Systematic review of clinical tests for lateral hip pain and GTPS." }],
});

export const plantarFasciitisPage = createPage({
  path: "/plantar-fasciitis-lafayette", name: "Plantar Heel Pain", eyebrow: "Plantar Fasciitis Care in Lafayette, Louisiana", h1: "Plantar heel pain care built around first-step symptoms and foot-load capacity.",
  title: "Plantar Fasciitis Treatment in Lafayette, LA", description: "Plantar fasciitis treatment in Lafayette, LA with progressive loading, foot and ankle evaluation, physical therapy, and selected shockwave care at Relief Plus.",
  hero: "Plantar fasciitis—often called plantar fasciopathy in persistent cases—is a common source of heel pain, but not every painful heel has the same diagnosis. Relief Plus evaluates first-step pain, calf capacity, foot load, gait, and daily demand.",
  overviewTitle: "Plantar heel pain is a symptom region; plantar fasciitis is a clinical pattern.", overview: ["Classic symptoms often include pain near the inside underside of the heel with first steps after rest and with prolonged standing or walking. Persistent presentations are not always best understood as ongoing inflammation alone.", "Nerve irritation, stress injury, fat-pad pain, systemic conditions, and other sources can mimic plantar fascia pain. A careful history and examination come before stretching or a modality."],
  examTitle: "The examination connects local tenderness with ankle, calf, gait, and load history.",
  exam: [{ title: "Confirm the pattern", description: "First-step symptoms, location, duration, tenderness, neurological features, trauma, and health history help test the diagnosis." }, { title: "Measure foot and calf capacity", description: "Ankle dorsiflexion, heel raises, foot strength, balance, and walking tolerance may be assessed." }, { title: "Audit current load", description: "Standing, walking, running, footwear, surface, body-load context, and recent activity changes are considered without blame." }],
  functionTitle: "Heel demand accumulates across the day and changes with surface, speed, and recovery.", functionDescription: "Morning steps, prolonged standing, work shifts, and running may expose different aspects of tissue tolerance.",
  functions: [{ title: "First-step pain", description: "Response after sleep or sitting is characteristic but not diagnostic by itself." }, { title: "Standing and walking", description: "Duration, surface, pace, and breaks shape cumulative load." }, { title: "Calf capacity", description: "Heel-raise strength and endurance influence push-off and foot loading." }, { title: "Training changes", description: "Sudden increases in distance, speed, hills, or frequency may exceed recovery." }],
  related: [{ title: "Tendonitis / Tendinopathy", href: "/tendonitis-treatment-lafayette" }, { title: "Achilles Tendinopathy", href: "/achilles-tendinopathy-lafayette" }, { title: "Knee Pain", href: "/knee-pain-lafayette" }],
  approach: "Physical therapy and progressive foot, calf, and lower-limb loading lead when appropriate. Chiropractic may address relevant foot or ankle restrictions. Shockwave receives consideration for selected persistent cases after a diagnosis and adequate conservative care; dry needling and laser remain adjuncts.",
  therapies: [care.pt("Progresses calf, foot, balance, walking, and activity tolerance."), care.chiropractic("May address relevant foot and ankle joint restrictions."), care.shockwave("May be considered for selected persistent plantar heel pain after diagnosis and conservative-care review."), care.dry("May address selected calf or foot muscular contributors."), care.laser("A possible adjunct without a guaranteed healing effect.")],
  sections: [
    { eyebrow: "Terminology and Diagnosis", title: "Persistent plantar fascia pain is not necessarily continuous inflammation.", paragraphs: ["Patients commonly use plantar fasciitis, while plantar fasciopathy may better describe some longer-lasting tissue presentations. The terminology does not determine severity or a single treatment.", "First-step pain and medial heel tenderness support the pattern. Burning, marked numbness, night pain, trauma, or symptoms outside the typical location broaden the differential."] },
    { eyebrow: "Beyond the Heel", title: "Calf strength, ankle motion, foot loading, and gait may influence demand.", paragraphs: ["The plantar fascia contributes as the foot accepts and transfers load. Calf capacity, ankle dorsiflexion, foot motion, walking speed, and the hip and knee may influence how demand is distributed.", "Footwear and body weight can affect load, but neither is treated as a moral judgment or the only explanation. Findings should be interpreted with actual exposure and tissue tolerance."], items: [{ title: "Ankle dorsiflexion", description: "May influence walking and squat strategy but is not universally restricted." }, { title: "Calf endurance", description: "Push-off capacity can be measured and progressed." }, { title: "Footwear", description: "Fit, comfort, work requirements, and recent change are factors—not universal causes." }, { title: "Gait", description: "Pace, step, incline, and surface help define the provocative dose." }] },
    { eyebrow: "Progressive Loading", title: "Stretching can help some patients, but it is not the whole plan.", paragraphs: ["Plantar fascia and calf stretching may fit selected presentations. Strengthening can progress calf, foot, and lower-limb capacity toward standing, walking, running, or work demands.", "Complete rest may reduce symptoms temporarily but can leave the foot less prepared. A graded plan changes volume, resistance, speed, and impact according to recovery."] },
    { eyebrow: "Shockwave for Persistent Cases", title: "Shockwave is considered after diagnosis, expectations, and prior care are reviewed.", paragraphs: ["Clinical guidelines support extracorporeal shockwave as a possible option in selected chronic plantar heel pain, but protocols and individual responses vary. It is not automatically first-line and does not guarantee resolution.", "Relief Plus considers symptom duration, diagnosis, contraindications, prior loading and conservative care, goals, cost, and alternatives. Shockwave should accompany a plan for load and function rather than replace it."] },
    { eyebrow: "Additional Evaluation", title: "Atypical pain, trauma, neurological symptoms, or failure to progress may need more assessment.", paragraphs: ["Prompt evaluation is appropriate for inability to bear weight after trauma, marked swelling, redness with fever, an open wound, new neurological or vascular findings, or suspected fracture.", "Imaging or medical review may be considered for atypical night pain, suspected stress injury, persistent numbness, systemic inflammatory concern, uncertain diagnosis, or prolonged disability despite appropriate care."] },
  ],
  faqs: [{ question: "Is first-step pain always plantar fasciitis?", answer: "It is a common feature, but diagnosis also considers location, examination, duration, and alternative causes." }, { question: "Do I only need to stretch?", answer: "No. Stretching may help selected patients, while calf and foot loading, walking tolerance, and activity progression often deserve attention." }, { question: "Do I need different shoes?", answer: "Footwear comfort and task requirements matter, but there is no single shoe for every patient and footwear is rarely the entire explanation." }, { question: "When is shockwave considered?", answer: "It may be discussed for selected persistent cases after the diagnosis, prior care, risks, alternatives, and an active loading plan are reviewed." }],
  sources: [{ label: "APTA Orthopedics: Heel Pain—Plantar Fasciitis CPG 2023", href: "https://www.orthopt.org/content/s/heel-pain-plantar-fasciitis-revision-2023", note: "Current clinical practice guideline on diagnosis and treatment of plantar heel pain." }, { label: "JOSPT: Heel Pain—Plantar Fasciitis Revision", href: "https://doi.org/10.2519/jospt.2023.0303", note: "Peer-reviewed guideline supporting multimodal, diagnosis-specific care." }],
});

export const tendonitisPage = createPage({
  path: "/tendonitis-treatment-lafayette", name: "Tendonitis and Tendinopathy", eyebrow: "Tendon Care in Lafayette, Louisiana", h1: "Tendonitis and tendinopathy care built around load, capacity, and the specific tendon.",
  title: "Tendonitis Treatment in Lafayette, LA", description: "Tendonitis and tendinopathy treatment in Lafayette, LA with progressive loading, physical therapy, shockwave, and selected options at Relief Plus.",
  hero: "“Tendonitis” is familiar language, but many persistent tendon problems are better described as tendinopathy. Relief Plus evaluates the specific tendon, current load, capacity, and the work or sport demand involved.",
  overviewTitle: "Persistent tendon pain is not simply ongoing inflammation in every case.", overview: ["Tendons transfer force from muscle to bone. Pain can develop after a sudden load spike, repetitive exposure, deconditioning, trauma, or a combination of factors. Persistent symptoms reflect more than one biological process.", "This page is a tendon-education hub. Achilles, tennis elbow, rotator cuff, and gluteal tendon pages provide diagnosis-specific details because one universal protocol cannot fit every tendon."],
  examTitle: "A tendon examination identifies location, differential, capacity, and actual exposure.",
  exam: [{ title: "Name the tissue pattern", description: "History, local tests, trauma, neurological features, and alternative diagnoses help determine whether a tendon is the likely source." }, { title: "Measure current capacity", description: "Strength, endurance, speed, stretch-shortening demand, and symptom recovery may be assessed for the involved region." }, { title: "Understand the load", description: "Work repetition, grip, running, jumping, lifting, training changes, and recovery define what the tendon is being asked to tolerate." }],
  functionTitle: "Load is more than weight—it includes speed, range, repetition, and recovery.", functionDescription: "Two people with pain at the same tendon may need different starting points because their diagnoses, jobs, sports, and capacities differ.",
  functions: [{ title: "Load spikes", description: "Rapid changes in frequency, intensity, or duration may exceed current capacity." }, { title: "Repetitive work", description: "Force, position, tools, and breaks shape tendon exposure." }, { title: "Deconditioning", description: "Reduced activity can lower capacity even when it temporarily calms symptoms." }, { title: "Recovery response", description: "Next-day stiffness, function, and symptom duration guide progression." }],
  related: [{ title: "Achilles Tendinopathy", href: "/achilles-tendinopathy-lafayette" }, { title: "Tennis Elbow", href: "/tennis-elbow-lafayette" }, { title: "Rotator Cuff Pain", href: "/rotator-cuff-pain-lafayette" }, { title: "Hip Bursitis / GTPS", href: "/hip-bursitis-lafayette" }, { title: "Plantar Fasciitis", href: "/plantar-fasciitis-lafayette" }],
  approach: "Physical therapy and progressive loading lead for appropriate tendinopathy. Shockwave, dry needling, laser, or PRP may be considered only for selected diagnoses and stages. Chiropractic addresses relevant regional mechanics rather than the tendon through an alignment claim.",
  therapies: [care.pt("Builds diagnosis-specific tendon and movement capacity."), care.shockwave("May be considered for selected chronic or persistent tendinopathies with diagnosis-specific evidence."), care.dry("May address selected muscular contributors as an adjunct."), care.laser("A possible adjunct without guaranteed tendon healing."), care.prp("Reserved for selected diagnoses after evidence, risks, alternatives, and candidacy review."), care.chiropractic("May address relevant neighboring joint findings that influence the task.")],
  sections: [
    { eyebrow: "Inflammation and Tendinopathy", title: "The common word “tendonitis” does not describe every persistent tendon change.", paragraphs: ["Acute irritation can involve inflammatory processes, but chronic tendinopathy includes changes in pain, structure, and load tolerance that are not captured by inflammation alone. This distinction helps explain why passive anti-inflammatory strategies may not restore capacity.", "Imaging changes can appear without pain, and pain can be meaningful without dramatic imaging. The clinical pattern and function remain central."] },
    { eyebrow: "Load Versus Capacity", title: "Symptoms can emerge when demand changes faster than the tendon can adapt.", paragraphs: ["A new job, training increase, return after inactivity, or repeated high-force task may increase demand. Sleep, health, prior symptoms, and recovery may influence adaptation without becoming a single blamed cause.", "Complete rest can reduce symptoms yet lower capacity. The long-term plan often maintains tolerable activity while rebuilding the specific force, speed, or endurance required."], items: [{ title: "Strength", description: "Slow resistance may be one phase of tendon loading." }, { title: "Energy storage", description: "Running and jumping require later progression to faster loading." }, { title: "Task exposure", description: "Work and sport define the required end point." }, { title: "Recovery", description: "Symptoms and performance after loading help adjust dosage." }] },
    { eyebrow: "Specific Tendons", title: "Insertion, compression, and function differ by body region.", paragraphs: ["Insertional Achilles symptoms may require different ranges than midportion symptoms. Rotator cuff shockwave guidance differs between calcific and noncalcific presentations. Gluteal tendons may be sensitive to compression, while lateral elbow demand is closely tied to grip.", "Plantar fascia pain is related conceptually to load management but is not simply treated as another tendon. Each linked guide explains its own differential and progression."] },
    { eyebrow: "Adjunctive Options", title: "An adjunct needs a diagnosis-specific reason and realistic expectation.", paragraphs: ["Shockwave has different evidence across tendon sites and may fit selected persistent cases. Dry needling may address muscular contributors, and laser may be an adjunct. None replaces progressive loading.", "PRP evidence varies by tendon and study. Discussion must include the specific diagnosis, uncertainty, alternatives, risks, cost, and candidacy, without promising regeneration or predictable relief."] },
    { eyebrow: "Additional Evaluation", title: "Sudden loss of function, major trauma, or atypical symptoms may indicate tear or another diagnosis.", paragraphs: ["Urgent evaluation is appropriate after a sudden pop with marked weakness, bruising, a palpable gap, or loss of push-off or lifting function. Fever, redness, significant swelling, vascular symptoms, or neurological change also require prompt assessment.", "Imaging or specialist review may be useful for suspected substantial tear, uncertain diagnosis, atypical symptoms, or persistent disability when the result would change management."] },
  ],
  faqs: [{ question: "Is tendinopathy just inflammation?", answer: "Not in every persistent case. Tendon pain and capacity involve biological and mechanical factors beyond ongoing inflammation alone." }, { question: "Should I completely rest the tendon?", answer: "Temporary modification may help, but prolonged complete rest can reduce capacity. Loading should be matched to diagnosis and irritability." }, { question: "Is eccentric exercise always best?", answer: "No single contraction type or protocol fits every tendon. Isometric, isotonic, eccentric, heavy slow, and faster loading may be used at different stages." }, { question: "Does shockwave or PRP regenerate a tendon?", answer: "Relief Plus does not promise regeneration. These options require diagnosis-specific evidence and candidacy discussion." }],
  sources: [{ label: "JOSPT: Achilles Tendinopathy CPG 2024", href: "https://www.orthopt.org/content/s/achilles-pain-stiffness-and-muscle-power-deficits-midportion-achilles-tendinopathy-revision-2024", note: "Current tendon-loading guidance illustrating diagnosis-specific rehabilitation." }, { label: "JOSPT: Rotator Cuff Tendinopathy CPG 2025", href: "https://doi.org/10.2519/jospt.2025.13182", note: "Current evidence on active rehabilitation and diagnosis-specific adjuncts." }],
});

export const carAccidentPage = createPage({
  path: "/car-accident-injuries-lafayette", name: "Car Accident Injuries", eyebrow: "Car Accident Injury Care in Lafayette, Louisiana", h1: "Car accident injury care guided by mechanism, symptom evolution, and function.",
  title: "Car Accident Injury Treatment in Lafayette, LA", description: "Car accident injury treatment in Lafayette, LA with trauma screening, chiropractic, physical therapy, and individualized functional rehabilitation at Relief Plus.",
  hero: "A collision can affect the neck, back, shoulder, ribs, head, or extremities, and symptoms may evolve over hours or days. Relief Plus begins with trauma history, neurological and concussion screening, and the activities affected.",
  overviewTitle: "The mechanism matters, but it does not dictate one treatment plan.", overview: ["Direction of impact, vehicle position, restraint use, head contact, immediate symptoms, and symptom evolution help identify clinical priorities. A low-speed label alone does not establish injury severity, while not every collision produces the same tissue problem.", "Emergency and medical needs come before musculoskeletal treatment. Once serious injury is excluded, care focuses on the actual diagnosis and restoring driving, sleep, work, movement, and activity capacity."],
  examTitle: "A post-collision examination begins with trauma, neurological, and head-injury screening.",
  exam: [{ title: "Reconstruct the event", description: "Impact direction, body and head position, restraints, loss of consciousness, memory, immediate symptoms, and prior care provide context." }, { title: "Screen important injury", description: "Neurological, concussion, fracture, vascular, chest, abdominal, and systemic findings determine whether urgent or medical referral is needed." }, { title: "Assess movement and function", description: "Neck and trunk motion, strength, balance, shoulder or limb function, sitting, driving, lifting, and load tolerance may be assessed when safe." }],
  functionTitle: "Recovery is measured through safe return to normal activities.", functionDescription: "Turning to check traffic, sitting, sleeping, carrying, work, exercise, and concentration may recover at different rates.",
  functions: [{ title: "Driving", description: "Head turning, attention, sitting, and symptom response affect readiness." }, { title: "Sleep and positions", description: "Irritability may change with side lying, bed mobility, or sustained positions." }, { title: "Work and lifting", description: "Job-specific exposure helps shape progression." }, { title: "Exercise and recreation", description: "Return is graded according to diagnosis, neurological status, and capacity." }],
  related: [{ title: "Neck Pain", href: "/neck-pain-lafayette" }, { title: "Back Pain", href: "/back-pain-lafayette" }, { title: "Headache Care", href: "/headache-treatment-lafayette" }, { title: "Shoulder Pain", href: "/shoulder-pain-lafayette" }],
  approach: "Chiropractic, physical therapy, education, and exercise may be combined after appropriate trauma screening. Dry needling or laser may address selected muscular or pain contributors. Treatment and documentation reflect the clinical findings; Relief Plus does not provide legal advice or promise claim outcomes.",
  therapies: [care.chiropractic("May address selected joint and movement findings after trauma screening."), care.pt("Progresses mobility, strength, balance, endurance, driving, work, and activity capacity."), care.dry("May address selected secondary muscular contributors."), care.laser("A possible adjunct for selected presentations without healing guarantees.")],
  sections: [
    { eyebrow: "Symptoms Can Evolve", title: "Pain, stiffness, headache, dizziness, or neurological symptoms may appear or change after the event.", paragraphs: ["Stress responses and tissue irritation can evolve over hours or days. Neck, back, shoulder, rib, jaw, headache, and extremity complaints may coexist, but each requires its own differential.", "Worsening rather than stable or improving symptoms deserve reassessment. New cognitive, balance, visual, or emotional symptoms after head or body impact can be compatible with concussion and require medical evaluation."] },
    { eyebrow: "Functional Examination", title: "We evaluate more than where the body is sore.", paragraphs: ["Turning the head while driving, tolerating sitting, rolling in bed, reaching, lifting, walking, and returning to work require coordinated movement. Breathing and rib-cage motion may matter when chest or thoracic guarding is present after serious injury has been excluded.", "Protective stiffness may be useful early and later limit function. It is interpreted as a response—not proof that joints are out of place."], items: [{ title: "Neurological status", description: "Strength, sensation, reflexes, coordination, and balance may be assessed when relevant." }, { title: "Symptom behavior", description: "Direction, duration, and response to movement help guide safe progression." }, { title: "Load tolerance", description: "Sitting, lifting, walking, and exercise are progressed in stages." }, { title: "Care coordination", description: "Medical records and referrals are coordinated clinically, without legal promises." }] },
    { eyebrow: "Treatment Selection", title: "The diagnosis—not the fact that a crash occurred—determines care.", paragraphs: ["Chiropractic may address selected cervical, thoracic, lumbar, or extremity joint findings when safe. Physical therapy may restore motion, strength, balance, endurance, and task capacity. Education supports pacing and gradual return.", "Dry needling and laser may be adjuncts for selected findings. No patient automatically needs every service, and passive treatment does not replace progressive activity when rehabilitation is appropriate."] },
    { eyebrow: "Return to Activity", title: "Progress driving, work, and exercise according to neurological status and recovery.", paragraphs: ["Brief modification may be appropriate, but prolonged inactivity can reduce capacity. Progress may start with short walks and tolerable daily tasks, then add duration, resistance, speed, and work-specific exposure.", "Possible concussion changes driving and exertion decisions. Medical instructions and symptom-guided return should be followed, especially when attention, reaction time, vision, balance, or fatigue are affected."] },
    { eyebrow: "Urgent Post-Traumatic Findings", title: "Some symptoms require emergency or prompt medical evaluation.", paragraphs: ["Emergency care is appropriate for worsening severe headache, repeated vomiting, seizure, increasing confusion or drowsiness, loss of consciousness, unequal pupils, slurred speech, new weakness or numbness, loss of coordination, or significant head-injury concern.", "Chest pain, breathing difficulty, abdominal pain, uncontrolled bleeding, deformity, inability to bear weight, suspected fracture, new bowel or bladder dysfunction, saddle sensory change, or progressive neurological loss also warrants urgent medical assessment."] },
  ],
  faqs: [{ question: "Should I be evaluated if symptoms started the next day?", answer: "Yes, evolving symptoms can occur. New or worsening neurological, head-injury, chest, abdominal, or fracture concerns require prompt medical assessment." }, { question: "Does every accident patient need adjustments?", answer: "No. Treatment depends on diagnosis, trauma screening, symptoms, goals, and clinical suitability." }, { question: "Can I exercise after a collision?", answer: "Return should reflect injury type, neurological and concussion status, and symptom recovery. Some patients can begin light activity while others need medical restrictions." }, { question: "Does Relief Plus provide legal advice?", answer: "No. The clinic documents and coordinates clinical care but does not make legal or workers-compensation promises." }],
  sources: [{ label: "CDC: Mild TBI and Concussion Symptoms", href: "https://www.cdc.gov/traumatic-brain-injury/signs-symptoms/index.html", note: "Current public-health guidance on delayed symptoms and adult danger signs." }, { label: "ACR: Acute Spinal Trauma", href: "https://acsearch.acr.org/docs/69359/Narrative/", note: "Imaging appropriateness guidance for trauma-related spinal concerns." }],
});

export const workInjuryPage = createPage({
  path: "/work-injury-lafayette", name: "Work Injuries", eyebrow: "Work Injury Rehabilitation in Lafayette, Louisiana", h1: "Work injury care designed around the actual demands of the job.",
  title: "Work Injury Treatment in Lafayette, LA", description: "Work injury treatment in Lafayette, LA with job-specific physical therapy, chiropractic, progressive rehabilitation, and individualized care at Relief Plus.",
  hero: "Work symptoms may follow one event or build as exposure exceeds current capacity. Relief Plus evaluates the diagnosis alongside lifting, reaching, carrying, repetition, standing, walking, and sustained-position demands.",
  overviewTitle: "The same diagnosis can create different barriers in different jobs.", overview: ["A shoulder condition affects an overhead electrician differently from an office worker. Back symptoms during lifting differ from symptoms during prolonged driving. Job title alone is not enough; force, frequency, duration, environment, and recovery define exposure.", "Ergonomics can help, but posture is not blamed as the one cause. Rehabilitation focuses on restoring capacity and using practical modifications while the worker progresses."],
  examTitle: "The examination connects tissue findings with essential job functions.",
  exam: [{ title: "Clarify injury and diagnosis", description: "Sudden event versus cumulative onset, symptoms, prior care, medical restrictions, and relevant red flags guide the clinical differential." }, { title: "Define job demand", description: "Loads, heights, carrying distance, repetition, pushing, pulling, standing, walking, tools, and shift duration make the target specific." }, { title: "Measure functional capacity", description: "Mobility, strength, endurance, balance, lifting, reaching, carrying, and task simulation may be assessed within safe clinical limits." }],
  functionTitle: "Work capacity depends on exposure, recovery, and the individual task.", functionDescription: "A short clinic test and an eight-hour shift are different demands, so progression considers repetition and fatigue as well as maximum strength.",
  functions: [{ title: "Lifting and carrying", description: "Load, height, distance, frequency, and grip alter demand." }, { title: "Reaching and tools", description: "Overhead duration, precision, vibration, and repetition may matter." }, { title: "Standing and walking", description: "Surface, footwear, distance, and shift length shape exposure." }, { title: "Sustained positions", description: "Variation and break strategy can matter without labeling one posture as harmful." }],
  related: [{ title: "Back Pain", href: "/back-pain-lafayette" }, { title: "Shoulder Pain", href: "/shoulder-pain-lafayette" }, { title: "Knee Pain", href: "/knee-pain-lafayette" }, { title: "Tendonitis", href: "/tendonitis-treatment-lafayette" }],
  approach: "Physical therapy and therapeutic exercise build job-specific strength, endurance, movement options, and confidence. Chiropractic may address relevant joint findings. Education, dry needling, and laser may support selected cases. The clinic does not make legal, employment, or compensation promises.",
  therapies: [care.pt("Builds measurable capacity for lifting, reaching, carrying, standing, walking, and repetition."), care.chiropractic("May address relevant joint motion and musculoskeletal findings."), care.dry("May address selected muscular contributors that limit active progression."), care.laser("A possible diagnosis-specific adjunct without return-to-work guarantees.")],
  sections: [
    { eyebrow: "Injury and Exposure", title: "Work symptoms can follow a single incident or cumulative demand.", paragraphs: ["A fall, twist, lift, or impact may create an acute injury. Repetition, force, vibration, long duration, or rapid workload change may also exceed capacity without one memorable event.", "Exposure is not destiny. Health history, prior symptoms, recovery, available equipment, work organization, and physical capacity may influence the presentation without assigning fault to the worker."] },
    { eyebrow: "Task-Specific Function", title: "Movement is evaluated in the planes, positions, and repetitions the job requires.", paragraphs: ["Lifting from floor to waist differs from lowering overhead. Carrying, pushing, pulling, climbing, kneeling, and tool use each require distinct strength, coordination, and endurance.", "Breathing and trunk strategy, hip and shoulder contribution, and force transfer may be assessed during relevant tasks. A movement difference may be a compensation or training target, not proof of a single cause."], items: [{ title: "Force", description: "Object weight and push or pull resistance define intensity." }, { title: "Frequency", description: "Repetitions and shift duration reveal endurance demand." }, { title: "Position", description: "Height, reach distance, grip, and space constraints matter." }, { title: "Environment", description: "Surface, temperature, tools, and available assistance can affect exposure." }] },
    { eyebrow: "Graded Return", title: "Capacity is progressed toward essential duties rather than a generic exercise goal.", paragraphs: ["A plan may progress range, resistance, repetitions, duration, speed, and task complexity. Temporary restrictions or modifications should be tied to the diagnosis and current function and reassessed as capacity changes.", "Ergonomic changes can reduce unnecessary demand, but the goal is not perfect posture. Task variation, equipment, pacing, technique, and physical conditioning may work together."] },
    { eyebrow: "Treatment Selection", title: "Active rehabilitation leads when the goal is durable work capacity.", paragraphs: ["Physical therapy may use therapeutic exercise, functional training, education, and graded work simulation. Chiropractic may address relevant joint restrictions when safe and appropriate.", "Dry needling or laser may support selected muscular or pain presentations but do not replace strength, endurance, and task progression. Other modalities are used only when the diagnosis supports them."] },
    { eyebrow: "Additional Evaluation", title: "Trauma, neurological change, systemic illness, or inability to perform basic function may require referral.", paragraphs: ["Urgent assessment is appropriate for significant trauma, deformity, inability to bear weight, chest or abdominal symptoms, new bowel or bladder dysfunction, saddle sensory change, progressive weakness, severe head-injury symptoms, or vascular concerns.", "Imaging or specialist referral may be useful when fracture, significant tissue injury, neurological compromise, or an uncertain diagnosis is suspected, or when results would change restrictions and care." ] },
  ],
  faqs: [{ question: "Do you evaluate the actual job demands?", answer: "Yes. Load, height, repetition, carrying, tools, shift duration, and other essential functions help define rehabilitation goals." }, { question: "Is posture the cause of most work pain?", answer: "No. Posture is one possible exposure factor among force, repetition, duration, recovery, health, and physical capacity." }, { question: "How is return to work progressed?", answer: "Capacity and task tolerance are built in stages, coordinated with appropriate medical restrictions and employer processes where authorized." }, { question: "Do you provide workers-compensation or legal advice?", answer: "No. Relief Plus provides clinical evaluation, documentation, and care coordination, not legal or claim-outcome advice." }],
  sources: [{ label: "APTA Orthopedics: Work Participation CPG", href: "https://www.orthopt.org/content/s/clinical-guidance-to-optimize-work-participation-after-injury-or-illness-the-role-of-physical-therapists-2021", note: "Guidance on work ability, functional evaluation, coordination, and graded return." }, { label: "NIOSH: Ergonomics and Musculoskeletal Disorders", href: "https://www.cdc.gov/niosh/ergonomics/", note: "Public-health guidance on workplace risk factors and ergonomic programs." }],
});

export const phaseSixConditionPages = [headachePage, shoulderPainPage, kneePainPage, hipPainPage, plantarFasciitisPage, tendonitisPage, carAccidentPage, workInjuryPage] as const;
