import LegalPageShell from "@/app/components/LegalPageShell";
import { createPageMetadata } from "@/lib/seo";

const path = "/hipaa-notice-of-privacy-practices" as const;
export const metadata = createPageMetadata({ title: "HIPAA Notice of Privacy Practices", description: "Relief Plus Notice of Privacy Practices describing uses of medical information, patient privacy rights, and complaint information.", path });

export default function Page() { return <LegalPageShell path={path} title="HIPAA Notice of Privacy Practices" description="This page preserves the substantive notice published on the legacy Relief Plus website while correcting the display spelling from HIPPA to HIPAA." notice="THIS NOTICE DESCRIBES HOW MEDICAL INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY." sections={[
  { title: "About this notice", paragraphs: ["We understand the importance of privacy and are committed to maintaining the confidentiality of your medical information. We make a record of the medical care we provide and may receive such records from others. We use these records to provide or enable other health care providers to provide quality medical care, to obtain payment for services provided to you as allowed by your health plan and to enable us to meet our professional and legal obligations to operate this medical practice properly.", "We are required by law to maintain the privacy of protected health information, to provide individuals with notice of our legal duties and privacy practices with respect to protected health information, and to notify affected individuals following a breach of unsecured protected health information. This notice describes how we may use and disclose your medical information. It also describes your rights and our legal obligations with respect to your medical information.", "The legacy notice says questions should be directed to the Privacy Officer listed above, but the published page does not identify that officer. Please call Relief Plus at 337-565-4200 while this omission is under owner and legal review."] },
  { title: "How this medical practice may use or disclose your health information", paragraphs: ["This medical practice collects health information about you and stores it in a chart and on a computer. This is your medical record. The medical record is the property of this medical practice, but the information in the medical record belongs to you. The law permits us to use or disclose your health information for the following purposes:"], items: [
    "Treatment. We use medical information about you to provide your medical care and may disclose it to employees and others involved in providing the care you need, including other health care providers, pharmacists, or laboratories. We may also disclose information to family members or others who can help when you are sick or injured, or after you die.",
    "Payment. We use and disclose medical information to obtain payment for the services we provide and may assist other health care providers in obtaining payment for services they provided to you.",
    "Health Care Operations. We may use and disclose information to operate this practice, review and improve quality, review professional competence and qualifications, obtain authorizations, conduct medical reviews, legal services, audits, compliance, business planning, and management. Business associates are required by written contract to protect protected health information.",
    "Appointment Reminders. We may use and disclose medical information to contact and remind you about appointments, including leaving a message when appropriate.",
    "Sign-In Sheet. We may ask you to sign in when you arrive and may call your name when ready to see you.",
    "Notification and Communication With Family. We may notify or assist in notifying family, a personal representative, or another person responsible for your care about your location or general condition, and may share information with someone involved in or paying for your care as permitted by law.",
    "Marketing. The legacy notice permits certain treatment-, case-management-, care-coordination-, practice-, and health-related communications without payment and requires written authorization for other marketing communications or compensated marketing as described in the notice.",
    "Sale of Health Information. We will not sell your health information without prior written authorization that discloses compensation.",
    "Required by Law and Public Health. We may use or disclose information as required by law and for permitted public-health purposes, including disease or injury control, certain abuse or neglect reports, FDA reporting, and exposure notifications.",
    "Health Oversight, Judicial Proceedings, and Law Enforcement. Information may be disclosed as permitted or required for audits, investigations, inspections, licensure, legal proceedings, court orders, subpoenas, warrants, and other lawful law-enforcement purposes.",
    "Coroners; Organ or Tissue Donation; Public Safety. Information may be disclosed for death investigations, organ or tissue procurement and transplantation, or to prevent or lessen a serious and imminent threat as permitted by law.",
    "Proof of Immunization; Specialized Government Functions. Information may be disclosed to a school with agreement where proof is required, and for permitted military, national-security, correctional, or custody purposes.",
    "Workers’ Compensation. Information may be disclosed as necessary to comply with workers’ compensation laws.",
    "Change of Ownership. If the practice is sold or merged, the health record becomes the property of the new owner, while you maintain the right to request transfer of copies to another physician or medical group.",
    "Breach Notification. In the case of a breach of unsecured protected health information, we will notify you as required by law. Notification may be provided by the practice, a business associate, email when a current address was provided, or other appropriate methods.",
  ] },
  { title: "When this medical practice may not use or disclose your information", paragraphs: ["Except as described in this Notice of Privacy Practices, this medical practice will, consistent with its legal obligations, not use or disclose health information which identifies you without your written authorization. If you authorize a use or disclosure for another purpose, you may revoke your authorization in writing at any time."] },
  { title: "Your health information rights", items: [
    "Right to Request Special Privacy Protections. You may request restrictions in writing. If you ask us not to disclose to a commercial health plan information about items or services paid in full out of pocket, we will abide by the request unless disclosure is required for treatment or legal reasons. Other requests may be accepted or rejected.",
    "Right to Request Confidential Communications. You may request in writing to receive information in a specific way or at a specific location. We will comply with reasonable requests specifying how or where communications should be sent.",
    "Right to Inspect and Copy. You may inspect and copy health information, with limited exceptions, by submitting a written request. Copies will be provided in a readily producible requested format, an acceptable alternative, or a readable electronic or hardcopy format as applicable. A reasonable cost-based fee may apply, and limited denials may be reviewed as described in the notice.",
    "Right to Amend or Supplement. You may request an amendment in writing with reasons. The practice may deny the request under circumstances described in the notice; you may submit a statement of disagreement, and related information will be maintained with subsequent disclosures.",
    "Right to an Accounting of Disclosures. You may request an accounting, subject to the exclusions described in the legacy notice, including certain treatment, payment, operations, authorized, family-notification, research, public-health, oversight, and law-enforcement disclosures.",
    "Right to a Paper or Electronic Copy. You have the right to notice of legal duties and privacy practices and to a paper copy even if you previously requested email delivery.",
  ] },
  { title: "Changes to this notice", paragraphs: ["We reserve the right to amend this Notice of Privacy Practices in the future. Until amended, we are required by law to comply with the notice currently in effect. A revised notice will apply to all protected health information maintained by the practice, regardless of when it was created or received. The current notice will be posted in the reception area, available at appointments, and posted on the website."] },
  { title: "Complaints", paragraphs: ["Complaints about this notice or how the practice handles health information should be directed to the Privacy Officer. The legacy page does not identify that officer and requires owner/legal correction.", "If you are not satisfied with how the office handles a complaint, the legacy notice states that a formal complaint may be submitted to the U.S. Department of Health and Human Services Office for Civil Rights. You will not be penalized for filing a complaint."], items: ["Email published in the legacy notice: OCRMail@hhs.gov", "Federal HIPAA complaint information: hhs.gov/hipaa/filing-a-complaint"] },
]} /> }
