import Link from "next/link";
import Breadcrumbs from "@/app/components/Breadcrumbs";
import JsonLd from "@/app/components/JsonLd";
import { createPageMetadata, createServiceStructuredData } from "@/lib/seo";
import SiteHeader from "@/app/components/SiteHeader";

const path = "/chiropractor-carencro-la";
const description = "Relief Plus serves Carencro and Acadiana with chiropractic care, physical therapy, and regenerative medicine for individualized musculoskeletal recovery.";
export const metadata = createPageMetadata({ title: "Chiropractor Serving Carencro, LA", description, path });

export default function CarencroPage() {
  return <main className="min-h-screen bg-[#f7f5ef] text-[#12233f]">
    <JsonLd data={createServiceStructuredData({ name: "Chiropractic care serving Carencro", description, path })} />
    <SiteHeader />
    <section className="px-6 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><Breadcrumbs currentPage="Chiropractor Serving Carencro" /><div className="mt-12 grid gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-semibold uppercase tracking-[.28em] text-[#9a7428]">Serving Carencro and Acadiana</p><h1 className="mt-6 font-serif text-5xl leading-tight tracking-tight sm:text-7xl">Chiropractic and musculoskeletal care serving Carencro.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[#12233f]/70">Relief Plus brings chiropractic, physical therapy, and regenerative medicine together for people seeking an individualized approach to pain, movement, function, and recovery.</p></div><aside className="rounded-[2rem] bg-[#153e35] p-9 text-white"><h2 className="font-serif text-3xl">Care starts with the individual.</h2><p className="mt-5 leading-7 text-white/70">An examination considers symptoms, movement, health history, daily demands, and goals before treatment options are discussed. No single service is assumed to fit every patient.</p><a href="tel:+13375654200" className="mt-8 inline-block rounded-full bg-[#d5b765] px-6 py-3 text-sm font-semibold text-[#12233f]">Call to Schedule</a></aside></div></div></section>
    <section className="bg-[#12233f] px-6 py-24 text-white lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#d5b765]">The Relief Plus Approach</p><h2 className="mt-5 max-w-3xl font-serif text-4xl sm:text-5xl">Three pillars support a broad view of musculoskeletal recovery.</h2><div className="mt-12 grid gap-px overflow-hidden rounded-3xl bg-white/10 md:grid-cols-3">{[["Chiropractic", "Joint motion, movement, and individualized musculoskeletal care.", "/chiropractic-adjustments-lafayette"], ["Physical Therapy", "Rehabilitation focused on mobility, strength, function, and progression.", "/physical-therapy-lafayette"], ["Regenerative Medicine", "Advanced options considered according to examination and candidacy.", "/regenerative-cellular-therapy-lafayette"]].map(([title, copy, href]) => <Link key={href} href={href} className="bg-[#12233f] p-8 transition hover:bg-white/5"><h3 className="font-serif text-2xl">{title}</h3><p className="mt-4 leading-7 text-white/65">{copy}</p></Link>)}</div></div></section>
    <section className="px-6 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#9a7428]">Thoughtful Next Steps</p><h2 className="mt-5 font-serif text-4xl sm:text-5xl">The right option depends on the clinical picture.</h2><p className="mt-6 leading-7 text-[#12233f]/65">Care may emphasize hands-on treatment, progressive rehabilitation, an advanced option, or coordination among services. Recommendations should match the person and the condition rather than a predetermined protocol.</p></div><div className="rounded-3xl border border-[#12233f]/10 bg-white/50 p-8"><h3 className="font-serif text-2xl">Explore care at Relief Plus</h3><div className="mt-5 grid gap-3"><Link href="/conditions-we-treat" className="rounded-xl border border-[#12233f]/10 p-4 hover:border-[#b08d3b]">Conditions We Treat →</Link><Link href="/dry-needling-lafayette" className="rounded-xl border border-[#12233f]/10 p-4 hover:border-[#b08d3b]">Dry Needling →</Link><Link href="/class-iv-laser-therapy-lafayette" className="rounded-xl border border-[#12233f]/10 p-4 hover:border-[#b08d3b]">Class IV Laser Therapy →</Link><Link href="/shockwave-therapy-lafayette" className="rounded-xl border border-[#12233f]/10 p-4 hover:border-[#b08d3b]">Shockwave Therapy →</Link></div></div></div></section>
  </main>;
}
